(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 35072 "@0='ベイクドアップル社'")
  (define-proc 12 (<> (text "ジェイク")))
  (define-proc 13 (<> (text "エヴァ")))
  (define-proc 14 (<> (text "クリスティ")))
  (define-proc 15 (<> (text-raw 60393 60393 60393)))
  (define-proc 16 (<> (text "猟奇殺人事件")))
  (define-proc 17 (<> (text "アンディ")))
  (branch-reg 22
   (</>
    (/
     (if (</> (// (? (!= M 3)) (nop@) (sound ' 2))))
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b11.gpc")
     (image-mem 0)
     (if (</>
          (//
           (? (!= M 3))
           (nop@)
           (sound ' 0)
           (sound ' "uso¥ap_03.uso")
           (sound ' 1)
           (set-var M 3))))
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (cmd:204 100 119)
     (branch-reg 350
      (</>
       (/ (text "またインタビューされたら嫌だな") (proc 15))
       (/ (proc 13) (text "は戻っているだろうか？"))))
     (proc 18)
     (image-file "gpc¥b12.gpc")
     (exec-mem 8192 "A 1")
     (text-frame 12 16 67 287)
     (text-reset 0)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (exec-mem 8192 "A 1")
     (image-mem 0)
     (image-file "gpc¥b12b.gpc")
     (image-mem 1)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (branch-reg 557
      (</>
       (/
        (text-frame 8 308 71 323)
        (text "眼鏡の男")
        (proc 19)
        (text "き、キミはいったい誰なんだい？" '60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 12)
        (proc 19)
        (text "あのぉ、")
        (proc 13)
        (text "・コートニーさんはいらっしゃいませんか？" '60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (text "眼鏡の男")
        (proc 19)
        (text-raw 60393 60393)
        (text "あっ、わかったぞ！　キミは探偵だね。ボクは")
        (proc 17)
        (text "。")
        (proc 13)
        (text "の同僚なんだよ。" '60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 12)
        (proc 19)
        (text "よろしく、")
        (proc 17)
        (text "。")
        (proc 12)
        (text "・スナイプスです。" '60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 17)
        (proc 19)
        (proc 12)
        (text "って名前なのかぁ")
        (proc 15)
        (text "カッコイイ名前だねぇ。" '60392)
        (set-reg 557 #t))
       (/
        (text-frame 8 308 71 323)
        (proc 17)
        (proc 19)
        (text "や、やあ")
        (proc 15)
        (text "エ、")
        (proc 13)
        (text "はまだ戻ってないよ")
        (proc 15)
        (text-raw 60392))))
     (proc 18))
    (/
     (nop@)
     (sound ' 2)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b12.gpc")
     (image-mem 0)
     (image-file "gpc¥b12b.gpc")
     (image-mem 1)
     (sound ' 0)
     (sound ' "uso¥ap_03.uso")
     (sound ' 1)
     (set-var M 3)
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (cmd:204 24 26)
     (set-reg 22 #f)
     (set-var A 0))))
  (if (</> (// (? (!= A 255)) (nop@) (set-var A 0))))
  (set-var V 0)
  (set-var P 0)
  (set-var C 0)
  (repeat 9 (<> (exec-mem 35072 "A'[C]=0") (inc-var C 1)))
  (loop
   (branch-var P
    (</>
     (/
      (cmd:204 0 11)
      (define-proc 0 (<> (str " ") (text "　　見る　　") (str " ")))
      (set-reg 0 #t)
      (define-proc 1 (<> (str " ") (text "　　話す　　") (str " ")))
      (set-reg 1 #t)
      (define-proc 2 (<> (str " ") (text "　　聞く　　") (str " ")))
      (set-reg 2 #t)
      (define-proc 3 (<> (text "　　考える　　")))
      (set-reg 3 #t)
      (define-proc 4 (<> (str " ") (text "　移動する　") (str " ")))
      (set-reg 4 #t)
      (define-proc 5 (<> (str " ") (text "　システム　") (str " ")))
      (set-reg 5 #t)
      (set-var F 0)
      (mes-load? 0)
      (set-var P 1))
     (/
      (cmd:204 0 11)
      (branch-var V
       (</>
        (/
         (define-proc 0 (<> (text "　　辺りの様子　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　　") (proc 17) (text "　　") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0
          (<> (str " ") (text "　　") (proc 17) (text "　　") (str " ")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　情報提供者の事　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　　ガイの事　　") (str " ")))
         (set-reg 1 #t)
         (define-proc 2 (<> (text "　") (proc 14) (text "の事　")))
         (set-reg 2 #t)
         (define-proc 3
          (<> (str " ") (text "　　記事の事　　") (str " ")))
         (set-reg 3 #t)
         (define-proc 4 (<> (text "　　") (proc 13) (text "の事　　")))
         (set-reg 4 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　情報提供者の事　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　　ガイの事　　") (str " ")))
         (set-reg 1 #t)
         (define-proc 2 (<> (text "　") (proc 14) (text "の事　")))
         (set-reg 2 #t)
         (define-proc 3
          (<> (str " ") (text "　　記事の事　　") (str " ")))
         (set-reg 3 #t)
         (define-proc 4 (<> (text "　　") (proc 13) (text "の事　　")))
         (set-reg 4 #t)
         (define-proc 5
          (<> (str " ") (text "　") (proc 17) (text "の事　") (str " ")))
         (set-reg 5 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　他の場所へ　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　セーブ　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "ゲームを終了する") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 0)
         (if (</>
              (//
               (? (!= S 255))
               (nop@)
               (if (</>
                    (//
                     (? (!= A 255))
                     (nop@)
                     (set-var A 255)
                     (mes-load? "mes¥save.mec" 4096))))
               (mes-load? 4096)
               (if (</>
                    (// (? (= S 254)) (nop@) (set-var P 1))
                    (// (nop@) (set-var F 5) (mes-load? 0))))))))))
      (if (</> (// (? (= S 255)) (nop@) (set-var P 0)))))
     (/
      (if (</>
           (//
            (? (= V 4))
            (nop@)
            (nop@)
            (set-reg 24 #f)
            (set-reg 25 #f)
            (set-reg 26 #f))
           (//
            (nop@)
            (if (</> (// (? (= 26 #t)) (nop@) (set-var F 1) (mes-load? 4096))))
            (set-var F 6)
            (mes-load? 0))))
      (text-frame 14 328 69 383)
      (seg-call)
      (branch-reg 23 (</> (/ (proc 18)) (/ (set-reg 23 #f))))
      (set-var P 0))))))
 (seg (? (= V 0) (= N 0))
      (branch-reg 100
       (</>
        (/
         (proc 13)
         (text "の姿のないこの場所は、スパイスを忘れた料理の様に味気ない。")
         (set-reg 100 #t))
        (/
         (text "こんな場所でも隔週刊誌を出しているのだから大したものだ。")
         (set-reg 100 #f)))))
 (seg (? (= V 0))
      (if (</>
           (//
            (? (= 101 #f))
            (text "椅子に縮こまって座る姿は滑稽とも言える。")
            (set-reg 101 #t))
           (//
            (? (= 102 #f))
            (text "彼のオフィスでもあるこの場所でなぜああまでおどおどとした態度をとっているのだろう？")
            (set-reg 102 #t))
           (//
            (text "失礼な言い方だが、彼が")
            (proc 13)
            (text "のアシスタントであるのが事実なら、彼女はかなりストレスを感じているのではないか？")
            (set-reg 101 #f)
            (set-reg 102 #f)))))
 (seg (? (= V 1) (= 354 #f))
      (text-frame 8 308 71 323)
      (proc 17)
      (proc 19)
      (text "ね、ねぇ")
      (proc 12)
      (proc 15)
      (text "あ、あのぉ")
      (proc 15)
      (text "そ、そのさぁ")
      (proc 15)
      (proc 13)
      (text "とはどういう関係なんだい？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "どういう関係と言われても")
      (proc 15)
      (text "難しいな、なんて説明すればいいんだろう？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 17)
      (proc 19)
      (text "も、もしかして、恋人？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "いや、そんな関係じゃないよ。彼女の書いた記事に関して聞きたい事があって来ているだけさ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 17)
      (proc 19)
      (text "ああ、ああそうなのかぁ")
      (proc 15)
      (text "よ、よかった。" '60392)
      (set-reg 354 #t))
 (seg (? (= V 1) (= 355 #f))
      (text-frame 8 308 71 323)
      (proc 17)
      (proc 19)
      (text "ぼっ、ボクは、ここで")
      (proc 13)
      (text "のアシスタントみたいな事してるんだよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (proc 13)
      (text "の下だと大変そうだね。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 17)
      (proc 19)
      (text "大変って言えば大変かなぁ")
      (proc 15)
      (text "彼女は元気でボクは元気じゃないから、か、彼女のペースに合わせると大変なんだ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "それは大変だね")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 17)
      (proc 19)
      (text "う、うん")
      (proc 15)
      (text-raw 60392)
      (set-reg 355 #t))
 (seg (? (= V 1) (= 356 #f))
      (text-frame 8 308 71 323)
      (proc 17)
      (proc 19)
      (proc 12)
      (text "は堂々としていてう、羨ましいなぁ")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "別に普通だよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 17)
      (proc 19)
      (text "ボクは人前に出ると上がっちゃって")
      (proc 15)
      (text "一人で話してると普通なんだけど")
      (proc 15)
      (text "ご、ゴメン")
      (proc 15)
      (text-raw 60392)
      (set-reg 356 #t))
 (seg (? (= V 1))
      (text-frame 8 308 71 323)
      (proc 17)
      (proc 19)
      (text "エ、")
      (proc 13)
      (text "、早く帰って来るといいのに")
      (proc 15)
      (proc 15)
      (text-raw 60392))
 (seg (? (= V 2) (= N 0))
      (branch-reg 357
       (</>
        (/
         (text-frame 8 308 71 323)
         (proc 17)
         (proc 19)
         (text "ぼ、ボクはそういうの知らないんだ。ご、ゴメンね、役に立てなくて")
         (proc 15)
         (text-raw 60392)
         (set-reg 357 #t))
        (/
         (text-frame 8 308 71 323)
         (proc 17)
         (proc 19)
         (text "本当に、ほ、本当に知らないんだよぉ")
         (proc 15)
         (text-raw 60392)))))
 (seg (? (= V 2) (= N 1))
      (if (</>
           (//
            (? (= 358 #f))
            (text-frame 8 308 71 323)
            (proc 17)
            (proc 19)
            (text "ガイって")
            (proc 15)
            (text "ネ、ネッツのガイ選手のコトかな？" '60392)
            (proc 18)
            (text-frame 8 308 71 323)
            (proc 12)
            (proc 19)
            (text "ああ、そうだよ。彼が")
            (proc 13)
            (text "と仲良しだって聞いてない？" '60392)
            (proc 18)
            (text-frame 8 308 71 323)
            (proc 17)
            (proc 19)
            (proc 15)
            (text "さ、さぁ？　そんなコトないと思うんだけど。" '60392)
            (set-reg 358 #t))
           (//
            (? (= 359 #f))
            (text-frame 8 308 71 323)
            (proc 12)
            (proc 19)
            (text "何かガイに関する話を耳にしてないかな？" '60392)
            (proc 18)
            (text-frame 8 308 71 323)
            (proc 17)
            (proc 19)
            (text "ぼ、ボクは")
            (proc 15)
            (text "そういうことあんまり知らないんだ。" '60392)
            (proc 18)
            (text-frame 8 308 71 323)
            (proc 12)
            (proc 19)
            (text "そうか")
            (proc 15)
            (text-raw 60392)
            (proc 18)
            (text-frame 8 308 71 323)
            (proc 17)
            (proc 19)
            (text "ご、ゴメンよ")
            (proc 15)
            (text "役に立てなくて")
            (proc 15)
            (text-raw 60392)
            (set-reg 359 #t))
           (//
            (text-frame 8 308 71 323)
            (proc 17)
            (proc 19)
            (text "ぼ、ボク")
            (proc 15)
            (text "役立たずなんだ")
            (proc 15)
            (text-raw 60392)))))
 (seg (? (= V 2) (= N 2))
      (branch-reg 360
       (</>
        (/
         (text-frame 8 308 71 323)
         (proc 17)
         (proc 19)
         (text "く、")
         (proc 14)
         (proc 15)
         (text "？　ゴメン、その人は知らない")
         (proc 15)
         (text-raw 60392)
         (proc 18)
         (text-frame 8 308 71 323)
         (proc 12)
         (proc 19)
         (text "ガイの知りあいなんだけどね。" '60392)
         (proc 18)
         (text-frame 8 308 71 323)
         (proc 17)
         (proc 19)
         (text "役に立てなくて")
         (proc 15)
         (text "ゴメンね")
         (proc 15)
         (text-raw 60392)
         (set-reg 360 #t))
        (/
         (text-frame 8 308 71 323)
         (proc 17)
         (proc 19)
         (text "ボクって")
         (proc 15)
         (text "な、なんて役立たずなんだろう")
         (proc 15)
         (text-raw 60392)))))
 (seg (? (= V 2) (= N 3))
      (branch-reg 361
       (</>
        (/
         (text-frame 8 308 71 323)
         (proc 17)
         (proc 19)
         (text "ボク")
         (proc 15)
         (text "記事のことは、ち、ちっとも知らない。" '60392)
         (proc 18)
         (text-frame 8 308 71 323)
         (proc 12)
         (proc 19)
         (text "アシスタントなのに？" '60392)
         (proc 18)
         (text-frame 8 308 71 323)
         (proc 17)
         (proc 19)
         (text "うっ、うん")
         (text-raw 60393 60393)
         (text "ボクってなっ、なんて役立たずなんだろう。" '60392)
         (set-reg 361 #t))
        (/
         (text-frame 8 308 71 323)
         (proc 17)
         (proc 19)
         (text "ゴメンよぉ、ゴメンよぉぉぉ")
         (proc 15)
         (text-raw 60392)))))
 (seg (? (= V 2))
      (if (</>
           (//
            (? (= 362 #f))
            (text-frame 8 308 71 323)
            (proc 17)
            (proc 19)
            (text "エ、")
            (proc 13)
            (text "はボクの、あ、憧れなんだ。つ、強くて元気な、" 'br)
            (text "す、素晴らしい女性だよ。" '60392)
            (proc 18)
            (text-frame 8 308 71 323)
            (proc 12)
            (proc 19)
            (text "確かに、彼女は強そうだね。" '60392)
            (proc 18)
            (text-frame 8 308 71 323)
            (proc 17)
            (proc 19)
            (text "うん。何にも負けない")
            (proc 15)
            (text "彼女は負けないんだ。" '60392)
            (set-reg 362 #t))
           (//
            (? (= 363 #f))
            (text-frame 8 308 71 323)
            (proc 17)
            (proc 19)
            (text "か、彼女は、ああ見えてもど、努力家なんだ。" '60392)
            (proc 18)
            (text-frame 8 308 71 323)
            (proc 12)
            (proc 19)
            (text "努力家？" '60392)
            (proc 18)
            (text-frame 8 308 71 323)
            (proc 17)
            (proc 19)
            (text "うん、そ、そうだよ！　貧乏暮らしだったけど頑張って学校に行って")
            (proc 15)
            (text "頑張ったから今の彼女がいるんだよ。" '60392)
            (set-reg 363 #t))
           (//
            (text-frame 8 308 71 323)
            (proc 17)
            (proc 19)
            (text "エ、")
            (proc 13)
            (text "のこと悪く言う人もいる、けど")
            (proc 15)
            (text "彼女はいい人なんだ")
            (proc 15)
            (text "ほ、本当は。" '60392)))))
 (seg (? (= V 3) (= N 0))
      (branch-reg 357
       (</>
        (/
         (proc 17)
         (text "が")
         (proc 13)
         (text "の情報提供者のことを知っていればラッキーなんだが")
         (proc 15))
        (/
         (proc 17)
         (text "は知らないのか")
         (proc 15)
         (text "残念だな。")))))
 (seg (? (= V 3) (= N 1))
      (branch-reg 359
       (</>
        (/
         (text "アンデイからガイの情報を得る事が出来れば")
         (proc 15))
        (/
         (text "目の前の彼から情報を得るのは無理のようだな。")))))
 (seg (? (= V 3) (= N 2))
      (branch-reg 360
       (</>
        (/
         (proc 13)
         (text "のことだ、きっと")
         (proc 14)
         (text "の悪口でも言っているに違いない。"))
        (/
         (text "考えてみれば、何も")
         (proc 17)
         (text "に聞く事でもないのか")
         (proc 15)))))
 (seg (? (= V 3) (= N 3))
      (branch-reg 361
       (</>
        (/
         (proc 17)
         (text "が記事のことについて知っているとは思えないが")
         (proc 15))
        (/ (text "やはり彼からは何も聞けないようだな。")))))
 (seg (? (= V 3) (= N 4))
      (if (</>
           (//
            (? (= 363 #f) (= 364 #f))
            (proc 17)
            (text "から")
            (proc 13)
            (text "のことが聞けるかも知れない。")
            (set-reg 364 #t))
           (//
            (? (= 363 #f))
            (proc 13)
            (text "はいつ帰って来るんだろう？"))
           (//
            (? (= 365 #f))
            (text "彼女が努力家だなんて")
            (proc 15)
            (text "いや、執念深さが努力家という言葉に置き換えられたんだろう、きっと。")
            (set-reg 365 #t))
           (//
            (proc 13)
            (text "が戻るまで待っているわけにもいかないな")
            (proc 15)))))
 (seg (? (= V 3))
      (branch-reg 366
       (</>
        (/
         (text "見た目通りの人物だな。決して悪人ではないと思うが、付き合い辛いタイプかもしれない")
         (proc 15)
         (set-reg 366 #t))
        (/
         (text "彼はどうしておどおどしているのだろう？　僕の顔が怖いというわけでもないだろうに")
         (proc 15)))))
 (seg (? (= V 4)) (nop@) (mes-jump "b:¥mes¥109map.mes"))
 (seg*
  (nop@)
  (text "※※※　バグです　※※※" 'br)
  (text "Ｖ＝")
  (exec-mem 35072 "DISP V")
  (text "　Ｎ＝")
  (exec-mem 35072 "DISP N")))