(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 35072 "@0='クリスティの家'")
  (define-proc 12 (<> (text "ジェイク")))
  (define-proc 13 (<> (text "ユリコ")))
  (define-proc 14 (<> (text "クリスティ")))
  (define-proc 15 (<> (text-raw 60393 60393 60393)))
  (define-proc 16 (<> (text "猟奇殺人事件")))
  (branch-reg 22
   (</>
    (/
     (if (</> (// (? (!= M 3)) (nop@) (sound ' 2))))
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b13.gpc")
     (image-mem 0)
     (if (</>
          (//
           (? (!= M 3))
           (nop@)
           (sound ' 0)
           (sound ' "uso¥ap_03.uso")
           (sound ' 1)
           (set-var M 3))))
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (cmd:204 100 199)
     (proc 14)
     (text "のことが気になってやってきたが")
     (proc 15)
     (text "果たして、中に入れてもらえるのだろうか？")
     (proc 18)
     (image-file "gpc¥b14.gpc")
     (exec-mem 8192 "A 1")
     (text-frame 12 16 67 287)
     (text-reset 0)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (exec-mem 8192 "A 1")
     (image-mem 0)
     (image-file "gpc¥b14a.gpc")
     (image-mem 1)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (text-frame 8 308 71 323)
     (proc 14)
     (proc 19)
     (text "あら、")
     (proc 12)
     (text "。久しぶりじゃない！" '60392)
     (proc 18)
     (text-frame 8 308 71 323)
     (proc 12)
     (proc 19)
     (proc 14)
     (text "、何言ってるんだ、さっきも来たじゃないか。" '60392)
     (proc 18)
     (text-frame 8 308 71 323)
     (proc 14)
     (proc 19)
     (proc 15)
     (text "やぁね、")
     (proc 12)
     (text "ったら。私をからかってるのね。" '60392)
     (proc 18)
     (text-frame 8 308 71 323)
     (proc 12)
     (proc 19)
     (proc 14)
     (proc 15)
     (text "？" '60392)
     (proc 18)
     (text-frame 8 308 71 323)
     (proc 14)
     (proc 19)
     (text "きょとんとした顔して")
     (proc 15)
     (text "今日の貴方はおかしくてよ。" '60392)
     (proc 18))
    (/
     (nop@)
     (sound ' 2)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b14.gpc")
     (image-mem 0)
     (image-file "gpc¥b14a.gpc")
     (image-mem 1)
     (sound ' 0)
     (sound ' "uso¥ap_03.uso")
     (sound ' 1)
     (set-var M 3)
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (cmd:204 24 26)
     (set-reg 22 #f)
     (set-var A 0))))
  (if (</> (// (? (!= A 255)) (nop@) (set-var A 0))))
  (set-var V 0)
  (set-var P 0)
  (set-var C 0)
  (repeat 9 (<> (exec-mem 35072 "A'[C]=0") (inc-var C 1)))
  (loop
   (branch-var P
    (</>
     (/
      (cmd:204 0 11)
      (define-proc 0 (<> (str " ") (text "　　見る　　") (str " ")))
      (set-reg 0 #t)
      (define-proc 1 (<> (str " ") (text "　　話す　　") (str " ")))
      (set-reg 1 #t)
      (define-proc 2 (<> (str " ") (text "　　聞く　　") (str " ")))
      (set-reg 2 #t)
      (define-proc 3 (<> (text "　　考える　　")))
      (set-reg 3 #t)
      (define-proc 4 (<> (str " ") (text "　移動する　") (str " ")))
      (exec-mem 35072 "#4=#553")
      (define-proc 5 (<> (str " ") (text "　システム　") (str " ")))
      (set-reg 5 #t)
      (set-var F 0)
      (mes-load? 0)
      (set-var P 1))
     (/
      (cmd:204 0 11)
      (branch-var V
       (</>
        (/
         (define-proc 0 (<> (text "　　辺りの様子　　")))
         (set-reg 0 #t)
         (define-proc 1 (<> (text "　　") (proc 14) (text "　　")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　") (proc 14) (text "　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0
          (<> (str " ") (text "　　ガイの事　　") (str " ")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　") (proc 14) (text "の事　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　　ガイの事　　") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　他の場所へ　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　セーブ　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "ゲームを終了する") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 0)
         (if (</>
              (//
               (? (!= S 255))
               (nop@)
               (if (</>
                    (//
                     (? (!= A 255))
                     (nop@)
                     (set-var A 255)
                     (mes-load? "mes¥save.mec" 4096))))
               (mes-load? 4096)
               (if (</>
                    (// (? (= S 254)) (nop@) (set-var P 1))
                    (// (nop@) (set-var F 5) (mes-load? 0))))))))))
      (if (</> (// (? (= S 255)) (nop@) (set-var P 0)))))
     (/
      (if (</>
           (//
            (? (= V 4))
            (nop@)
            (nop@)
            (set-reg 24 #f)
            (set-reg 25 #f)
            (set-reg 26 #f))
           (//
            (nop@)
            (if (</> (// (? (= 26 #t)) (nop@) (set-var F 1) (mes-load? 4096))))
            (set-var F 6)
            (mes-load? 0))))
      (text-frame 14 328 69 383)
      (seg-call)
      (branch-reg 23 (</> (/ (proc 18)) (/ (set-reg 23 #f))))
      (set-var P 0))))))
 (seg (? (= V 0) (= N 0))
      (text "いつもと何等変わる事のない部屋なのに、何故だか見知らぬ場所のように感じられる")
      (proc 15))
 (seg (? (= V 0))
      (text "うっすらと笑みをたたえている顔に狂気を感じるのは気のせいだと思いたい")
      (proc 15))
 (seg (? (= V 1) (= 100 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "ガイと一緒に来てくれればよかったのに。うふふ")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (proc 14)
      (text "？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "ガイともうすぐ結婚するでしょ？　だからね、準備が大変なのよ、嬉しい悲鳴をあげたいって感じかしら。" '60392)
      (set-reg 100 #t))
 (seg (? (= V 1) (= 101 #f))
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (proc 14)
      (text "、どうかしたの？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "いやぁねぇ、難しい顔しちゃって")
      (proc 15)
      (text "どうかしたのは貴方の方じゃなくて？　困った人")
      (proc 15)
      (text "うふふ。" '60392)
      (set-reg 101 #t))
 (seg (? (= V 1))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "ああ、結婚式が待ちどおしいわぁ。" '60392))
 (seg (? (= V 2) (= 102 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "ガイ？　彼は私の愛しい人よ。いやねぇ、今更何を言ってるのかしら私ったら。うふふ")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (proc 15)
      (text "なんかバカな質問しちゃったね。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "本当にそうよ。貴方がガイと私の事を一番よく知ってる人なのに")
      (proc 15)
      (text "二人して変よねぇ")
      (proc 15)
      (text "くすす。" '60392)
      (set-reg 102 #t))
 (seg (? (= V 2) (= 103 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "今日はガイとウエディングドレスを見に行くの。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "そんな予定があったの？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "いやだ、")
      (proc 12)
      (text "何を言ってるの？　ガイと貴方で決めてくれたスケジュールじゃないの。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "えっ")
      (proc 15)
      (text "？　")
      (proc 14)
      (text "、何を言って")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "うふふ、おかしな")
      (proc 12)
      (text "ね。" '60392)
      (set-reg 103 #t))
 (seg (? (= V 2))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "どんなドレスにしようかしら、ね？" '60392))
 (seg (? (= V 3) (= N 0))
      (if (</>
           (//
            (? (= 553 #t))
            (proc 14)
            (text "は精神的にかなり参っているようだ。早くなんとかしてあげなくては")
            (proc 15))
           (//
            (? (= 101 #t) (= 103 #t))
            (text "まるで狂ってしまったようだ。いや、すでに心が壊れてしまったのかもしれない")
            (proc 15)
            (set-reg 553 #t))
           (// (proc 14) (text "の様子がどこかおかしい。")))))
 (seg (? (= V 3))
      (branch-reg 105
       (</>
        (/
         (text "ガイが")
         (proc 14)
         (text "とのことをどう考えているのかわからない。")
         (proc 18)
         (text "しかし、このままでは")
         (proc 14)
         (text "がダメになってしまう。")
         (set-reg 105 #t))
        (/ (text "ガイは") (proc 14) (text "と直接話をすべきだ。")))))
 (seg (? (= V 4)) (nop@) (mes-jump "b:¥mes¥109map.mes"))
 (seg*
  (nop@)
  (text "※※※　バグです　※※※" 'br)
  (text "Ｖ＝")
  (exec-mem 35072 "DISP V")
  (text "　Ｎ＝")
  (exec-mem 35072 "DISP N")))