(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 35072 "@0='リトルイタリー'")
  (define-proc 12 (<> (text "ジェイク")))
  (define-proc 13 (<> (text "売り子")))
  (define-proc 14 (<> (text "隣のおばさん")))
  (define-proc 15 (<> (text-raw 60393 60393 60393)))
  (define-proc 16 (<> (text "猟奇殺人事件")))
  (branch-reg 22
   (</>
    (/
     (cmd:204 100 119)
     (if (</> (// (? (!= M 3)) (nop@) (sound ' 2))))
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "b:¥gpc¥b05.gpc")
     (image-mem 0)
     (if (</>
          (//
           (? (= 806 #f))
           (nop@)
           (exec-mem 8192 "G 1 15 101 21 187")
           (image-file "b:¥gpc¥b05a.gpc")
           (image-mem 1))))
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (if (</>
          (//
           (? (!= M 3))
           (nop@)
           (sound ' 0)
           (sound ' "uso¥ap_03.uso")
           (sound ' 1)
           (set-var M 3))))
     (cmd:209 1 2)
     (text "すでに日課と化したようなリトルイタリー詣でである。")
     (proc 18))
    (/
     (nop@)
     (sound ' 2)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "b:¥gpc¥b05.gpc")
     (image-mem 0)
     (if (</>
          (//
           (? (= 806 #f))
           (nop@)
           (exec-mem 8192 "G 1 15 101 21 187")
           (image-file "b:¥gpc¥b05a.gpc")
           (image-mem 1))))
     (sound ' 0)
     (sound ' "uso¥ap_03.uso")
     (sound ' 1)
     (set-var M 3)
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (cmd:204 24 26)
     (set-reg 22 #f)
     (set-var A 0))))
  (if (</> (// (? (!= A 255)) (nop@) (set-var A 0))))
  (set-var V 0)
  (set-var P 0)
  (set-var C 0)
  (repeat 9 (<> (exec-mem 35072 "A'[C]=0") (inc-var C 1)))
  (loop
   (branch-var P
    (</>
     (/
      (cmd:204 0 11)
      (define-proc 0 (<> (str " ") (text "　　見る　　") (str " ")))
      (set-reg 0 #t)
      (define-proc 1 (<> (str " ") (text "　　話す　　") (str " ")))
      (set-reg 1 #t)
      (define-proc 2 (<> (str " ") (text "　　聞く　　") (str " ")))
      (exec-mem 35072 "#2=#806")
      (define-proc 3 (<> (text "　　考える　　")))
      (exec-mem 35072 "#3=#806")
      (define-proc 4 (<> (str " ") (text "　移動する　") (str " ")))
      (exec-mem 35072 "#4=#806")
      (define-proc 5 (<> (str " ") (text "　システム　") (str " ")))
      (set-reg 5 #t)
      (set-var F 0)
      (mes-load? 0)
      (set-var P 1))
     (/
      (cmd:204 0 11)
      (branch-var V
       (</>
        (/
         (define-proc 0 (<> (text "　　辺りの様子　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　新聞スタンド　") (str " ")))
         (set-reg 1 #t)
         (define-proc 2
          (<> (str " ") (text "　　　雑誌　　　") (str " ")))
         (set-reg 2 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　") (proc 13) (text "　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　") (proc 14) (text "　") (str " ")))
         (exec-mem 35072 "#1=(#806==0)")
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (str " ") (proc 16) (text "の事") (str " ")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　アンナの事　　")))
         (set-reg 0 #t)
         (define-proc 1 (<> (str " ") (proc 16) (text "の事") (str " ")))
         (set-reg 1 #t)
         (define-proc 2 (<> (text "　　エヴァの事　　")))
         (exec-mem 35072 "#2=#806")
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　アンナの家　　")))
         (set-reg 0 #t)
         (define-proc 1 (<> (text "　　他の場所へ　　")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　セーブ　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "ゲームを終了する") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 0)
         (if (</>
              (//
               (? (!= S 255))
               (nop@)
               (if (</>
                    (//
                     (? (!= A 255))
                     (nop@)
                     (set-var A 255)
                     (mes-load? "mes¥save.mec" 4096))))
               (mes-load? 4096)
               (if (</>
                    (// (? (= S 254)) (nop@) (set-var P 1))
                    (// (nop@) (set-var F 5) (mes-load? 0))))))))))
      (if (</> (// (? (= S 255)) (nop@) (set-var P 0)))))
     (/
      (if (</>
           (//
            (? (= V 4) (= N 1))
            (nop@)
            (nop@)
            (set-reg 24 #f)
            (set-reg 25 #f)
            (set-reg 26 #f))
           (//
            (nop@)
            (if (</> (// (? (= 26 #t)) (nop@) (set-var F 1) (mes-load? 4096))))
            (set-var F 6)
            (mes-load? 0))))
      (text-frame 14 328 69 383)
      (seg-call)
      (branch-reg 23 (</> (/ (proc 18)) (/ (set-reg 23 #f))))
      (set-var P 0))))))
 (seg (? (= V 0) (= N 0))
      (branch-random (</>
                      (/
                       (text "イタリア料理の店が並ぶこの通りは、リトルイタリーの中で" 'br)
                       (text "一番賑やかな通りだ。"))
                      (/
                       (text "これといって特に変わったところはないようだ。"))
                      (/
                       (text "この通りもすっかり馴染みになってしまった。")))))
 (seg (? (= V 0) (= N 1))
      (branch-random (</>
                      (/
                       (text "相変わらず、いつもの")
                       (proc 13)
                       (text "が店番をしている。ここは彼の個人経営なのかな？"))
                      (/
                       (text "窮屈な感じがするが、えてして新聞スタンドとはこういうものだろう。")))))
 (seg (? (= V 0))
      (branch-random (</>
                      (/
                       (text "イタリアン、アメリカン、チャイニーズ")
                       (proc 15)
                       (text "いろいろな国の雑誌が所狭しと並べられている。"))
                      (/
                       (text "これだけある雑誌の中には数ヶ月で廃刊になってしまうものもあるのだろう。")))))
 (seg (? (= V 1) (= N 0) (= 601 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "よぉ、ダンナ！　最近よく来るね。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "うん、ちょっと野暮用でね。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "なんだ、まぁだ彼女に会ってもらえないのかい？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "そういうんじゃないよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "はぁ" '60517)
      (text "あ、ダンナも意外とモテないねぇ。" '60392)
      (set-reg 601 #t))
 (seg (? (= V 1) (= N 0))
      (branch-random (</>
                      (/
                       (text-frame 8 308 71 323)
                       (proc 13)
                       (proc 19)
                       (text "今日は何を買ってってくれるんだい？" '60392))
                      (/
                       (text-frame 8 308 71 323)
                       (proc 13)
                       (proc 19)
                       (text "ダンナ" '60517)
                       (text "、邪魔しにきただけなら勘弁だよぉ。" '60392))
                      (/
                       (text-frame 8 308 71 323)
                       (proc 13)
                       (proc 19)
                       (text "ダンナ" '60517)
                       (text "、ただ見はお断りだよぉ。" '60392)))))
 (seg (? (= V 1))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "おや、あんたこの前の")
      (proc 15)
      (text-raw 60393 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "その節はお世話になりました。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "あんた、マスコミの人じゃないって本当かい？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "はい。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "だったらいいんだけど")
      (proc 15)
      (text "はぁ" '60517)
      (text "あ")
      (proc 15)
      (text-raw 60393 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "何かあったんですか？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "いやね、実はさぁ、なんとかアップルの記者だとか言う女が来て、アンナに会わせろ、居場所教えろってうるさいんだよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "女記者、ですか？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "そうそう。こう目のキッと釣り上がった女で、乳だけはデカイ女でさ。もう、もんのすごくイヤな奴なんだよぉ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "それ、もしかしてエヴァ・コートニーという女では？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "あぁ、そう、それだよ、それ！　あんたの知り合いかい？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "知り合いというわけではないですが、顔見知りです。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "悪い事はいわないよ。あんな女とは付き合うのやめた方がいいよ。あんたまでイヤな人間だと思われるからね。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "あらあら、思わぬ時間を取っちまったねぇ。急いで帰らなきゃいけないよ。それじゃあね。" '60392)
      (proc 18)
      (exec-mem 8192 "A 1,P 1 15 101,F 1,A 0")
      (exec-mem 17664 15 101 35 287 1 0)
      (set-reg 23 #t)
      (set-reg 806 #t))
 (seg (? (= V 2) (= 806 #t) (= 610 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "ああ、そういやぁまた新しい事件があったよな。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "新しい事件？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "そう。まだ例の事件かどうかはわかんないらしいけど、この" 'br)
      (text "ニューヨークにも殺人鬼がやって来たらしいぜ。" '60392)
      (set-reg 610 #t))
 (seg (? (= V 2) (= 806 #t) (= 611 #f))
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "殺人鬼がやって来た？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "なんでもよ、埠頭で女の死体が発見されてその両手首から先がなかったって話だ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "また、切断されてた、か")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "そういうこと。切り口はやっぱり関節からキレイに")
      (proc 15)
      (text "って言ったらどうもアレ臭いだろ？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "なるほど")
      (proc 15)
      (text-raw 60393 60392)
      (set-reg 611 #t))
 (seg (? (= V 2) (= 806 #t))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "世間が何と言ったって、オレはニューヨークの殺しも今までの奴と同じ奴の犯行だと思うね。" '60392))
 (seg (? (= V 2))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "唐突にそんなコト言われても")
      (proc 15)
      (text "この前話してやったことが全てだぜ。" '60392))
 (seg (? (= V 3) (= N 0) (= 806 #t))
      (text "アンナの不在とエヴァの行動に関連があるとしたら")
      (text-raw 60393 60393)
      (text "メリルの娘のことだろうか？"))
 (seg (? (= V 3) (= N 0) (= 602 #f))
      (text "アンナの不在の長さが気になる。彼女はどこに何をしに行ったのだろう")
      (proc 15)
      (text "？")
      (set-reg 602 #t))
 (seg (? (= V 3) (= N 0))
      (text "アンナが戻って来てくれない事には商売上がったりだ。"))
 (seg (? (= V 3) (= N 1) (= 611 #t))
      (if (</>
           (//
            (? (= 612 #f))
            (text "もともとニューヨークでの犯罪自体は珍しいものではないが、両手首のない女性の死体となると")
            (proc 15)
            (proc 18)
            (text "やはり、サンフランシスコ・ロサンジェルス・デトロイトと続いた一連の事件に関連がある気がする。")
            (set-reg 612 #t))
           (//
            (? (= 613 #f))
            (text "それにしても、この犯人、次はどこで犯行するつもりなのだろうか？")
            (proc 18)
            (text "今までのことを考えると別の都市に移動するのだろうが")
            (proc 15)
            (set-reg 613 #t))
           (// (text "早く犯人が捕まる事を祈るさ。")))))
 (seg (? (= V 3) (= N 1) (= 603 #f))
      (text "ニューヨークでも殺人事件が起きたばかりだ。どうしてこう事件が絶えないのだろう")
      (proc 15)
      (set-reg 603 #t))
 (seg (? (= V 3) (= N 1))
      (text "どうして人と人が殺しあったりするのかな")
      (proc 15))
 (seg (? (= V 3))
      (if (</>
           (//
            (? (= 614 #f))
            (text "エヴァがアンナを訪ねて来ていたって？")
            (proc 18)
            (text "一体何のために")
            (proc 15)
            (text '60393 "？")
            (set-reg 614 #t))
           (//
            (? (= 615 #f))
            (text "エヴァの行く所事件あり")
            (text-raw 60485 60484)
            (text "となると、まさかメリルの娘の事を嗅ぎ付けたんじゃ！？")
            (set-reg 615 #t))
           (//
            (text "エヴァに依頼を邪魔されるのだけは勘弁だ。")))))
 (seg (? (= V 4) (= N 0) (= 100 #t))
      (text "しばらく時間を置いてからの方がいいんじゃないか？"))
 (seg (? (= V 4) (= N 0))
      (mes-load? "mes¥win_c.mec" 4096)
      (mes-load? 4096)
      (branch-random (</>
                      (/
                       (text "呼び鈴を鳴らす前にポストを覗いてみたが、相変わらず郵便物が詰まっていた。")
                       (proc 18)
                       (text-frame 8 308 71 323)
                       (proc 12)
                       (proc 19)
                       (text "また出直しか")
                       (proc 15)
                       (text-raw 60392)
                       (proc 18)
                       (text "ため息混じりに一人ごちて、通りに戻った。"))
                      (/
                       (text "アンナはまだ戻っていない。いつになったら会うことが出来るのだろう。"))))
      (set-reg 100 #t)
      (proc 18)
      (set-reg 23 #t)
      (exec-mem 8192 "A 1")
      (text-frame 0 0 79 399)
      (text-reset 0)
      (exec-mem 256 0 6 58 36 1 2 0 2560 2560 1 1)
      (image-file "b:¥gpc¥b05.gpc")
      (image-mem 0 3 1 56)
      (exec-mem 8192 "A 0")
      (mes-load? "mes¥win_o.mec" 4096)
      (mes-load? 4096)
      (set-var A 1))
 (seg (? (= V 4)) (mes-jump "b:¥mes¥111map.mes"))
 (seg*
  (nop@)
  (text "※※※　バグです　※※※" 'br)
  (text "Ｖ＝")
  (exec-mem 35072 "DISP V")
  (text "　Ｎ＝")
  (exec-mem 35072 "DISP N")))