(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 35072 "@0='セントレジナスホテル'")
  (define-proc 12 (<> (text "ジェイク")))
  (define-proc 14 (<> (text "メリル")))
  (define-proc 15 (<> (text-raw 60393 60393 60393)))
  (branch-reg 22
   (</>
    (/
     (cmd:204 100 199)
     (if (</> (// (? (!= M 3)) (nop@) (sound ' 2))))
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b09.gpc")
     (image-mem 0)
     (if (</>
          (//
           (? (!= M 3))
           (nop@)
           (sound ' 0)
           (sound ' "uso¥ap_03.uso")
           (sound ' 1)
           (set-var M 3))))
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (delay 50)
     (image-file "gpc¥b10.gpc")
     (exec-mem 8192 "A 1")
     (text-frame 12 16 67 287)
     (text-reset 0)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (exec-mem 8192 "A 1")
     (image-mem 0)
     (image-file "gpc¥b10a.gpc")
     (image-mem 1)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (branch-reg 200
      (</>
       (/
        (text-frame 8 308 71 323)
        (proc 14)
        (proc 19)
        (text "あら、やっと娘とのスケジュール組んでくれたのね？" '60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 12)
        (proc 19)
        (text "いえ、実はまだなんです")
        (proc 15)
        (text-raw 60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 14)
        (proc 19)
        (text "それじゃ一体何しに来たの？" '60392)
        (set-reg 200 #t))
       (/
        (text-frame 8 308 71 323)
        (proc 14)
        (proc 19)
        (text "こんどは娘との話をつけて来てくれたんでしょうね？" '60392))))
     (proc 18))
    (/
     (nop@)
     (sound ' 2)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b10.gpc")
     (image-mem 0)
     (image-file "gpc¥b10a.gpc")
     (image-mem 1)
     (sound ' 0)
     (sound ' "uso¥ap_03.uso")
     (sound ' 1)
     (set-var M 3)
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (cmd:204 24 26)
     (set-reg 22 #f)
     (set-var A 0))))
  (if (</> (// (? (!= A 255)) (nop@) (set-var A 0))))
  (set-var V 0)
  (set-var P 0)
  (set-var C 0)
  (repeat 9 (<> (exec-mem 35072 "A'[C]=0") (inc-var C 1)))
  (loop
   (branch-var P
    (</>
     (/
      (cmd:204 0 11)
      (define-proc 0 (<> (str " ") (text "　　見る　　") (str " ")))
      (set-reg 0 #t)
      (define-proc 1 (<> (str " ") (text "　　話す　　") (str " ")))
      (set-reg 1 #t)
      (define-proc 2 (<> (str " ") (text "　　聞く　　") (str " ")))
      (exec-mem 35072 "#2=#202")
      (define-proc 3 (<> (text "　　考える　　")))
      (exec-mem 35072 "#3=#202")
      (define-proc 4 (<> (str " ") (text "　移動する　") (str " ")))
      (exec-mem 35072 "#4=#202")
      (define-proc 5 (<> (str " ") (text "　システム　") (str " ")))
      (set-reg 5 #t)
      (set-var F 0)
      (mes-load? 0)
      (set-var P 1))
     (/
      (cmd:204 0 11)
      (branch-var V
       (</>
        (/
         (define-proc 0 (<> (text "　　辺りの様子　　")))
         (set-reg 0 #t)
         (define-proc 1 (<> (text "　　　") (proc 14) (text "　　　")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　") (proc 14) (text "　　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　娘の事　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　　撮影の事　　") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　") (proc 14) (text "の事　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　シンディの事　") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　他の場所へ　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　セーブ　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "ゲームを終了する") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 0)
         (if (</>
              (//
               (? (!= S 255))
               (nop@)
               (if (</>
                    (//
                     (? (!= A 255))
                     (nop@)
                     (set-var A 255)
                     (mes-load? "mes¥save.mec" 4096))))
               (mes-load? 4096)
               (if (</>
                    (// (? (= S 254)) (nop@) (set-var P 1))
                    (// (nop@) (set-var F 5) (mes-load? 0))))))))))
      (if (</> (// (? (= S 255)) (nop@) (set-var P 0)))))
     (/
      (if (</> (// (? (= 26 #t)) (nop@) (set-var F 1) (mes-load? 4096))))
      (set-var F 6)
      (mes-load? 0)
      (text-frame 14 328 69 383)
      (seg-call)
      (branch-reg 23 (</> (/ (proc 18)) (/ (set-reg 23 #f))))
      (set-var P 0))))))
 (seg (? (= V 0) (= N 0))
      (if (</>
           (//
            (? (= 100 #f))
            (text "大物女優の部屋にしては質素な部屋なのか、実は上品にまとまっているだけなのか")
            (proc 15)
            (text "僕には判断しかねる。")
            (set-reg 100 #t))
           (//
            (? (= 101 #f))
            (text "目の前に著名な女優が、しかも挑発的な態度で横たわっていると言うのに、あまり興奮しないな。彼女には毒がありそうだ。")
            (set-reg 101 #t))
           (//
            (text "この部屋は")
            (proc 14)
            (text "の別宅なんだろうか。本当の家はビバリーヒルズか、あるいはマイアミあたりか")
            (proc 15)
            (set-reg 100 #f)
            (set-reg 101 #f)))))
 (seg (? (= V 0))
      (branch-reg 201
       (</>
        (/
         (proc 14)
         (text "は、僕の仕事の遅さに苛立っているようだ。今にも手にもったグラスを投げ付けられそうだぞ")
         (proc 15)
         (set-reg 201 #t))
        (/
         (proc 14)
         (text "の僕に対する評価は地に落ちたようだ。その表情からはあきらかに、失望の色を読み取る事が出来る。")))))
 (seg (? (= V 1))
      (branch-reg 202
       (</>
        (/
         (text-frame 8 308 71 323)
         (proc 14)
         (proc 19)
         (text "私はね、あなたとお喋りする時間なんてないのよ。" '60392)
         (proc 18)
         (text-frame 8 308 71 323)
         (proc 12)
         (proc 19)
         (text "すみません。" '60392)
         (proc 18)
         (text-frame 8 308 71 323)
         (proc 14)
         (proc 19)
         (text "ここへ訪ねて来る時には、依頼が進展した時だけにして欲しいわね。" '60392)
         (set-reg 202 #t))
        (/
         (text-frame 8 308 71 323)
         (proc 14)
         (proc 19)
         (text "わかったら、さっさと娘のところへ行ってよ。" '60392)))))
 (seg (? (= V 2) (= N 0))
      (if (</>
           (//
            (? (= 203 #f))
            (text-frame 8 308 71 323)
            (proc 14)
            (proc 19)
            (text "娘は見つかったんでしょう？" '60392)
            (proc 18)
            (text-frame 8 308 71 323)
            (proc 12)
            (proc 19)
            (text "はい。" '60392)
            (proc 18)
            (text-frame 8 308 71 323)
            (proc 14)
            (proc 19)
            (text "それならどうして会えないの？　おかしいじゃない。" '60392)
            (proc 18)
            (text-frame 8 308 71 323)
            (proc 12)
            (proc 19)
            (text "それが、彼女にも都合があって")
            (proc 15)
            (text-raw 60392)
            (proc 18)
            (text-frame 8 308 71 323)
            (proc 14)
            (proc 19)
            (text "彼女の都合？　私の都合はどう考えてるわけ？" '60392)
            (set-reg 203 #t))
           (//
            (? (= 204 #f))
            (text-frame 8 308 71 323)
            (proc 12)
            (proc 19)
            (proc 15)
            (text "なるべく早く約束を取り付けて来ます。" '60392)
            (proc 18)
            (text-frame 8 308 71 323)
            (proc 14)
            (proc 19)
            (text "なるべく早くじゃなくて、すぐにでしょう？　全く、能無しなんだから")
            (proc 15)
            (text-raw 60392)
            (set-reg 204 #t))
           (//
            (text-frame 8 308 71 323)
            (proc 14)
            (proc 19)
            (text "もうっ、一体いつまで待たせる気なのよ。" '60392)))))
 (seg (? (= V 2))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "撮影？　そんなこと今は関係ないでしょう。そんなことを気にかけるより娘の事をどうにかしてよ" '60392))
 (seg (? (= V 3) (= N 0))
      (branch-reg 205
       (</>
        (/
         (text "僕がシンディに約束を取りつける事が出来なかったせいで、かなり機嫌を損ねているようだ")
         (proc 15)
         (proc 18)
         (text "僕だって一生懸命やってるんだ、シンディの気持ちだってあるし")
         (proc 15)
         (text "もう少し気長に構えてくれないもんかな。")
         (set-reg 205 #t))
        (/
         (text "このままじゃ本当に無能者の烙印を押されそうだ。探偵は僕だけじゃないし、")
         (proc 14)
         (text "には高額な報酬を払う経済力がある。")))))
 (seg (? (= V 3))
      (branch-reg 206
       (</>
        (/
         (text "シンディにしてみれば、血がつながってるってだけで愛しくも懐かしくもない母親だからな")
         (proc 15)
         (proc 18)
         (text "いまさら会ってどうしろって言うんだ？　あの子を納得させるのは大仕事になりそうだなぁ。")
         (set-reg 206 #t))
        (/
         (text "とにかく、会って話をしなけりゃ始まらない。あまり自信は無いが")
         (proc 15)
         (text "努力だけはしてみよう。")))))
 (seg (? (= V 4))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "今度来るときは娘との話がついてなきゃダメよ。" '60392)
      (cmd:203 1 0)
      (exec-mem 12288 0 20 (bytes 235 186) 72 368 0 1021 2)
      (text-frame 8 308 69 383)
      (cmd:203 1 1)
      (mes-jump "b:¥mes¥3_map.mes"))
 (seg*
  (nop@)
  (text "※※※　バグです　※※※" 'br)
  (text "Ｖ＝")
  (exec-mem 35072 "DISP V")
  (text "　Ｎ＝")
  (exec-mem 35072 "DISP N")))