(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 35072 "@0='セントレジナスホテル'")
  (define-proc 12 (<> (text "ジェイク")))
  (define-proc 14 (<> (text "メリル")))
  (define-proc 15 (<> (text-raw 60393 60393 60393)))
  (branch-reg 22
   (</>
    (/
     (cmd:204 100 199)
     (if (</> (// (? (!= M 3)) (nop@) (sound ' 2))))
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b09.gpc")
     (image-mem 0)
     (if (</>
          (//
           (? (!= M 3))
           (nop@)
           (sound ' 0)
           (sound ' "uso¥ap_03.uso")
           (sound ' 1)
           (set-var M 3))))
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (delay 50)
     (image-file "gpc¥b10.gpc")
     (exec-mem 8192 "A 1")
     (text-frame 12 16 67 287)
     (text-reset 0)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (exec-mem 8192 "A 1")
     (image-mem 0)
     (image-file "gpc¥b10a.gpc")
     (image-mem 1)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (text-frame 8 308 71 323)
     (proc 14)
     (proc 19)
     (text "あら、まだ何か用なの？" '60392)
     (proc 18))
    (/
     (nop@)
     (sound ' 2)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b10.gpc")
     (image-mem 0)
     (image-file "gpc¥b10a.gpc")
     (image-mem 1)
     (sound ' 0)
     (sound ' "uso¥ap_03.uso")
     (sound ' 1)
     (set-var M 3)
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (cmd:204 24 26)
     (set-reg 22 #f)
     (set-var A 0))))
  (if (</> (// (? (!= A 255)) (nop@) (set-var A 0))))
  (set-var V 0)
  (set-var P 0)
  (set-var C 0)
  (repeat 9 (<> (exec-mem 35072 "A'[C]=0") (inc-var C 1)))
  (loop
   (branch-var P
    (</>
     (/
      (cmd:204 0 11)
      (define-proc 0 (<> (str " ") (text "　　見る　　") (str " ")))
      (set-reg 0 #t)
      (define-proc 1 (<> (str " ") (text "　　話す　　") (str " ")))
      (set-reg 1 #t)
      (define-proc 2 (<> (str " ") (text "　　聞く　　") (str " ")))
      (exec-mem 35072 "#2=#221")
      (define-proc 3 (<> (text "　　考える　　")))
      (exec-mem 35072 "#3=#221")
      (define-proc 4 (<> (str " ") (text "　移動する　") (str " ")))
      (exec-mem 35072 "#4=#221")
      (define-proc 5 (<> (str " ") (text "　システム　") (str " ")))
      (set-reg 5 #t)
      (set-var F 0)
      (mes-load? 0)
      (set-var P 1))
     (/
      (cmd:204 0 11)
      (branch-var V
       (</>
        (/
         (define-proc 0 (<> (text "　　辺りの様子　　")))
         (set-reg 0 #t)
         (define-proc 1 (<> (text "　　　") (proc 14) (text "　　　")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　") (proc 14) (text "　　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　娘の事　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　　撮影の事　　") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　") (proc 14) (text "の事　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　シンディの事　") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　他の場所へ　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　セーブ　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "ゲームを終了する") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 0)
         (if (</>
              (//
               (? (!= S 255))
               (nop@)
               (if (</>
                    (//
                     (? (!= A 255))
                     (nop@)
                     (set-var A 255)
                     (mes-load? "mes¥save.mec" 4096))))
               (mes-load? 4096)
               (if (</>
                    (// (? (= S 254)) (nop@) (set-var P 1))
                    (// (nop@) (set-var F 5) (mes-load? 0))))))))))
      (if (</> (// (? (= S 255)) (nop@) (set-var P 0)))))
     (/
      (if (</> (// (? (= 26 #t)) (nop@) (set-var F 1) (mes-load? 4096))))
      (set-var F 6)
      (mes-load? 0)
      (text-frame 14 328 69 383)
      (seg-call)
      (branch-reg 23 (</> (/ (proc 18)) (/ (set-reg 23 #f))))
      (set-var P 0))))))
 (seg (? (= V 0) (= N 0))
      (if (</>
           (//
            (? (= 100 #f))
            (text "大物女優の部屋にしては質素な部屋なのか、実は上品にまとまっているだけなのか")
            (proc 15)
            (text "僕には判断しかねる。")
            (set-reg 100 #t))
           (//
            (? (= 101 #f))
            (text "目の前に著名な女優が、しかも挑発的な態度で横たわっていると言うのに、あまり興奮しないな。彼女には毒がありそうだ。")
            (set-reg 101 #t))
           (//
            (text "この部屋は")
            (proc 14)
            (text "の別宅なんだろうか。本当の家はビバリーヒルズか、あるいはマイアミあたりか")
            (proc 15)
            (set-reg 100 #f)
            (set-reg 101 #f)))))
 (seg (? (= V 0))
      (branch-reg 220
       (</>
        (/
         (text "まるで、初めてのデートを明日に控えたローティーンの女の子のように、そわそわと落ち着きがない。")
         (set-reg 220 #t))
        (/
         (text "どうやら僕の働きに満足しているようだ。このテの女性を怒らせると後が怖いからな")
         (proc 15)))))
 (seg (? (= V 1))
      (branch-reg 221
       (</>
        (/
         (text-frame 8 308 71 323)
         (proc 14)
         (proc 19)
         (text "ねぇ、どんな服を着ていったらいいと思う？" '60392)
         (proc 18)
         (text-frame 8 308 71 323)
         (proc 12)
         (proc 19)
         (text "僕はセンスないですから、お役には立てませんよ。" '60392)
         (proc 18)
         (text-frame 8 308 71 323)
         (proc 14)
         (proc 19)
         (text "あら")
         (proc 15)
         (proc 15)
         (text "そうね、あなたにこんな事話しても仕方ないわね。" '60392)
         (set-reg 221 #t))
        (/
         (text-frame 8 308 71 323)
         (proc 14)
         (proc 19)
         (text "アカデミー賞を獲るより緊張しちゃうわ、どうしようかしら。もう、心臓がドキドキしちゃって")
         (proc 15)
         (text-raw 60392)))))
 (seg (? (= V 2) (= N 0))
      (branch-reg 222
       (</>
        (/
         (text-frame 8 308 71 323)
         (proc 14)
         (proc 19)
         (text "どうか彼女の機嫌を悪くするような事はしないで頂戴ね。" '60392)
         (proc 18)
         (text-frame 8 308 71 323)
         (proc 12)
         (proc 19)
         (text "大丈夫ですよ")
         (proc 15)
         (text "あなたと会う事は承知してるんだし、多忙って訳でもないですから。" '60392)
         (proc 18)
         (text-frame 8 308 71 323)
         (proc 14)
         (proc 19)
         (text "そう？　それじゃ、あなたにお任せするわ。" '60392)
         (set-reg 222 #t))
        (/
         (text-frame 8 308 71 323)
         (proc 14)
         (proc 19)
         (text "本当は今すぐにでも会いたいけど")
         (proc 15)
         (text "娘にも私にも、心の準備が必要だわ。" '60392)))))
 (seg (? (= V 2))
      (branch-reg 223
       (</>
        (/
         (text-frame 8 308 71 323)
         (proc 14)
         (proc 19)
         (text "これで落ち着いて撮影にも頑張れるわ。でも、かえって気もそぞろでミスしちゃうかしら？" '60392)
         (proc 18)
         (text-frame 8 308 71 323)
         (proc 12)
         (proc 19)
         (text "それは大変だ。気を付けて下さい。" '60392)
         (proc 18)
         (text-frame 8 308 71 323)
         (proc 14)
         (proc 19)
         (text "あらやだ、この私がミスるわけないでしょう。ほんの冗談よ、冗談。" '60392)
         (set-reg 223 #t))
        (/
         (text-frame 8 308 71 323)
         (proc 14)
         (proc 19)
         (text "そうね")
         (proc 15)
         (text "これ以上プライベートな事の為に仕事を犠牲にする訳にはいかないわ。" '60392)))))
 (seg (? (= V 3) (= N 0))
      (branch-reg 224
       (</>
        (/
         (text "娘と会う日取りが決まったってだけで、有頂天になってほしくないな。美術館で腐ったトマトをぶつけられなきゃいいが。")
         (set-reg 224 #t))
        (/
         (text "とにかく、出来るだけ")
         (proc 14)
         (text "の意向に沿えるようにしよう。彼女は大事なお客さんなんだから。")))))
 (seg (? (= V 3))
      (branch-reg 225
       (</>
        (/
         (text "何しろ暇を持て余してたからな、シンディに場所と日時を承知させるのは何の問題も無い。")
         (set-reg 225 #t))
        (/
         (text "シンディの気が変わらないうちに、ふたりを会わせてしまった方がいいな。")))))
 (seg (? (= V 4))
      (text "僕は")
      (proc 14)
      (text "の部屋を後にした。")
      (cmd:203 1 0)
      (exec-mem 12288 0 20 (bytes 235 186) 72 368 0 1021 2)
      (text-frame 8 308 69 383)
      (cmd:203 1 1)
      (mes-jump "b:¥mes¥3_map.mes"))
 (seg*
  (nop@)
  (text "※※※　バグです　※※※" 'br)
  (text "Ｖ＝")
  (exec-mem 35072 "DISP V")
  (text "　Ｎ＝")
  (exec-mem 35072 "DISP N")))