(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 35072 "@0='スナイプス探偵事務所'")
  (define-proc 12 (<> (text "ジェイク")))
  (define-proc 13 (<> (text "ユリコ")))
  (define-proc 14 (<> (text "事務所")))
  (define-proc 15 (<> (text-raw 60393 60393 60393)))
  (exec-mem 4096 "INIT")
  (exec-mem 4096 "MODE M8")
  (exec-mem 4096 "LOAD gpc¥i06.gpc,KEEP")
  (branch-reg 22
   (</>
    (/
     (cmd:204 100 199)
     (sound ' 2)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 8192 "A 1")
     (text-frame 0 0 79 399)
     (text-reset 0)
     (exec-mem 256 0 6 58 36 1 2 0 2560 2560 1 1)
     (image-file "b:¥gpc¥009.gpc")
     (image-mem 0 3 1 56)
     (exec-mem 8192 "A 0")
     (mes-load? "mes¥win_o.mec" 4096)
     (sound ' 0)
     (sound ' "uso¥ap_12.uso")
     (delay 100)
     (text-color 0 2 2)
     (cmd:203 1 1)
     (text-frame 14 328 69 383)
     (text "　　　　　　　　　　−　翌日　−")
     (cmd:209 1 2)
     (proc 18)
     (text "昨日は散々な目にあった")
     (proc 15)
     (text "朝から憂鬱な頭を抱え、それでも僕は")
     (proc 14)
     (text "へ出勤。")
     (proc 18)
     (text "メリルの依頼も終わったも同然の今、しばらくバカンスに行ったってよかった")
     (text-raw 60485 60484)
     (text "そんな事を考えていた。")
     (proc 18)
     (proc 14)
     (text "に着いてドアノブに手をかけると、鍵をかけたはずのドアが開いているのに気付いた。")
     (proc 18)
     (text-frame 8 308 71 323)
     (proc 12)
     (proc 19)
     (proc 15)
     (proc 15)
     (proc 15)
     (text-raw 60392)
     (proc 18)
     (text "僕はおそるおそるドアを開け、")
     (proc 14)
     (text "の中へ足を踏み入れた。")
     (proc 18)
     (sound ' 1)
     (set-var M 12)
     (mes-load? 4096)
     (text-frame 8 308 71 323)
     (proc 12)
     (proc 19)
     (text "な、なんだこれは")
     (proc 15)
     (text "！？" '60392)
     (proc 18)
     (proc 14)
     (text "は惨々たる状況だった。昨夜かあるいは今朝、誰かがここへ忍び込んで荒らして行ったに違いない。")
     (proc 18)
     (text "でも誰が？　いったい何のためにこんなことを")
     (proc 15)
     (text "！？")
     (proc 18)
     (text "とりあえず、部屋に誰もいないことを確認すると、僕は辺りを調べ始めた。")
     (proc 18))
    (/
     (nop@)
     (sound ' 2)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "b:¥gpc¥009.gpc")
     (image-mem 0)
     (sound ' 0)
     (sound ' "uso¥ap_12.uso")
     (sound ' 1)
     (set-var M 12)
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (cmd:204 24 26)
     (set-reg 22 #f)
     (set-var A 0))))
  (if (</> (// (? (!= A 255)) (nop@) (set-var A 0))))
  (set-var V 0)
  (set-var P 0)
  (set-var C 0)
  (repeat 9 (<> (exec-mem 35072 "A'[C]=0") (inc-var C 1)))
  (loop
   (branch-var P
    (</>
     (/
      (cmd:204 0 11)
      (define-proc 0 (<> (text "　　調べる　　")))
      (set-reg 0 #t)
      (define-proc 1 (<> (str " ") (text "　システム　") (str " ")))
      (set-reg 1 #t)
      (set-var F 0)
      (mes-load? 0)
      (set-var P 1))
     (/
      (cmd:204 0 11)
      (branch-var V
       (</>
        (/
         (define-proc 0 (<> (text "　　　　机　　　　")))
         (set-reg 0 #t)
         (define-proc 1 (<> (text "　　　　窓　　　　")))
         (set-reg 1 #t)
         (define-proc 2 (<> (text "　　　　床　　　　")))
         (set-reg 2 #t)
         (define-proc 3
          (<> (str " ") (text "　　　書類　　　") (str " ")))
         (set-reg 3 #t)
         (define-proc 4 (<> (text "　　　　壁　　　　")))
         (set-reg 4 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　セーブ　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "ゲームを終了する") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 0)
         (if (</>
              (//
               (? (!= S 255))
               (nop@)
               (if (</>
                    (//
                     (? (!= A 255))
                     (nop@)
                     (set-var A 255)
                     (mes-load? "mes¥save.mec" 4096))))
               (mes-load? 4096)
               (if (</>
                    (// (? (= S 254)) (nop@) (set-var P 1))
                    (// (nop@) (set-var F 5) (mes-load? 0))))))))))
      (if (</> (// (? (= S 255)) (nop@) (set-var P 0)))))
     (/
      (if (</> (// (? (= 26 #t)) (nop@) (set-var F 1) (mes-load? 4096))))
      (set-var F 6)
      (mes-load? 0)
      (text-frame 14 328 69 383)
      (seg-call)
      (branch-reg 23 (</> (/ (proc 18)) (/ (set-reg 23 #f))))
      (set-var P 0))))))
 (seg (? (= 160 #t))
      (text "一通り調べたが何をとられたのか、このカフスが犯人のものであるのか")
      (proc 15)
      (text "全部")
      (proc 13)
      (text "が来ない事にはわからないな。")
      (proc 18)
      (mes-load? "mes¥win_c.mec" 4096)
      (set-var A 1)
      (mes-load? 4096)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "おはようござ")
      (proc 15)
      (text "げげっ、ボス、どうしてこんなこと！？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "やあおはよう、待ってたんだよ。今日は朝から大掃除だ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "え、え")
      (text-raw 60485 60483 60484)
      (text "っ！？　そんなぁ")
      (proc 15)
      (proc 15)
      (proc 15)
      (text-raw 60392)
      (cmd:203 1 0)
      (exec-mem 12288 0 20 (bytes 235 186) 72 368 0 1021 2)
      (text-frame 8 308 69 383)
      (cmd:203 1 1)
      (cmd:204 100 499)
      (set-reg 794 #t)
      (set-var W 18)
      (exec-mem 4096 "EXIT")
      (mes-jump "b:¥mes¥308_18.mes"))
 (seg (? (= N 0) (= 159 #t))
      (text "他には何も見つからない。")
      (set-reg 160 #t))
 (seg (? (= N 0) (= 151 #t) (= 152 #t) (= 153 #t) (= 154 #t) (= 155 #t))
      (text "おや、机の下に何か落ちてる")
      (proc 15)
      (proc 18)
      (exec-mem 8192 "G 1 32 90 16 124,A 1,P 1 32 90")
      (exec-mem 4096 "COPY gpc¥i06.gpc,GPC")
      (image-mem 1 0 32 90)
      (exec-mem 8192 "C 1 32 90 16 124 0 32 90")
      (text "珍しいデザインのカフスだ。この雰囲気はどことなくガレの宝飾品を思わせるデザインだな。")
      (proc 18)
      (text "しかし、これは僕のものでも")
      (proc 13)
      (text "のものでもないとしたら、犯人のものでしかないわけだ。")
      (proc 18)
      (set-reg 23 #t)
      (exec-mem 8192 "P 1 32 90,F 1")
      (set-reg 159 #t))
 (seg (? (= N 0))
      (branch-reg 100
       (</>
        (/
         (text "僕の机は見事に１８０度転がされて引出しのいくつかは机から飛び出ている。")
         (proc 18)
         (text "しかし、机上の電話やパソコンがそのままなのを見ると、単なる泥棒の類ではないようだ。")
         (set-reg 100 #t))
        (/
         (text "とられて困るようなものは何も置いてなかったのが幸いしたが犯人の目的はなんだったんだろう？")
         (set-reg 151 #t)))))
 (seg (? (= N 1))
      (if (</>
           (//
            (? (= 101 #f))
            (text "ブラインドが折れ曲がってしまったが、肝心の窓ガラスは割られていない。不幸中の幸いと言うべきか。")
            (set-reg 101 #t))
           (//
            (? (= 152 #f))
            (text "窓ガラスが無事なのを見ると、犯人はドアから入って来たのに間違いないか。")
            (proc 18)
            (text "しかし、暴力的でもないこの犯人の目的がさっぱり見えない。")
            (set-reg 152 #t))
           (// (text "ブラインドは買い替えだな。")))))
 (seg (? (= N 2))
      (if (</>
           (//
            (? (= 102 #f))
            (text "床には書類やゴミ箱から飛び出たゴミが散乱している。掃除するのは一苦労だぞ。")
            (set-reg 102 #t))
           (//
            (? (= 153 #f))
            (text "う" '60517)
            (text "ん、何かめぼしいものは転がってないかなぁ")
            (proc 15)
            (text "この辺りで犯人の手がかりになるようなものが見つかるといいのに。")
            (set-reg 153 #t))
           (//
            (proc 13)
            (text "が来てから掃除しよう")
            (proc 15)
            (text "あ" '60517)
            (text "あ、朝から大変だ。")))))
 (seg (? (= N 3))
      (if (</>
           (//
            (? (= 103 #f))
            (text "大した書類などなくてよかった。ほとんどは請求書や")
            (proc 13)
            (text "がプリントアウトした探偵小説リストや犯罪データなどだ。")
            (set-reg 103 #t))
           (//
            (? (= 154 #f))
            (text "犯人はゴミ捨てにここへ来たわけじゃないんだし、むしゃくしゃした八つ当たりにここを荒らしたわけでもないんだよな。")
            (set-reg 154 #t))
           (//
            (text "たぶん、全部ゴミ箱に投げてもいい書類ばかりなんだろうな。")))))
 (seg*
  (if (</>
       (//
        (? (= 104 #f))
        (text "あ" '60517)
        (text "あ、お気に入りのポスターが剥がされてるなぁ。この犯人の狙いは一体なんだったんだ？")
        (set-reg 104 #t))
       (//
        (? (= 155 #f))
        (text "どう見ても単純な物取りとは思えない")
        (proc 15)
        (set-reg 155 #t))
       (//
        (text "こうして見るとなんて汚い壁なんだろう")
        (proc 15)
        (text "とほほ。")))))
 (seg*
  (nop@)
  (text "※※※　バグです　※※※" 'br)
  (text "Ｖ＝")
  (exec-mem 35072 "DISP V")
  (text "　Ｎ＝")
  (exec-mem 35072 "DISP N")))