(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 35072 "@0='スナイプス探偵事務所'")
  (define-proc 12 (<> (text "ジェイク")))
  (define-proc 13 (<> (text "ユリコ")))
  (define-proc 15 (<> (text-raw 60393 60393 60393)))
  (branch-reg 22
   (</>
    (/
     (cmd:204 100 199)
     (sound ' 2)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (exec-mem 4096 "COPY gpc¥b03.gpc,GPC")
     (image-mem 0)
     (sound ' 0)
     (sound ' "uso¥ap_04.uso")
     (sound ' 1)
     (set-var M 4)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:209 1 2)
     (branch-reg 760
      (</>
       (/
        (proc 15)
        (text "なんだ、")
        (proc 13)
        (text "はまだ戻ってないのか。まさかメリル達と一緒に話し込んでるんゃじないだろうな。")
        (proc 18)
        (text "　　　　　ＲＲＲＲＲＲＲＲＲＲ")
        (proc 15)
        (proc 15)
        (sound ' 0)
        (sound 'se 1)
        (proc 18)
        (text "あ、電話。")
        (proc 13)
        (text "かな？")
        (proc 18)
        (sound ' 0)
        (sound ' 1)
        (text-frame 8 308 71 323)
        (proc 12)
        (proc 19)
        (text "はい、こちら")
        (proc 15)
        (text-raw 60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (text "ファーバー")
        (proc 19)
        (proc 12)
        (text "か？　メリルがまだなんだが")
        (proc 15)
        (text-raw 60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 12)
        (proc 19)
        (text "今心当たりをあたっている最中なんです。" '60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (text "ファーバー")
        (proc 19)
        (text "クソっ、いったいどこに雲隠れしてるんだ？" '60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 12)
        (proc 19)
        (proc 15)
        (text '60331 "そんなこと僕に言われてもなぁ")
        (text-raw 60332 60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (text "ファーバー")
        (proc 19)
        (text "すまんがメリルの首に鎖をつけてでも引っ張って来て欲しいんだ。" '60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 12)
        (proc 19)
        (text "えっ、いや、それは")
        (proc 15)
        (text "出来ませんよ。" '60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (text "ファーバー")
        (proc 19)
        (text "今、ロケはグリニッジビレッジでやってるんだ。今日はメリルがいないと困るんだよ。" '60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 12)
        (proc 19)
        (text "僕も探して伝言はしてみますが")
        (proc 15)
        (text-raw 60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (text "ファーバー")
        (proc 19)
        (text "うん、よろしく頼むよ。それじゃ")
        (proc 15)
        (text-raw 60392)
        (proc 18)
        (text "　　　　　　　　　　ガチャ")
        (proc 15)
        (proc 18)
        (proc 15)
        (text "別にいいんだけど、僕はメリルのマネージャーじゃないんだよなぁ")
        (proc 15)
        (set-reg 760 #t))
       (/ (proc 15) (proc 13) (text "はまだ戻ってないのか。"))))
     (proc 18))
    (/
     (nop@)
     (sound ' 2)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (exec-mem 4096 "COPY gpc¥b03.gpc,GPC")
     (image-mem 0)
     (sound ' 0)
     (sound ' "uso¥ap_04.uso")
     (sound ' 1)
     (set-var M 4)
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (cmd:204 24 26)
     (set-reg 22 #f)
     (set-var A 0))))
  (if (</> (// (? (!= A 255)) (nop@) (set-var A 0))))
  (set-var V 0)
  (set-var P 0)
  (set-var C 0)
  (repeat 9 (<> (exec-mem 35072 "A'[C]=0") (inc-var C 1)))
  (loop
   (branch-var P
    (</>
     (/
      (cmd:204 0 11)
      (define-proc 0 (<> (str " ") (text "　　見る　　") (str " ")))
      (set-reg 0 #t)
      (define-proc 1 (<> (text "　　考える　　")))
      (set-reg 1 #t)
      (define-proc 2 (<> (str " ") (text "　移動する　") (str " ")))
      (set-reg 2 #t)
      (define-proc 3 (<> (str " ") (text "　システム　") (str " ")))
      (set-reg 3 #t)
      (set-var F 0)
      (mes-load? 0)
      (set-var P 1))
     (/
      (cmd:204 0 11)
      (branch-var V
       (</>
        (/
         (define-proc 0 (<> (text "　　辺りの様子　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　") (proc 13) (text "の事　　")))
         (set-reg 0 #t)
         (define-proc 1 (<> (text "　　エヴァの事　　")))
         (set-reg 1 #t)
         (define-proc 2 (<> (text "　　メリルの事　　")))
         (set-reg 2 #t)
         (define-proc 3 (<> (text "　クリスティの事　")))
         (set-reg 3 #t)
         (define-proc 4
          (<> (str " ") (text "　シンディの事　") (str " ")))
         (set-reg 4 #t)
         (define-proc 5 (<> (text "　　トニーの事　　")))
         (set-reg 5 #t)
         (define-proc 6 (<> (text "ファーバー監督の事")))
         (set-reg 6 #t)
         (define-proc 7
          (<> (str " ") (text "ジェニファーの事") (str " ")))
         (set-reg 7 #t)
         (define-proc 8
          (<> (str " ") (text "事務所荒らしの事") (str " ")))
         (set-reg 8 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　他の場所へ　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　セーブ　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "ゲームを終了する") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 0)
         (if (</>
              (//
               (? (!= S 255))
               (nop@)
               (if (</>
                    (//
                     (? (!= A 255))
                     (nop@)
                     (set-var A 255)
                     (mes-load? "mes¥save.mec" 4096))))
               (mes-load? 4096)
               (if (</>
                    (// (? (= S 254)) (nop@) (set-var P 1))
                    (// (nop@) (set-var F 5) (mes-load? 0))))))))))
      (if (</> (// (? (= S 255)) (nop@) (set-var P 0)))))
     (/
      (if (</>
           (//
            (? (= V 2))
            (nop@)
            (nop@)
            (set-reg 24 #f)
            (set-reg 25 #f)
            (set-reg 26 #f))
           (//
            (nop@)
            (if (</> (// (? (= 26 #t)) (nop@) (set-var F 1) (mes-load? 4096))))
            (set-var F 6)
            (mes-load? 0))))
      (text-frame 14 328 69 383)
      (seg-call)
      (branch-reg 23 (</> (/ (proc 18)) (/ (set-reg 23 #f))))
      (set-var P 0))))))
 (seg (? (= V 0))
      (if (</>
           (//
            (? (= 100 #f))
            (text "空き巣騒ぎから立ち直って、元の見慣れた風景に戻った。何も盗まれなかったのは幸いだったな")
            (proc 15)
            (set-reg 100 #t))
           (//
            (? (= 101 #f))
            (text "いつもの見慣れた部屋ではあるが、")
            (proc 13)
            (text "がいない事がこれ程こたえるとは")
            (proc 15)
            (text "一体どこに行ってしまったんだろう？")
            (set-reg 101 #t))
           (//
            (text "また空き巣に入られたらコトだな")
            (proc 15)
            (proc 13)
            (text "の忠告どおり、もっと鍵を付けておくか。")
            (set-reg 100 #f)
            (set-reg 101 #f)))))
 (seg (? (= V 1) (= N 0) (= 763 #t))
      (branch-reg 250
       (</>
        (/
         (text "メリルの話だと")
         (proc 13)
         (text "は美術館に行っていないことになる。それじゃ、")
         (proc 13)
         (text "は何処へ行ったんだ？")
         (set-reg 250 #t))
        (/
         (proc 13)
         (text "は誰かに連れ去られた")
         (proc 15)
         (text "とか？")))))
 (seg (? (= V 1) (= N 0) (= 762 #t))
      (branch-reg 251
       (</>
        (/
         (text "おばさんの話だと、美術館の入口にいたのはメリル一人だと言う事になる。")
         (proc 13)
         (text "は行かなかったのか？")
         (set-reg 251 #t))
        (/
         (text "場所を間違えてる可能性は考えられなくもないが")
         (proc 15)))))
 (seg (? (= V 1) (= N 0))
      (branch-reg 252
       (</>
        (/
         (text "たぶん、")
         (proc 13)
         (text "はメリルとシンディ母娘と共に行動しているのだろう。")
         (set-reg 252 #t))
        (/ (text "あの娘も野次馬だからなぁ") (proc 15)))))
 (seg (? (= V 1) (= N 1))
      (text "エヴァを殺した犯人のことも気がかりだが、今はそれどころじゃない。"))
 (seg (? (= V 1) (= N 2) (= 763 #t))
      (branch-reg 253
       (</>
        (/
         (text "メリルがからかわれたと誤解するのも無理はない。")
         (proc 13)
         (text "もシンディも現れなかったんだからな。")
         (set-reg 253 #t))
        (/
         (text "メリルの僕に対する評価は地に落ちたな。とにかく、シンディの居所を探してもう一度話をしよう。")))))
 (seg (? (= V 1) (= N 2) (= 762 #t))
      (branch-reg 254
       (</>
        (/
         (text "おばさんの話だと、メリルが一人で待ってたってことだったよな。")
         (proc 18)
         (text "とすると、メリルは確実に待ち合わせ場所に行った訳だ。")
         (set-reg 254 #t)
         (nop@))
        (/ (text "メリルはホテルに戻ってるのかな。")))))
 (seg (? (= V 1) (= N 2))
      (branch-reg 255
       (</>
        (/
         (text "ファーバー監督は僕をメリルのマネージャーか何かと勘違いしてるよな。")
         (set-reg 255 #t))
        (/
         (text "今、どこかで楽しく語らっているんだろうけど")
         (proc 15)
         (text "何処にいるんだ一体？")))))
 (seg (? (= V 1) (= N 3))
      (text "クリスティがどうしてるかは気になるが")
      (proc 15)
      (text "先に解決しなきゃならない問題がある。"))
 (seg (? (= V 1) (= N 4) (= 764 #t))
      (branch-reg 256
       (</>
        (/
         (text "シンディは昨日の夕方からいないのか")
         (proc 15)
         (text "グロリアが連れて行ったと考えるのが妥当なセンだな。")
         (set-reg 256 #t))
        (/
         (text "グロリアに会って、シンディを返してもらうしか")
         (proc 15)
         (text "いや、もしかすると自主的に仕事に戻ったのかな、シンディは。")))))
 (seg (? (= V 1) (= N 4) (= 762 #t))
      (branch-reg 257
       (</>
        (/
         (text "シンディは美術館にいかなかったのか")
         (proc 15)
         (text "シンディに限って場所を間違えるとも思えないし、会うのが嫌になったのかな。")
         (set-reg 257 #t))
        (/
         (text "シンディに事情を聞かないと")
         (proc 15)
         (text "このままじゃメリルが可哀想だ。")))))
 (seg (? (= V 1) (= N 4))
      (branch-reg 258
       (</>
        (/
         (text "シンディはメリルが母と知ってどんな反応をしただろうか？")
         (set-reg 258 #t))
        (/
         (text "今頃、仲良くやれてればいいけど")
         (proc 15)
         (text "ちょっと心配。")))))
 (seg (? (= V 1) (= N 5))
      (text "メスのことも気がかりだけど、そんな時間はないぞ。"))
 (seg (? (= V 1))
      (branch-reg 259
       (</>
        (/
         (text "ジェニファーはもうロケに行っただろうか？　いや、今はそんなことを考えてるほどヒマじゃないか。")
         (set-reg 259 #t))
        (/ (text "今はメリル達母娘のことが先決だ。")))))
 (seg (? (= V 2)) (mes-jump "b:¥mes¥3_map.mes"))
 (seg*
  (nop@)
  (text "※※※　バグです　※※※" 'br)
  (text "Ｖ＝")
  (exec-mem 35072 "DISP V")
  (text "　Ｎ＝")
  (exec-mem 35072 "DISP N")))