(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 35072 "@0='セントレジナスホテル'")
  (define-proc 12 (<> (text "ジェイク")))
  (define-proc 14 (<> (text "メリル")))
  (define-proc 15 (<> (text-raw 60393 60393 60393)))
  (branch-reg 22
   (</>
    (/
     (cmd:204 100 199)
     (if (</> (// (? (!= M 3)) (nop@) (sound ' 2))))
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b09.gpc")
     (image-mem 0)
     (if (</>
          (//
           (? (!= M 3))
           (nop@)
           (sound ' 0)
           (sound ' "uso¥ap_03.uso")
           (sound ' 1)
           (set-var M 3))))
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (if (</>
          (//
           (? (= 762 #f))
           (branch-reg 240
            (</>
             (/
              (text "母娘対面がどうなったのか、撮影のすっぽかしの原因は何なのか")
              (proc 15)
              (text "とにかく")
              (proc 14)
              (text "に会うのが先決と思った。")
              (proc 18)
              (text-frame 8 308 71 323)
              (text "フロント")
              (proc 19)
              (text "もし、お客様、")
              (proc 14)
              (text "様でしたら外出されてますが")
              (proc 15)
              (text-raw 60392)
              (proc 18)
              (text-frame 8 308 71 323)
              (proc 12)
              (proc 19)
              (text "まだ戻ってないのですか？" '60392)
              (proc 18)
              (text-frame 8 308 71 323)
              (text "フロント")
              (proc 19)
              (text "朝出かけられたきり、まだお戻りにはなっておりません。" '60392)
              (proc 18)
              (text-frame 8 308 71 323)
              (proc 12)
              (proc 19)
              (text "どうもありがとう。" '60392)
              (proc 18)
              (proc 14)
              (text "はまだ戻ってないのか")
              (proc 15)
              (set-reg 240 #t))
             (/
              (text-frame 8 308 71 323)
              (text "フロント")
              (proc 19)
              (proc 14)
              (text "様でしたらまだお戻りではありませんよ。" '60392)
              (proc 18)
              (text-frame 8 308 71 323)
              (proc 12)
              (proc 19)
              (text "そうか")
              (proc 15)
              (text "どうもありがとう。" '60392)
              (proc 18)
              (proc 14)
              (text "はどこで何をしているんだ？"))))
           (cmd:203 1 0)
           (exec-mem 12288 0 20 (bytes 235 186) 72 368 0 1021 2)
           (text-frame 8 308 69 383)
           (cmd:203 1 1)
           (mes-jump "b:¥mes¥3_map.mes"))))
     (delay 50)
     (image-file "gpc¥b10.gpc")
     (exec-mem 8192 "A 1")
     (text-frame 12 16 67 287)
     (text-reset 0)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (exec-mem 8192 "A 1")
     (image-mem 0)
     (image-file "gpc¥b10a.gpc")
     (image-mem 1)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (text-frame 14 328 69 383)
     (branch-reg 241
      (</>
       (/
        (proc 14)
        (text "の部屋を訪ねた。")
        (proc 18)
        (text "彼女は無言で僕を部屋へ招きいれると、また、いつものように長椅子に寝そべっていた。")
        (proc 18)
        (text "彼女は泣いているようだった")
        (proc 15)
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 12)
        (proc 19)
        (proc 15)
        (text "どうかしたんですか？" '60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 14)
        (proc 19)
        (text "ふん")
        (proc 15)
        (text "どうかしたか、じゃないわよ。" '60392)
        (set-reg 241 #t))
       (/
        (proc 14)
        (text "は泣き疲れてぐったりしているようだった。")
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 14)
        (proc 19)
        (text "あんたの顔なんて見たくないって言ったでしょう")
        (proc 15)
        (text-raw 60392))))
     (proc 18))
    (/
     (nop@)
     (sound ' 2)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b10.gpc")
     (image-mem 0)
     (image-file "gpc¥b10a.gpc")
     (image-mem 1)
     (sound ' 0)
     (sound ' "uso¥ap_03.uso")
     (sound ' 1)
     (set-var M 3)
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (cmd:204 24 26)
     (set-reg 22 #f)
     (set-var A 0))))
  (if (</> (// (? (!= A 255)) (nop@) (set-var A 0))))
  (set-var V 0)
  (set-var P 0)
  (set-var C 0)
  (repeat 9 (<> (exec-mem 35072 "A'[C]=0") (inc-var C 1)))
  (loop
   (branch-var P
    (</>
     (/
      (cmd:204 0 11)
      (define-proc 0 (<> (str " ") (text "　　見る　　") (str " ")))
      (set-reg 0 #t)
      (define-proc 1 (<> (str " ") (text "　　話す　　") (str " ")))
      (set-reg 1 #t)
      (define-proc 2 (<> (str " ") (text "　　聞く　　") (str " ")))
      (exec-mem 35072 "#2=#242")
      (define-proc 3 (<> (text "　　考える　　")))
      (exec-mem 35072 "#3=#242")
      (define-proc 4 (<> (str " ") (text "　移動する　") (str " ")))
      (exec-mem 35072 "#4=#763")
      (define-proc 5 (<> (str " ") (text "　システム　") (str " ")))
      (set-reg 5 #t)
      (set-var F 0)
      (mes-load? 0)
      (set-var P 1))
     (/
      (cmd:204 0 11)
      (branch-var V
       (</>
        (/
         (define-proc 0 (<> (text "　　辺りの様子　　")))
         (set-reg 0 #t)
         (define-proc 1 (<> (text "　　　") (proc 14) (text "　　　")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　") (proc 14) (text "　　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0
          (<> (str " ") (text "　母娘対面の事　") (str " ")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　　撮影の事　　") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　") (proc 14) (text "の事　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　シンディの事　") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　他の場所へ　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　セーブ　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "ゲームを終了する") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 0)
         (if (</>
              (//
               (? (!= S 255))
               (nop@)
               (if (</>
                    (//
                     (? (!= A 255))
                     (nop@)
                     (set-var A 255)
                     (mes-load? "mes¥save.mec" 4096))))
               (mes-load? 4096)
               (if (</>
                    (// (? (= S 254)) (nop@) (set-var P 1))
                    (// (nop@) (set-var F 5) (mes-load? 0))))))))))
      (if (</> (// (? (= S 255)) (nop@) (set-var P 0)))))
     (/
      (if (</> (// (? (= 26 #t)) (nop@) (set-var F 1) (mes-load? 4096))))
      (set-var F 6)
      (mes-load? 0)
      (text-frame 14 328 69 383)
      (seg-call)
      (if (</> (// (? (= 244 #t) (= 245 #t)) (nop@) (set-reg 763 #t))))
      (branch-reg 23 (</> (/ (proc 18)) (/ (set-reg 23 #f))))
      (set-var P 0))))))
 (seg (? (= V 0) (= N 0))
      (if (</>
           (//
            (? (= 100 #f))
            (text "室内は以前訪れた時と同じように、きちんと整っている。メリルが感情をぶち撒けた形跡はない。")
            (set-reg 100 #t))
           (//
            (? (= 101 #f))
            (text "辺りには、強いアルコールの匂いが漂っている。")
            (proc 14)
            (text "が飲んだのは、テーブル上の一本だけではないようだ。")
            (set-reg 101 #t))
           (//
            (text "マンハッタンを見下ろす窓の前を、横たわった")
            (proc 14)
            (text "が占領している。")
            (set-reg 100 #f)
            (set-reg 101 #f)))))
 (seg (? (= V 0))
      (if (</>
           (//
            (? (= 102 #f))
            (text "憤慨と侮蔑の入り混じった表情で僕を見ている。全身を支配しているのは、例えようのない虚脱感だろうか？")
            (set-reg 102 #t))
           (//
            (? (= 103 #f))
            (text "アルコールのせいで白い肌に赤みが入り、薄く汗が浮かんでいる。その上の顔さえ見なければ魅惑の")
            (proc 15)
            (text "って事になる。")
            (set-reg 103 #t))
           (//
            (text "これ以上、視線を合わせているのに耐えられそうもない。")
            (set-reg 102 #f)
            (set-reg 103 #f)))))
 (seg (? (= V 1) (= 242 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "あんたみたいな男の顔、二度と見たくなかったのに")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "何か気にさわることでも？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "とぼけないでよ！　あんたに騙されて私は大恥かいたわよ。" '60392)
      (set-reg 242 #t))
 (seg (? (= V 1) (= 763 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "金輪際私の目の前に現れないでちょうだい。" '60392))
 (seg (? (= V 1))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "二度と私の前に現れないで")
      (proc 15)
      (text "わかったわね。" '60392))
 (seg (? (= V 2) (= N 0) (= 243 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "来なかったわよ")
      (proc 15)
      (text "誰も来なかったわよ。休館日の今日、あの前に立ってたのは私一人だったわ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "ユリコも行かなかったんですか？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "誰も来なかったわよ。")
      (proc 15)
      (text "そう、誰もね。" '60392)
      (set-reg 243 #t))
 (seg (? (= V 2) (= N 0) (= 244 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "いそいそと出かけて行って馬鹿見たじゃないの。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "ユリコが娘さんと引き合わせるために行ったはずですけど。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "そんなもの来なかったって言ってるでしょう。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "私はね、１１時３０分からグツゲンハイム美術館の入口前に立ってたのよ、ずーっと")
      (proc 15)
      (text "結局１時まで待ちぼうけ。" '60392)
      (set-reg 244 #t))
 (seg (? (= V 2) (= N 0))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "あんた、私を担いだのね。ひどい")
      (proc 15)
      (text "最低の男ねっ！" '60392))
 (seg (? (= V 2) (= 245 #f))
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "ファーバー監督が、今日は必ずロケに来てくれるようにとおっしゃってました。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "そんなの知らないわよ。")
      (proc 15)
      (text "私、女優なんてもうやめた。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "そんな")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "私がロケに行かないのは、みんなあんたのせいなのよ。それをマーティンに説明しておいてよね。ふん")
      (proc 15)
      (text-raw 60392)
      (set-reg 245 #t))
 (seg (? (= V 2))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "こんな気持ちで撮影なんかやってられるわけないじゃない。" '60392))
 (seg (? (= V 3) (= N 0))
      (if (</>
           (//
            (? (= 244 #f))
            (text "まさかこんな結果になるなんて、誰が予想出来ただろう？　メリルの憤慨ももっともな事だ。"))
           (//
            (? (= 246 #f))
            (text "分刻みのスケジュールに追われる")
            (proc 14)
            (text "にとって、１時間半は途方もない価値を持っているのだろうな")
            (proc 15)
            (proc 18)
            (text "娘に会えると思えばこそ、癇癪を起こさずにじっと耐えていたのだろう。")
            (set-reg 246 #t))
           (//
            (text "これ以上、")
            (proc 14)
            (text "と二人っきりでいるのに耐えられない。彼女の怒りを鎮めるには、僕が消えるしかないだろう")
            (proc 15)))))
 (seg (? (= V 3))
      (if (</>
           (//
            (? (= 244 #f))
            (text "シンディは今日、待ち合わせをすっぽかしたと言うのか？")
            (proc 18)
            (text "あんなに楽しみにしてたのに、どうして")
            (proc 15))
           (//
            (? (= 247 #f))
            (text "シンディに何が起こったんだ？　ただの気まぐれで約束をすっぽかしたのか")
            (proc 15)
            (proc 15)
            (proc 18)
            (text "一緒にいるはずのユリコはどうしてしまったんだろう")
            (proc 15)
            (text "まさか、シンディの気紛れに付き合って、遊び惚けてるのか？")
            (set-reg 247 #t))
           (//
            (text "とにかく、シンディを探してみよう。今ならまだやり直しがきくだろう。")))))
 (seg (? (= V 4))
      (text "僕は")
      (proc 14)
      (text "に別れを告げると、部屋を後にした")
      (proc 15)
      (cmd:203 1 0)
      (exec-mem 12288 0 20 (bytes 235 186) 72 368 0 1021 2)
      (text-frame 8 308 69 383)
      (cmd:203 1 1)
      (mes-jump "b:¥mes¥3_map.mes"))
 (seg*
  (nop@)
  (text "※※※　バグです　※※※" 'br)
  (text "Ｖ＝")
  (exec-mem 35072 "DISP V")
  (text "　Ｎ＝")
  (exec-mem 35072 "DISP N")))