(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 35072 "@0='クラブＦＬＩＸ'")
  (define-proc 12 (<> (text "ジェイク")))
  (define-proc 13 (<> (text "シンディ")))
  (define-proc 14 (<> (text "ティム")))
  (define-proc 15 (<> (text-raw 60393 60393 60393)))
  (branch-reg 22
   (</>
    (/
     (cmd:204 100 199)
     (if (</> (// (? (!= M 3)) (nop@) (sound ' 2))))
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b20.gpc")
     (image-mem 0)
     (if (</>
          (//
           (? (!= M 3))
           (nop@)
           (sound ' 0)
           (sound ' "uso¥ap_03.uso")
           (sound ' 1)
           (set-var M 3))))
     (cmd:209 1 2)
     (delay 50)
     (image-file "gpc¥b21.gpc")
     (exec-mem 8192 "A 1")
     (text-frame 12 16 67 287)
     (text-reset 0)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (exec-mem 8192 "A 1")
     (image-mem 0)
     (image-file "b:¥gpc¥b21a.gpc")
     (image-mem 1)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (if (</>
          (//
           (? (= 702 #f))
           (text-frame 8 308 71 323)
           (proc 14)
           (proc 19)
           (text "あ")
           (proc 15)
           (text "なんだ探偵さんか。" '60392)
           (proc 18)
           (text-frame 8 308 71 323)
           (proc 12)
           (proc 19)
           (text "なんだはないだろう？" '60392)
           (proc 18)
           (text-frame 8 308 71 323)
           (proc 14)
           (proc 19)
           (text "いや、ゴメン、アリアナかと思ったから")
           (proc 15)
           (text-raw 60392)
           (proc 18)
           (text-frame 8 308 71 323)
           (proc 12)
           (proc 19)
           (proc 15)
           (text-raw 60393 60393)
           (text "まだ、何の連絡もないのか。" '60392)
           (proc 18)
           (text-frame 8 308 71 323)
           (proc 14)
           (proc 19)
           (text "うん")
           (proc 15)
           (text "いったいどこいっちゃったんだろうな、あいつ！" '60392)
           (set-reg 702 #t))
          (//
           (? (= 320 #f))
           (text-frame 8 308 71 323)
           (proc 14)
           (proc 19)
           (text "あ")
           (proc 15)
           (text "探偵さん！　アリアナは、アリアナは見つかった？" '60392)
           (proc 18)
           (text-frame 8 308 71 323)
           (proc 12)
           (proc 19)
           (text "まだ戻ってないのか")
           (proc 15)
           (text-raw 60392)
           (proc 18)
           (text-frame 8 308 71 323)
           (proc 14)
           (proc 19)
           (text "あれからずっとだよ。何の連絡もないんだ")
           (proc 15)
           (text-raw 60392)
           (set-reg 320 #t))
          (//
           (text-frame 8 308 71 323)
           (proc 14)
           (proc 19)
           (text "探偵さん、アリアナ見つかった")
           (proc 15)
           (text "？" '60392))))
     (proc 18))
    (/
     (nop@)
     (sound ' 2)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b21.gpc")
     (image-mem 0)
     (image-file "b:¥gpc¥b21a.gpc")
     (image-mem 1)
     (sound ' 0)
     (sound ' "uso¥ap_03.uso")
     (sound ' 1)
     (set-var M 3)
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (cmd:204 24 26)
     (set-reg 22 #f)
     (set-var A 0))))
  (if (</> (// (? (!= A 255)) (nop@) (set-var A 0))))
  (set-var V 0)
  (set-var P 0)
  (set-var C 0)
  (repeat 9 (<> (exec-mem 35072 "A'[C]=0") (inc-var C 1)))
  (loop
   (branch-var P
    (</>
     (/
      (cmd:204 0 11)
      (define-proc 0 (<> (str " ") (text "　　見る　　") (str " ")))
      (set-reg 0 #t)
      (define-proc 1 (<> (str " ") (text "　　話す　　") (str " ")))
      (set-reg 1 #t)
      (define-proc 2 (<> (str " ") (text "　　聞く　　") (str " ")))
      (exec-mem 35072 "#2=#321")
      (define-proc 3 (<> (text "　　考える　　")))
      (exec-mem 35072 "#3=#321")
      (define-proc 4 (<> (str " ") (text "　移動する　") (str " ")))
      (exec-mem 35072 "#4=#321")
      (define-proc 5 (<> (str " ") (text "　システム　") (str " ")))
      (set-reg 5 #t)
      (set-var F 0)
      (mes-load? 0)
      (set-var P 1))
     (/
      (cmd:204 0 11)
      (branch-var V
       (</>
        (/
         (define-proc 0 (<> (text "　　辺りの様子　　")))
         (set-reg 0 #t)
         (define-proc 1 (<> (text "　　　") (proc 14) (text "　　　")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　") (proc 14) (text "　　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0
          (<> (str " ") (text "　アリアナの事　") (str " ")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　グロリアの事　") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　") (proc 14) (text "の事　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　") (proc 13) (text "の事　") (str " ")))
         (set-reg 1 #t)
         (define-proc 2
          (<> (str " ") (text "　グロリアの事　") (str " ")))
         (set-reg 2 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　他の場所へ　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　セーブ　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "ゲームを終了する") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 0)
         (if (</>
              (//
               (? (!= S 255))
               (nop@)
               (if (</>
                    (//
                     (? (!= A 255))
                     (nop@)
                     (set-var A 255)
                     (mes-load? "mes¥save.mec" 4096))))
               (mes-load? 4096)
               (if (</>
                    (// (? (= S 254)) (nop@) (set-var P 1))
                    (// (nop@) (set-var F 5) (mes-load? 0))))))))))
      (if (</> (// (? (= S 255)) (nop@) (set-var P 0)))))
     (/
      (if (</> (// (? (= 26 #t)) (nop@) (set-var F 1) (mes-load? 4096))))
      (set-var F 6)
      (mes-load? 0)
      (text-frame 14 328 69 383)
      (seg-call)
      (branch-reg 23 (</> (/ (proc 18)) (/ (set-reg 23 #f))))
      (set-var P 0))))))
 (seg (? (= V 0) (= N 0))
      (if (</>
           (//
            (? (= 100 #f))
            (text "夜半のバカ騒ぎにそなえて、鋭気を養う束の間の休息中ってとこか。店の中は驚く程静かで、客の姿もない。")
            (set-reg 100 #t))
           (//
            (? (= 101 #f))
            (text "暇を持て余したバーテンが、僕と")
            (proc 14)
            (text "を見つめている。少しは")
            (proc 14)
            (text "の事を心配しているんだろうか？")
            (set-reg 101 #t))
           (//
            (text "どうやら")
            (proc 13)
            (text "はいないようだ。隠れようと思えば場所はいくらでもあるが、")
            (proc 14)
            (text "の態度は芝居ではなさそうだし")
            (proc 15)
            (set-reg 100 #f)
            (set-reg 101 #f)))))
 (seg (? (= V 0))
      (if (</>
           (//
            (? (= 102 #f))
            (text "元々線の細い少年だが、")
            (proc 13)
            (text "の件がよほどこたえているらしい。さらに痩せてしまったようだ")
            (proc 15)
            (set-reg 102 #t))
           (//
            (? (= 103 #f))
            (text "ソワソワして仕事もろくに手につかないような様子は、痛々しくて見ているこっちが参ってしまいそうだ。")
            (set-reg 103 #t))
           (//
            (text "ずっと寝ていないのだろうか、目の下に隈が出来ている。それでも仕事に出て来なければならないのは、生活のためだろう。")
            (set-reg 102 #f)
            (set-reg 103 #f)))))
 (seg (? (= V 1) (= 321 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "マンションに行った？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "マンションって、")
      (proc 13)
      (text "のかい？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "うん。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "ああ")
      (proc 15)
      (text "だけど、彼女は知らないみたいだったよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "そんなぁ、アリアナが連絡よこさないなんて、グロリアにとっ捕まった以外に考えられないよ。" '60392)
      (set-reg 321 #t))
 (seg (? (= V 1))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "アリアナのことが気になって、仕事もドジ踏んでばかりだよ。まいっちゃうなぁ")
      (proc 15)
      (text-raw 60392))
 (seg (? (= V 2) (= N 0) (= 322 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "アリアナから連絡はないよ。探偵さんの所へは連絡あった？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "いや、全くないんだ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "アリアナはオレのこと怒ってるんだ。だから")
      (proc 15)
      (text "でも、グロリアの所じゃなかったら、一体どこにいるんだろう？" '60392)
      (set-reg 322 #t))
 (seg (? (= V 2) (= N 0) (= 323 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "オレ、どうしよう")
      (proc 15)
      (text "アリアナにもしもの事があったらオレどうしたらいいんだ")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "悪い方に考えない方がいい。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "だけど、だけどいい事なんて考えられるわけないじゃないか。連絡もないなんて")
      (proc 15)
      (text "そんなの、そんなの")
      (proc 15)
      (text-raw 60392)
      (set-reg 323 #t))
 (seg (? (= V 2) (= N 0))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "どうしたらいい、オレどうすれば")
      (proc 15)
      (text-raw 60392))
 (seg (? (= V 2) (= 324 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "オレはあいつが嫌いだけど、アリアナはあいつの所にいてくれればいいなぁ、って思ってる。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "だが、訪ねたときは")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "やめてよ、聞きたくない")
      (proc 15)
      (text "絶対、絶対にあの女が隠してるんだ。そうでなきゃ、こんなこと説明つかないよ")
      (proc 15)
      (text-raw 60392)
      (set-reg 324 #t))
 (seg (? (= V 2) (= 325 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "オレ、あの女に会ってアリアナと会わせてもらえるように話して来ようかなって思ったんだ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (proc 14)
      (text "、だけどさ、少なくとも今はグロリアも")
      (proc 13)
      (text "の居場所を知らないんじゃないか？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "そんなのわかるもんか！　どっかのホテルに監禁してるのかもしれないんだ。そうだ、その手があるじゃないか。" '60392)
      (set-reg 325 #t))
 (seg (? (= V 2))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "きっとアリアナを監禁してるんだ。そうでなきゃ")
      (proc 15)
      (text "そうでなきゃオレ")
      (proc 15)
      (text-raw 60392))
 (seg (? (= V 3) (= N 0))
      (if (</>
           (//
            (? (= 326 #f))
            (proc 14)
            (text "はグロリアが")
            (proc 13)
            (text "を監禁していると思いたいみたいだ。確かにそれ以外は嫌な想像しか出来ないからな。")
            (set-reg 326 #t))
           (//
            (? (= 327 #f))
            (text "仮に")
            (proc 13)
            (text "が母親と再会して、自分の元を離れて母親の所へ行くとしたら、")
            (proc 14)
            (text "はどうする？")
            (proc 18)
            (proc 13)
            (text "みたいな可愛い子を手放したいなんて、誰が思う？　まさか")
            (proc 14)
            (text "が")
            (proc 13)
            (text "を誘拐したんじゃ")
            (proc 15)
            (text "まさかな。")
            (set-reg 327 #t))
           (//
            (proc 14)
            (text "は自分よりも")
            (proc 13)
            (text "の事を大切にしていた。")
            (proc 13)
            (text "がいなくなって一番こたえているのは")
            (proc 14)
            (text "だろう。")))))
 (seg (? (= V 3) (= N 1))
      (if (</>
           (//
            (? (= 328 #f))
            (proc 14)
            (text "大好きの")
            (proc 13)
            (text "が、何も言わず連絡もせず姿を隠す事など考えられない。")
            (set-reg 328 #t))
           (//
            (? (= 329 #f))
            (text "グロリアが引き留めていたとしても")
            (proc 15)
            (text "いや、その可能性はないに等しいのではないか。")
            (set-reg 329 #t))
           (//
            (text "僕の胸の中で、不吉な予感が沸き起こっていた。")))))
 (seg (? (= V 3))
      (if (</>
           (//
            (? (= 330 #f))
            (text "あの時、グロリアは")
            (proc 13)
            (text "の事を心から心配していた。あの姿にウソはないだろう")
            (proc 15)
            (set-reg 330 #t))
           (//
            (? (= 331 #f))
            (proc 15)
            (text "とすると、")
            (proc 13)
            (text "はやはりグロリアの所へいるわけではないのだろう。")
            (set-reg 331 #t))
           (//
            (proc 13)
            (text "はどこに消えたのか、グロリアに心当たりはないのだろうか？")))))
 (seg (? (= V 4))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "探偵さん、何かわかったら教えてくれよ。" '60392)
      (cmd:203 1 0)
      (exec-mem 12288 0 20 (bytes 235 186) 72 368 0 1021 2)
      (text-frame 8 308 69 383)
      (cmd:203 1 1)
      (mes-jump "b:¥mes¥4_map.mes"))
 (seg*
  (nop@)
  (text "※※※　バグです　※※※" 'br)
  (text "Ｖ＝")
  (exec-mem 35072 "DISP V")
  (text "　Ｎ＝")
  (exec-mem 35072 "DISP N")))