(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 35072 "@0='リー・ロワイヤルホテル'")
  (define-proc 12 (<> (text "ジェイク")))
  (define-proc 13 (<> (text "ジェニファー")))
  (define-proc 15 (<> (text-raw 60393 60393 60393)))
  (branch-reg 22
   (</>
    (/
     (if (</> (// (? (!= M 3)) (nop@) (sound ' 2))))
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "b:¥gpc¥b33.gpc")
     (image-mem 0)
     (if (</>
          (//
           (? (!= M 3))
           (nop@)
           (sound ' 0)
           (sound ' "uso¥ap_03.uso")
           (sound ' 1)
           (set-var M 3))))
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (delay 50)
     (image-file "b:¥gpc¥b34.gpc")
     (exec-mem 8192 "A 1")
     (text-frame 12 16 67 287)
     (text-reset 0)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (exec-mem 8192 "A 1")
     (image-mem 0)
     (image-file "b:¥gpc¥b34a.gpc")
     (image-mem 1)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (cmd:204 100 199)
     (branch-reg 220
      (</>
       (/
        (text-frame 8 308 71 323)
        (proc 12)
        (proc 19)
        (text "やあ")
        (proc 15)
        (text-raw 60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 13)
        (proc 19)
        (text "あら！　いらっしゃい。" '60392)
        (set-reg 220 #t))
       (/
        (text-frame 8 308 71 323)
        (proc 13)
        (proc 19)
        (text "また来てくれたのね、嬉しいわ。" '60392))))
     (proc 18))
    (/
     (nop@)
     (sound ' 2)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "b:¥gpc¥b34.gpc")
     (image-mem 0)
     (image-file "b:¥gpc¥b34a.gpc")
     (image-mem 1)
     (sound ' 0)
     (sound ' "uso¥ap_03.uso")
     (sound ' 1)
     (set-var M 3)
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (cmd:204 24 26)
     (set-reg 22 #f)
     (set-var A 0))))
  (if (</> (// (? (!= A 255)) (nop@) (set-var A 0))))
  (set-var V 0)
  (set-var P 0)
  (set-var C 0)
  (repeat 9 (<> (exec-mem 35072 "A'[C]=0") (inc-var C 1)))
  (loop
   (branch-var P
    (</>
     (/
      (cmd:204 0 11)
      (define-proc 0 (<> (str " ") (text "　　見る　　") (str " ")))
      (set-reg 0 #t)
      (define-proc 1 (<> (str " ") (text "　　話す　　") (str " ")))
      (set-reg 1 #t)
      (define-proc 2 (<> (str " ") (text "　　聞く　　") (str " ")))
      (exec-mem 35072 "#2=#221")
      (define-proc 3 (<> (text "　　考える　　")))
      (exec-mem 35072 "#3=#221")
      (define-proc 4 (<> (str " ") (text "　移動する　") (str " ")))
      (exec-mem 35072 "#4=#221")
      (define-proc 5 (<> (str " ") (text "　システム　") (str " ")))
      (set-reg 5 #t)
      (set-var F 0)
      (mes-load? 0)
      (set-var P 1))
     (/
      (cmd:204 0 11)
      (branch-var V
       (</>
        (/
         (define-proc 0 (<> (text "　　辺りの様子　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　") (proc 13) (text "　") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0
          (<> (str " ") (text "　") (proc 13) (text "　") (str " ")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0
          (<> (str " ") (text "　　仕事の事　　") (str " ")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　シンディの事　") (str " ")))
         (set-reg 1 #t)
         (define-proc 2 (<> (text "　　ジニーの事　　")))
         (set-reg 2 #t)
         (define-proc 3 (<> (text "　　トニーの事　　")))
         (set-reg 3 #t)
         (define-proc 4 (<> (text "ファーバー監督の事")))
         (exec-mem 35072 "#4=#701")
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (str " ") (proc 13) (text "の事") (str " ")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　シンディの事　") (str " ")))
         (set-reg 1 #t)
         (define-proc 2 (<> (text "　　ジニーの事　　")))
         (set-reg 2 #t)
         (define-proc 3 (<> (text "　　トニーの事　　")))
         (set-reg 3 #t)
         (define-proc 4 (<> (text "ファーバー監督の事")))
         (exec-mem 35072 "#4=#701")
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　他の場所へ　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　セーブ　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "ゲームを終了する") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 0)
         (if (</>
              (//
               (? (!= S 255))
               (nop@)
               (if (</>
                    (//
                     (? (!= A 255))
                     (nop@)
                     (set-var A 255)
                     (mes-load? "mes¥save.mec" 4096))))
               (mes-load? 4096)
               (if (</>
                    (// (? (= S 254)) (nop@) (set-var P 1))
                    (// (nop@) (set-var F 5) (mes-load? 0))))))))))
      (if (</> (// (? (= S 255)) (nop@) (set-var P 0)))))
     (/
      (if (</>
           (//
            (? (= V 4))
            (nop@)
            (nop@)
            (set-reg 24 #f)
            (set-reg 25 #f)
            (set-reg 26 #f))
           (//
            (nop@)
            (if (</> (// (? (= 26 #t)) (nop@) (set-var F 1) (mes-load? 4096))))
            (set-var F 6)
            (mes-load? 0))))
      (text-frame 14 328 69 383)
      (seg-call)
      (branch-reg 23 (</> (/ (proc 18)) (/ (set-reg 23 #f))))
      (set-var P 0))))))
 (seg (? (= V 0) (= N 0))
      (if (</>
           (//
            (? (= 100 #f))
            (text "味気ないホテルの部屋だ。そこにある家具や調度のどれを取っても、誰かの嗜好や想いを感じる事は出来ない。")
            (set-reg 100 #t))
           (//
            (? (= 101 #f))
            (text "マンハッタンのほぼ中央という立地の良さは、何にも代えられない価値を持っている。ばか高い宿泊料も納得出来るな。")
            (set-reg 101 #t))
           (//
            (text "もう長い期間をこの部屋で過ごしているはずなのに、ジェニファーの私物と言える物はほとんど無い。")
            (set-reg 100 #f)
            (set-reg 101 #f)))))
 (seg (? (= V 0))
      (if (</>
           (//
            (? (= 102 #f))
            (text "普段と何ら変わらない、わずかな笑みを浮かべた美しい顔を僕に向けている。")
            (set-reg 102 #t))
           (//
            (? (= 103 #f))
            (text "整った顔立ちと独特のそっけない立ち居振る舞いのせいで、他人からはかなり酷い事も言われている。")
            (set-reg 103 #t))
           (//
            (text "今日はあまり機嫌がよくないのだろうか、どことなく覇気が感じられないような気がする。")
            (set-reg 102 #f)
            (set-reg 103 #f)))))
 (seg (? (= V 1) (= 221 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "あなたに会えると元気になるわ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "まるで、今まで元気じゃなかったような言いぐさだね。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "うん")
      (proc 15)
      (text "もうすぐ、この部屋を引き払わなきゃいけなくなるの。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text-raw 60393 60393)
      (text "まさか、予算が足りなくてランク下のホテルに移ってくれ")
      (text-raw 60485 60484)
      (text "なんていわれたわけじゃないよね？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "まさかぁ")
      (proc 15)
      (text "そんなことじゃないわよ。" '60392)
      (set-reg 221 #t))
 (seg (? (= V 1) (= 701 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "あなたに会えて嬉しい。あなたに会った日はラッキーな日と決めてるの。うふふ")
      (proc 15)
      (text-raw 60392))
 (seg (? (= V 1))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "最近暗い話題が多くて嫌だわ。なにかこう明るくなる事とかないのかしら")
      (proc 15)
      (text-raw 60392))
 (seg (? (= V 2) (= N 0) (= 222 #f))
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "撮影はどう、順調に進んでる？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "う" '60517)
      (text "ん、それがね")
      (proc 15)
      (text "もう、どうしようかなって感じよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "なんだい、それ？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "うん")
      (proc 15)
      (text "私、どうしたらいいかしら？" '60392)
      (set-reg 222 #t))
 (seg (? (= V 2) (= N 0) (= 701 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "実はね、ホテル引き払うって言うのはね、撮影が中止になったからなの。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "撮影中止だって！？　それじゃ今回の映画は")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "無期延期とは言ってるけど、そのままお蔵入りしそうよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (proc 15)
      (text "それは残念だね。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "ええ。だけど")
      (proc 15)
      (text "出演者は揃わない撮影は進まない、と色々問題あったもの。当然の結果かもしれないわ。" '60392)
      (set-reg 701 #t))
 (seg (? (= V 2) (= N 0))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "時間に余裕が出来ちゃったからバカンスでも行こうかしら？" '60392))
 (seg (? (= V 2) (= N 1) (= 223 #f))
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "そういえば、シンディと仲いいんだよね。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "ええ、まあ")
      (proc 15)
      (text "あ、そう言えば、彼女病気治ったのかしら？早く元気になってくれればいいけど")
      (proc 15)
      (text-raw 60392)
      (set-reg 223 #t))
 (seg (? (= V 2) (= N 1) (= 224 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "本当は彼女に会いたいんだけど、グロリアの壁は厚いの。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "そうか、キミは何もまだ")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "何")
      (proc 15)
      (text "何かあったの？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "いやなんでもない。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (proc 15)
      (text "？" '60392)
      (set-reg 224 #t))
 (seg (? (= V 2) (= N 1))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "若いけどしっかりした子ね。プライドばかり高いどっかの誰かよりよっぽど好きだわ。" '60392))
 (seg (? (= V 2) (= N 2) (= 225 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "彼女とはずっと顔を合わせてないのよ。彼女に何があったか知らないけど私は何もかかわってないわ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "トニーはなんだかキミを")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "トニーが言う事を真に受けたりしないで。それとも、私よりもトニー・フォードの方が信用できるって言うの？" '60392)
      (set-reg 225 #t))
 (seg (? (= V 2) (= N 2))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "お願い、もうそんな話はしないで。あなたまで私を悪く言うのね")
      (proc 15)
      (text "とても辛いわ。" '60392))
 (seg (? (= V 2) (= N 3) (= 226 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "私と彼が仲悪いの知ってるでしょう？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "あまりいいとは言えないよね。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "だったらそんな人の話")
      (proc 15)
      (text-raw 60392)
      (set-reg 226 #t))
 (seg (? (= V 2) (= N 3))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "もうやめて")
      (proc 15)
      (text "そんな男の話。" '60392))
 (seg (? (= V 2) (= 227 #f))
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "監督が決定した事なんだよね。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "ええ、そうよ。出演者がちっとも揃わないでしょう？　本当にちっとも進まなくて監督も参ってらっしゃるわ。" '60392)
      (set-reg 227 #t))
 (seg (? (= V 2) (= 228 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "私も残念よ、夢のファーバー監督作品に出演する機会をひとつ失ったんですもの。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "でもこれが最後じゃないんだから")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "それはわかってるけど")
      (proc 15)
      (text "初めにつまづくと意外とうまくいかなくなってしまうから。" '60392)
      (set-reg 228 #t))
 (seg (? (= V 2))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "私、ファーバー監督とは縁が無いのかもね。" '60392))
 (seg (? (= V 3) (= N 0))
      (if (</>
           (//
            (? (= 229 #f))
            (text "約束もなく突然現れた僕の顔を見ても、全然嫌そうじゃない。")
            (proc 13)
            (text "にとって、僕はどんな存在なんだろう。")
            (set-reg 229 #t))
           (//
            (? (= 230 #f))
            (text "いい加減、ニューヨークにも嫌気がさした頃だろう。特にこうも嫌な事続きじゃ無理もない。街を離れるのもいいかも")
            (proc 15)
            (set-reg 230 #t))
           (//
            (proc 13)
            (text "は何処かへ行ってしまうのか")
            (proc 15)
            (text "また彼女と会える事もあるんだろうか。")))))
 (seg (? (= V 3) (= N 1))
      (if (</>
           (//
            (? (= 231 #f))
            (text "シンディは今どこで何をしているのだろう？　生きていればいいのだけれど")
            (proc 15)
            (set-reg 231 #t))
           (//
            (? (= 232 #f))
            (text "まだメリルとの対面も果たしていない。まさか、メリルが母だと知って失踪した？　")
            (text-raw 60393 60393)
            (text "いや、そんなことは考えられない。")
            (set-reg 232 #t))
           (//
            (text "シンディともっとも近しい間柄だったのは、ティムかグロリアだ。どちらかがシンディを拉致してるって事もあるだろうか？")))))
 (seg (? (= V 3) (= N 2))
      (if (</>
           (//
            (? (= 233 #f))
            (proc 13)
            (text "とジニーが仲が悪かったと言う話は、本当なのだろうか。だとすると、")
            (proc 13)
            (text "にも動機が")
            (proc 15)
            (set-reg 233 #t))
           (//
            (? (= 234 #f))
            (text "初心に帰るという意味でも、ジニーの事件をもう一度考えてみるべきかもしれない。")
            (set-reg 234 #t))
           (//
            (text "どうもジニーという女性の、生前の姿が浮かんでこない。僕が訊ねた全員が嘘をついているとしか思えないんだが")
            (proc 15)))))
 (seg (? (= V 3) (= N 3))
      (if (</>
           (//
            (? (= 730 #f))
            (text "今までを考えるとトニーが怪しいのは事実。しかし、ジニーの行方不明に関係しているのかは謎だ。"))
           (//
            (? (= 235 #f))
            (text "トニーは嘘つきで信用ならない奴だ。人の事務所は荒らさせるし")
            (proc 13)
            (text "には恨みを抱いているし")
            (proc 15)
            (text "本当に困った奴だ。")
            (set-reg 235 #t))
           (//
            (? (= 236 #f))
            (text "マイルスを使って、僕の事務所を家捜しさせたのはトニーだったのか。迷惑料ぐらい請求してもよかったかもしれない。")
            (set-reg 236 #t))
           (//
            (text "確かにトニーはまっとうな人間ではないが、連続殺人の犯人ではなさそうだ。彼にはそんな事をする度胸は無いだろう。")))))
 (seg (? (= V 3))
      (if (</>
           (//
            (? (= 237 #f))
            (text "残念な事をしたな")
            (proc 15)
            (text "このせいで監督の経歴に傷がついたりしなきゃいいけど。")
            (set-reg 237 #t))
           (//
            (? (= 238 #f))
            (text "ファーバー監督の事だ、これくらいはちょっとしたつまづき程度でまたすぐに次の映画を撮りはじめるだろう。")
            (set-reg 238 #t))
           (//
            (text "監督の事は心配いらないだろう。黙っていてもひとりで立ち直る事が出来るはずだ。")))))
 (seg (? (= V 4)) (mes-jump "b:¥mes¥4_map.mes"))
 (seg*
  (nop@)
  (text "※※※　バグです　※※※" 'br)
  (text "Ｖ＝")
  (exec-mem 35072 "DISP V")
  (text "　Ｎ＝")
  (exec-mem 35072 "DISP N")))