(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 35072 "@0='ＳＯ　ＷＨＡＴ！'")
  (define-proc 12 (<> (text "ジェイク")))
  (define-proc 13 (<> (text "ジェニファー")))
  (define-proc 15 (<> (text-raw 60393 60393 60393)))
  (branch-reg 22
   (</>
    (/
     (if (</> (// (? (!= M 3)) (nop@) (sound ' 2))))
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "b:¥gpc¥b35.gpc")
     (image-mem 0)
     (if (</>
          (//
           (? (!= M 3))
           (nop@)
           (sound ' 0)
           (sound ' "uso¥ap_03.uso")
           (sound ' 1)
           (set-var M 3))))
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (branch-reg 704
      (</>
       (/
        (branch-reg 240
         (</>
          (/
           (text-frame 8 308 71 323)
           (proc 12)
           (proc 19)
           (text "ここが" '60522)
           (text "ＳＯ　ＷＨＡＴ？" '60523)
           (text "か")
           (proc 15)
           (text "入りにくい感じのする店だな。" '60392)
           (proc 18)
           (text "深呼吸して中に入るつもりでドアに手をかけた。")
           (proc 15)
           (text "が、まだ店はあいてなかった。")
           (proc 18)
           (text "この時間から開いてるわけもないか")
           (proc 15)
           (set-reg 240 #t))
          (/ (text "まだ開店前か") (proc 15))))
        (cmd:203 1 0)
        (exec-mem 12288 0 20 (bytes 235 186) 72 368 0 1021 2)
        (text-frame 8 308 69 383)
        (cmd:203 1 1)
        (mes-jump "b:¥mes¥4_map.mes"))
       (/
        (branch-reg 241
         (</>
          (/
           (text "ここが" '60522)
           (text "ＳＯ　ＷＨＡＴ？" '60523)
           (text "だ。")
           (proc 18)
           (text "初めての店でゲイクラブ")
           (proc 15)
           (text "なんとなく緊張してしまうな。")
           (proc 18)
           (text "僕は、大きく深呼吸をして店の中へと入っていった。")
           (set-reg 241 #t))
          (/
           (text '60522 "ＳＯ　ＷＨＡＴ？" '60523)
           (text "へやって来た。")))))))
     (proc 18)
     (if (</> (// (? (!= M 8)) (nop@) (sound ' 2))))
     (image-file "b:¥gpc¥b36.gpc")
     (exec-mem 8192 "A 1")
     (text-frame 12 16 67 287)
     (text-reset 0)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (exec-mem 8192 "A 1")
     (image-mem 0)
     (set-reg 706 #t)
     (if (</>
          (//
           (? (= 700 #t) (= 701 #t) (= 705 #t))
           (nop@)
           (image-file "b:¥gpc¥b36a.gpc")
           (image-mem 1)
           (set-reg 242 #t))))
     (exec-mem 8192 "A 0")
     (if (</>
          (//
           (? (!= M 8))
           (nop@)
           (sound ' 0)
           (sound ' "uso¥ap_08.uso")
           (sound ' 1)
           (set-var M 8))))
     (exec-mem 16384 12 16 67 287 3 1)
     (cmd:204 100 199)
     (text-frame 14 328 69 383)
     (if (</>
          (//
           (? (= 242 #t))
           (nop@)
           (text-frame 8 308 71 323)
           (text "少年")
           (proc 19)
           (text "ハイ、一人なの？" '60392)
           (proc 18)
           (text "僕の目の前に、美しい少年が現れた。")
           (proc 18)
           (text "彼はその透き通った眼で、じっと僕を見ている。"))
          (//
           (nop@)
           (text "暗い店内には甘い香りと汗の香りが充満していた。"))))
     (proc 18))
    (/
     (nop@)
     (sound ' 2)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "b:¥gpc¥b36.gpc")
     (image-mem 0)
     (if (</>
          (//
           (? (= 242 #t))
           (nop@)
           (image-file "b:¥gpc¥b36a.gpc")
           (image-mem 1))))
     (sound ' 0)
     (sound ' "uso¥ap_08.uso")
     (sound ' 1)
     (set-var M 8)
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (cmd:204 24 26)
     (set-reg 22 #f)
     (set-var A 0))))
  (if (</> (// (? (!= A 255)) (nop@) (set-var A 0))))
  (set-var V 0)
  (set-var P 0)
  (set-var C 0)
  (repeat 9 (<> (exec-mem 35072 "A'[C]=0") (inc-var C 1)))
  (loop
   (branch-var P
    (</>
     (/
      (cmd:204 0 11)
      (define-proc 0 (<> (str " ") (text "　　見る　　") (str " ")))
      (set-reg 0 #t)
      (define-proc 1 (<> (str " ") (text "　　話す　　") (str " ")))
      (exec-mem 35072 "#1=#242")
      (define-proc 2 (<> (str " ") (text "　　聞く　　") (str " ")))
      (exec-mem 35072 "#2=#245")
      (define-proc 3 (<> (text "　　考える　　")))
      (exec-mem 35072 "#3=#242")
      (define-proc 4 (<> (str " ") (text "　移動する　") (str " ")))
      (exec-mem 35072 "#4=(#242==0)")
      (define-proc 5 (<> (str " ") (text "　システム　") (str " ")))
      (set-reg 5 #t)
      (set-var F 0)
      (mes-load? 0)
      (set-var P 1))
     (/
      (cmd:204 0 11)
      (branch-var V
       (</>
        (/
         (define-proc 0 (<> (text "　　辺りの様子　　")))
         (set-reg 0 #t)
         (branch-reg 243
          (</>
           (/
            (define-proc 1
             (<> (str " ") (text "　　　少年　　　") (str " "))))
           (/
            (define-proc 1
             (<> (str " ") (text "　　アンジュ　　") (str " "))))))
         (exec-mem 35072 "#1=#242")
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (branch-reg 243
          (</>
           (/
            (define-proc 0
             (<> (str " ") (text "　　　少年　　　") (str " "))))
           (/
            (define-proc 0
             (<> (str " ") (text "　　アンジュ　　") (str " "))))))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　トニーの事　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　トニーの事　　")))
         (exec-mem 35072 "#0=#244")
         (branch-reg 243
          (</>
           (/
            (define-proc 1
             (<> (str " ") (text "　　少年の事　　") (str " "))))
           (/
            (define-proc 1
             (<> (str " ") (text "　アンジュの事　") (str " "))))))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　他の場所へ　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　セーブ　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "ゲームを終了する") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 0)
         (if (</>
              (//
               (? (!= S 255))
               (nop@)
               (if (</>
                    (//
                     (? (!= A 255))
                     (nop@)
                     (set-var A 255)
                     (mes-load? "mes¥save.mec" 4096))))
               (mes-load? 4096)
               (if (</>
                    (// (? (= S 254)) (nop@) (set-var P 1))
                    (// (nop@) (set-var F 5) (mes-load? 0))))))))))
      (if (</> (// (? (= S 255)) (nop@) (set-var P 0)))))
     (/
      (if (</> (// (? (= 26 #t)) (nop@) (set-var F 1) (mes-load? 4096))))
      (set-var F 6)
      (mes-load? 0)
      (text-frame 14 328 69 383)
      (seg-call)
      (branch-reg 23 (</> (/ (proc 18)) (/ (set-reg 23 #f))))
      (set-var P 0))))))
 (seg (? (>= V 1) (<= V 2) (= 249 #t) (= 250 #t))
      (text-frame 8 308 71 323)
      (text "アンジュ")
      (proc 19)
      (text "ねえ、今夜は朝まで付き合ってくれるでしょう？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "えっ")
      (proc 15)
      (text "！？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (text "アンジュ")
      (proc 19)
      (text "それとも、僕から話を聞くだけきいてあとはサヨナラなんて冷たいこと言うわけ？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "アンジュ")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (text "アンジュ")
      (proc 19)
      (text "お願い、ね？　今夜は朝まで一緒に")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text "僕は、アンジュの悲しげな瞳に心揺らぎ、いつしか首を縦にふっていたのだった")
      (proc 15)
      (cmd:203 1 0)
      (exec-mem 12288 0 20 (bytes 235 186) 72 368 0 1021 2)
      (text-frame 8 308 69 383)
      (cmd:203 1 1)
      (set-var W 18)
      (cmd:204 100 499)
      (set-reg 792 #t)
      (mes-jump "b:¥mes¥401.mes"))
 (seg (? (= V 0) (= N 0))
      (if (</>
           (//
            (? (= 100 #f))
            (text "店内は甘い香りが立ちこめていて、頭がクラクラしそうだ。")
            (set-reg 100 #t))
           (//
            (? (= 101 #f))
            (text "こうして立っているだけでおしりや股間を撫でられてしまう。")
            (proc 18)
            (text "そういう場所だから当然なのかもしれないが、ハッキリ言っていい気はしない。")
            (set-reg 101 #t))
           (//
            (text "暗く甘い淫靡な世界の縮小がこの狭いホールに充満している。")
            (set-reg 100 #f)
            (set-reg 101 #f)))))
 (seg (? (= V 0))
      (if (</>
           (//
            (? (= 102 #f))
            (text "目の前に立つ人物は、透き通るような肌の中性的なクールビューティだ。")
            (set-reg 102 #t))
           (//
            (? (= 103 #f))
            (text "全てを見通すかのような美しい瞳で僕を見つめている。")
            (set-reg 103 #t))
           (//
            (text "これが本当に少年なのかと疑ってしまう")
            (proc 15)
            (set-reg 102 #f)
            (set-reg 103 #f)))))
 (seg (? (= V 1) (= 243 #f))
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "さっきから僕を見てるね。何か用でもあるの？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (text "少年")
      (proc 19)
      (text "はん、自意識過剰")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "そうなのかなぁ")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (text "少年")
      (proc 19)
      (text "あれ、ヤケに素直ね。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (text "少年")
      (proc 19)
      (text "ねえ、名前")
      (proc 15)
      (text "名前は？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "普通は声をかけた方から名乗るのが常識じゃない？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (text "少年")
      (proc 19)
      (text "常識にはまるのは好きじゃないんだけど")
      (proc 15)
      (text "ぼくはアンジュって言うの。よろしくね。" '60392)
      (set-reg 243 #t))
 (seg (? (= V 1) (= 244 #f))
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "キミがアンジュなんだ")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (text "アンジュ")
      (proc 19)
      (text "なにそれ？")
      (proc 15)
      (text "普通さ、人の名前聞いたら名乗りかえすんでしょ。なのにさ")
      (text-raw 60393 60393)
      (text "なんか、失礼じゃない、そういうの？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "ごめん、僕は")
      (proc 12)
      (text "って言うんだ。よろしくね。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (text "アンジュ")
      (proc 19)
      (proc 12)
      (proc 15)
      (text "よかった、これで今夜は寂しくないね。" '60392)
      (set-reg 244 #t))
 (seg (? (= V 1) (= 252 #f))
      (text-frame 8 308 71 323)
      (text "アンジュ")
      (proc 19)
      (text "僕と朝まで一緒にいて")
      (proc 15)
      (text "ね。" '60392))
 (seg (? (= V 1) (= 245 #f))
      (text-frame 8 308 71 323)
      (text "アンジュ")
      (proc 19)
      (text "ぼくね、最近寂しいの。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "なにかよくないことでも？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (text "アンジュ")
      (proc 19)
      (proc 15)
      (text "今までかわいがってくれた人が最近冷たくって。ねぇ、ぼくのどこがいけないんだと思う？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "アンジュのこと、まだよく知らないから")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (text "アンジュ")
      (proc 19)
      (proc 15)
      (text "そう、そうね。でもね、ホントに寂しいの。" '60392)
      (set-reg 245 #t))
 (seg (? (= V 1))
      (text-frame 8 308 71 323)
      (text "アンジュ")
      (proc 19)
      (text "最近本当に寂しくて")
      (proc 15)
      (proc 15)
      (text-raw 60392))
 (seg (? (= V 2) (= 246 #f))
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "ねえアンジュ、キミの彼ってトニー・フォードなの？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (text "アンジュ")
      (proc 19)
      (text "あ")
      (proc 15)
      (text "あなたトニーのこと知ってるの？　あ、知ってて当たり前かぁ、彼、有名だもんね。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (text "アンジュ")
      (proc 19)
      (text "僕、正直者だから言っちゃうけど")
      (proc 15)
      (text "トニーは僕の恋人。のはずなんだけど、最近彼が冷たくて全然会ってくれないの。" '60392)
      (set-reg 246 #t))
 (seg (? (= V 2) (= 247 #f))
      (text-frame 8 308 71 323)
      (text "アンジュ")
      (proc 19)
      (text "彼と最後に会ったのは、もう遠い昔みたいな気がするの。それも夜遅く、女の人と会った後なんだよ、絶対に")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "女の人と会った後なんて、どうしてわかるの？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (text "アンジュ")
      (proc 19)
      (text "僕には、ジニーとかって言う名前のライバルがいるのは知ってたのよ。だけど、トニーは僕だけを見ててくれると")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (text "アンジュ")
      (proc 19)
      (text "でも、あの日トニーは僕のところへ来て僕がジャケット脱がせたら")
      (proc 15)
      (text "シャツに長いストレートの髪の毛がついてたの。" '60392)
      (set-reg 247 #t))
 (seg (? (= V 2) (= 248 #f))
      (text-frame 8 308 71 323)
      (text "アンジュ")
      (proc 19)
      (text "女を抱いた後で僕のところへ来るなんて")
      (proc 15)
      (text "僕、すごく嫌な気分だったの。でも、その後抱かれちゃったけど")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (proc 15)
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (text "アンジュ")
      (proc 19)
      (text "それが最後になっちゃった")
      (proc 15)
      (text-raw 60392)
      (set-reg 248 #t))
 (seg (? (= V 2))
      (text-frame 8 308 71 323)
      (text "アンジュ")
      (proc 19)
      (text "もしトニーに会う事があったら、僕が会いたいって言ってたって伝言してね。" '60392)
      (set-reg 249 #t))
 (seg (? (= V 3) (= N 0))
      (if (</>
           (//
            (? (= 247 #f))
            (text "こんな可愛い少年趣味があったのか")
            (proc 15)
            (text "奥の深い人物かもねトニー・フォードって。"))
           (//
            (? (= 250 #f))
            (text "長い髪の毛をつけて、か")
            (proc 15)
            (text "ジニーに会った後でアンジュの所へ来たのは間違いなさそうだが、それはいつの事なのか？")
            (set-reg 250 #t))
           (//
            (text "トニーに会ってアンジュをネタに話を聞こう。")))))
 (seg (? (= V 3))
      (if (</>
           (//
            (? (= 243 #f))
            (text "この男の子は、まるで女の子のように可愛いな。しかし、彼から声をかけてくるなんて僕は気に入られたということか？"))
           (//
            (? (= 251 #f))
            (text "この子がアンジュ")
            (proc 15)
            (text "トニーのお気に入りの少年なのか。")
            (proc 18)
            (text "ユリコがトニーのことをバイ・セクシャルと言ってたのは嘘" 'br)
            (text "じゃなかったけど、トニーってかなり面食いなんだな。")
            (set-reg 251 #t))
           (//
            (? (= 249 #f))
            (text "こうして面と向かっているとアンジュが男だなんて忘れてしまいそうだ。危ない道に転ぶ前に早くトニーの事を聞こう。")
            (set-reg 252 #t))
           (//
            (text "職業的なゲイってわけじゃなさそうだ。トニーと付き合ってたのも、金のためだけってわけじゃないようだな。")))))
 (seg (? (= V 4)) (mes-jump "b:¥mes¥4_map.mes"))
 (seg*
  (nop@)
  (text "※※※　バグです　※※※" 'br)
  (text "Ｖ＝")
  (exec-mem 35072 "DISP V")
  (text "　Ｎ＝")
  (exec-mem 35072 "DISP N")))