(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 35072 "@0='ティムの家'")
  (define-proc 12 (<> (text "ジェイク")))
  (define-proc 13 (<> (text "シンディ")))
  (define-proc 14 (<> (text "ティム")))
  (define-proc 15 (<> (text-raw 60393 60393 60393)))
  (branch-reg 22
   (</>
    (/
     (cmd:204 100 199)
     (if (</> (// (? (!= M 3)) (nop@) (sound ' 2))))
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "b:¥gpc¥b26.gpc")
     (image-mem 0)
     (if (</>
          (//
           (? (!= M 3))
           (nop@)
           (sound ' 0)
           (sound ' "uso¥ap_03.uso")
           (sound ' 1)
           (set-var M 3))))
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (delay 50)
     (image-file "b:¥gpc¥b27.gpc")
     (exec-mem 8192 "A 1")
     (text-frame 12 16 67 287)
     (text-reset 0)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (exec-mem 8192 "A 1")
     (image-mem 0)
     (image-file "b:¥gpc¥b27b.gpc")
     (image-mem 1)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (text-frame 14 328 69 383)
     (branch-reg 310
      (</>
       (/
        (text-frame 8 308 71 323)
        (proc 12)
        (proc 19)
        (text "こんにちは、")
        (proc 14)
        (text "。" '60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 14)
        (proc 19)
        (proc 15)
        (proc 15)
        (text "ああ。" '60392)
        (set-reg 310 #t))
       (/
        (text-frame 8 308 71 323)
        (proc 12)
        (proc 19)
        (text "やあ")
        (proc 15)
        (text "元気にしてるかい？" '60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 14)
        (proc 19)
        (text "元気？　どうかな")
        (proc 15)
        (text "どう見える？" '60392))))
     (proc 18)
     (cmd:204 508 509))
    (/
     (nop@)
     (sound ' 2)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "b:¥gpc¥b27.gpc")
     (image-mem 0)
     (image-file "b:¥gpc¥b27b.gpc")
     (image-mem 1)
     (sound ' 0)
     (sound ' "uso¥ap_03.uso")
     (sound ' 1)
     (set-var M 3)
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (cmd:204 24 26)
     (set-reg 22 #f)
     (set-var A 0))))
  (if (</> (// (? (!= A 255)) (nop@) (set-var A 0))))
  (set-var V 0)
  (set-var P 0)
  (set-var C 0)
  (repeat 9 (<> (exec-mem 35072 "A'[C]=0") (inc-var C 1)))
  (loop
   (branch-var P
    (</>
     (/
      (cmd:204 0 11)
      (define-proc 0 (<> (str " ") (text "　　見る　　") (str " ")))
      (set-reg 0 #t)
      (define-proc 1 (<> (str " ") (text "　　話す　　") (str " ")))
      (set-reg 1 #t)
      (define-proc 2 (<> (str " ") (text "　　聞く　　") (str " ")))
      (exec-mem 35072 "#2=#311")
      (define-proc 3 (<> (text "　　考える　　")))
      (exec-mem 35072 "#3=#311")
      (define-proc 4 (<> (str " ") (text "　移動する　") (str " ")))
      (exec-mem 35072 "#4=#311")
      (define-proc 5 (<> (str " ") (text "　システム　") (str " ")))
      (set-reg 5 #t)
      (set-var F 0)
      (mes-load? 0)
      (set-var P 1))
     (/
      (cmd:204 0 11)
      (branch-var V
       (</>
        (/
         (define-proc 0 (<> (text "　　辺りの様子　　")))
         (set-reg 0 #t)
         (define-proc 1 (<> (text "　　　") (proc 14) (text "　　　")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　") (proc 14) (text "　　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0
          (<> (str " ") (text "　アリアナの事　") (str " ")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　") (proc 14) (text "の事　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　") (proc 13) (text "の事　") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　他の場所へ　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　セーブ　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "ゲームを終了する") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 0)
         (if (</>
              (//
               (? (!= S 255))
               (nop@)
               (if (</>
                    (//
                     (? (!= A 255))
                     (nop@)
                     (set-var A 255)
                     (mes-load? "mes¥save.mec" 4096))))
               (mes-load? 4096)
               (if (</>
                    (// (? (= S 254)) (nop@) (set-var P 1))
                    (// (nop@) (set-var F 5) (mes-load? 0))))))))))
      (if (</> (// (? (= S 255)) (nop@) (set-var P 0)))))
     (/
      (if (</>
           (//
            (? (= V 4))
            (nop@)
            (nop@)
            (set-reg 24 #f)
            (set-reg 25 #f)
            (set-reg 26 #f))
           (//
            (nop@)
            (if (</> (// (? (= 26 #t)) (nop@) (set-var F 1) (mes-load? 4096))))
            (set-var F 6)
            (mes-load? 0))))
      (text-frame 14 328 69 383)
      (seg-call)
      (if (</> (// (? (= 315 #t) (= 317 #t)) (nop@) (set-reg 708 #t))))
      (branch-reg 23 (</> (/ (proc 18)) (/ (set-reg 23 #f))))
      (set-var P 0))))))
 (seg (? (= V 0) (= N 0))
      (if (</>
           (//
            (? (= 100 #f))
            (text "ただでさえほとんど何も無い部屋だが、")
            (proc 13)
            (text "がいないとなおさら閑散として見える。")
            (set-reg 100 #t))
           (//
            (? (= 101 #f))
            (text "床やテーブルの上に薄く埃が積もっている。無気力感に取り付かれた")
            (proc 14)
            (text "は、掃除なんてする気にもならないんだろう。")
            (set-reg 101 #f))
           (//
            (text "わずかな")
            (proc 14)
            (text "の持ち物は、すっかり整理されて壁に貼った写真やポスター以外にはほとんど何も残っていない。")
            (set-reg 100 #f)
            (set-reg 101 #f)))))
 (seg (? (= V 0))
      (if (</>
           (//
            (? (= 102 #f))
            (text "おそらく、")
            (proc 13)
            (text "の訃報を聞いてから食事も睡眠も取っていないんだろう。")
            (proc 14)
            (text "の体からは生気のかけらさえ見えない。")
            (set-reg 102 #t))
           (//
            (? (= 103 #f))
            (text "今の")
            (proc 14)
            (text "には下手な慰めや悔やみの言葉など無用らしい。そんな事を言っても、彼の耳には一切届いていない。")
            (set-reg 103 #t))
           (//
            (text "あっと言う間に老けこんでしまったようだ。緩慢な動作からは目的を持って何かをしようという意志が感じられない。")
            (set-reg 102 #f)
            (set-reg 103 #f)))))
 (seg (? (= V 1) (= 311 #f))
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (proc 14)
      (text "、ちゃんと食べてる？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "いや")
      (proc 15)
      (text "今は何ものどを通らないよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "それじゃカラダが弱ってしまう。ちゃんと食べなきゃダメだよ")
      (proc 14)
      (text "。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "いいんだ")
      (proc 15)
      (text "オレなんて")
      (proc 15)
      (text-raw 60392)
      (set-reg 311 #t))
 (seg (? (= V 1) (= 312 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "オレなんて、好きな女も守ってやれないダメな男なんだ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "自分を責めたらいけないよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "だって")
      (proc 15)
      (text "オレがいつもそばにいてやったらこんなことには")
      (proc 15)
      (text "こんな結果にはならなかったよ")
      (proc 15)
      (text "そうだろう？" '60392)
      (set-reg 312 #t))
 (seg (? (= V 1))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "オレ")
      (proc 15)
      (text "もうどうなってもいいや")
      (proc 15)
      (proc 15)
      (text-raw 60392))
 (seg (? (= V 2) (= 313 #f))
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "こんな時に酷なようだけど、")
      (proc 13)
      (text "、いやアリアナがいなくなった時のこと聞かせて欲しいんだ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "オレがバイトに行って")
      (proc 15)
      (text "あの日は後から来るって言ってたんだけど")
      (proc 15)
      (text "でも、ＦＬＩＸに顔見せないままで")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "誰か友達の所へ行こうとしたのかな？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "友達！？")
      (proc 15)
      (text-raw 60393 60393)
      (text "アリアナに友達なんていなかったよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "そんなこと")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "アリアナは人見知りが激しいんだ。")
      (proc 15)
      (text "それにグロリアが" 'br)
      (text "始終つきまとって、友達なんて作らせなかったし")
      (proc 15)
      (text-raw 60392)
      (set-reg 313 #t))
 (seg (? (= V 2) (= 314 #f))
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "なにか思い当たることとか、なかった？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "思い当たる事なんて")
      (proc 15)
      (text "ただ、母親に会えるって楽しみにしてたよ。それ以外、誰かと会うなんて言ってなかったし。" '60392)
      (set-reg 314 #t))
 (seg (? (= V 2) (= 315 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "もういいじゃないか、ここで何を話したってアリアナは生き返らないんだ")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (proc 15)
      (text "ゴメン。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "いいんだ、悪い")
      (proc 15)
      (text "あんたが悪いんじゃないのに")
      (proc 15)
      (text-raw 60392)
      (set-reg 315 #t))
 (seg (? (= V 2))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "オレのせいさ")
      (proc 15)
      (text "全部、オレが")
      (proc 15)
      (text "オレが悪いんだ。" '60392))
 (seg (? (= V 3) (= N 0))
      (if (</>
           (//
            (? (= 316 #f))
            (proc 13)
            (text "は、")
            (proc 14)
            (text "にかまってもらえなかったから死んだわけじゃない。なのに彼は自分を責めている。")
            (set-reg 316 #t))
           (//
            (? (= 317 #f))
            (text "このままじゃ、")
            (proc 14)
            (text "が衰弱して死んでしまうんじゃないかと心配になる。")
            (set-reg 317 #t))
           (//
            (proc 13)
            (text "の事で悔やむべき人間は他にいるはずなんだ。")))))
 (seg (? (= V 3))
      (if (</>
           (//
            (? (= 313 #f))
            (text "もし、今でも")
            (proc 13)
            (text "が生きていて、この部屋にいたら")
            (proc 15)
            (proc 14)
            (text "と")
            (proc 13)
            (text "は幸せになりえただろうか？"))
           (//
            (? (= 318 #f))
            (text "母娘対面の前日、彼女はどこへ行ったんだろう？　誰かに呼び出されて？　あるいはＦＬＩＸに行く途中で？")
            (set-reg 318 #t))
           (//
            (text "これも猟奇殺人事件にかかわっているのだろうか？")))))
 (seg (? (= V 4)) (mes-jump "b:¥mes¥4_map.mes"))
 (seg*
  (nop@)
  (text "※※※　バグです　※※※" 'br)
  (text "Ｖ＝")
  (exec-mem 35072 "DISP V")
  (text "　Ｎ＝")
  (exec-mem 35072 "DISP N")))