(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 35072 "@0='ギュンターのオフィス'")
  (define-proc 12 (<> (text "ジェイク")))
  (define-proc 13 (<> (text "クリスティ")))
  (define-proc 14 (<> (text "ギュンター")))
  (define-proc 15 (<> (text-raw 60393 60393 60393)))
  (branch-reg 22
   (</>
    (/
     (cmd:204 100 199)
     (if (</> (// (? (!= M 3)) (nop@) (sound ' 2))))
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b18.gpc")
     (image-mem 0)
     (if (</>
          (//
           (? (!= M 3))
           (nop@)
           (sound ' 0)
           (sound ' "uso¥ap_03.uso")
           (sound ' 1)
           (set-var M 3))))
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (delay 50)
     (image-file "gpc¥b19.gpc")
     (exec-mem 8192 "A 1")
     (text-frame 12 16 67 287)
     (text-reset 0)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (exec-mem 8192 "A 1")
     (image-mem 0)
     (image-file "gpc¥b19a.gpc")
     (image-mem 1)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (if (</>
          (//
           (? (= 707 #f) (= 234 #f))
           (text-frame 8 308 71 323)
           (proc 14)
           (proc 19)
           (proc 15)
           (text "時間が出来て学会用の資料を作成しようと考えるとあなたがやって来るんですね。" '60392)
           (proc 18)
           (text-frame 8 308 71 323)
           (proc 12)
           (proc 19)
           (text "別に意識してるわけではないんですけど")
           (proc 15)
           (text-raw 60392)
           (proc 18)
           (text-frame 8 308 71 323)
           (proc 14)
           (proc 19)
           (text "意識してそれが出来るとも思えませんしな。" '60392)
           (set-reg 234 #t))
          (//
           (? (= 707 #f))
           (text-frame 8 308 71 323)
           (proc 14)
           (proc 19)
           (text "おや、またあなたですか")
           (proc 15)
           (text-raw 60392))
          (//
           (? (= 235 #f))
           (text-frame 8 308 71 323)
           (proc 14)
           (proc 19)
           (text "よくお見えになりますな。" '60392)
           (set-reg 235 #t))
          (//
           (text-frame 8 308 71 323)
           (proc 14)
           (proc 19)
           (proc 15)
           (text "もう何も話す事はないと思いますが。" '60392))))
     (proc 18)
     (cmd:204 504 506))
    (/
     (nop@)
     (sound ' 2)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b19.gpc")
     (image-mem 0)
     (image-file "gpc¥b19a.gpc")
     (image-mem 1)
     (sound ' 0)
     (sound ' "uso¥ap_03.uso")
     (sound ' 1)
     (set-var M 3)
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (cmd:204 24 26)
     (set-reg 22 #f)
     (set-var A 0))))
  (if (</> (// (? (!= A 255)) (nop@) (set-var A 0))))
  (set-var V 0)
  (set-var P 0)
  (set-var C 0)
  (repeat 9 (<> (exec-mem 35072 "A'[C]=0") (inc-var C 1)))
  (loop
   (branch-var P
    (</>
     (/
      (cmd:204 0 11)
      (define-proc 0 (<> (str " ") (text "　　見る　　") (str " ")))
      (set-reg 0 #t)
      (define-proc 1 (<> (str " ") (text "　　話す　　") (str " ")))
      (set-reg 1 #t)
      (define-proc 2 (<> (str " ") (text "　　聞く　　") (str " ")))
      (exec-mem 35072 "#2=#232")
      (define-proc 3 (<> (text "　　考える　　")))
      (exec-mem 35072 "#3=#232")
      (define-proc 4 (<> (str " ") (text "　移動する　") (str " ")))
      (exec-mem 35072 "#4=#232")
      (define-proc 5 (<> (str " ") (text "　システム　") (str " ")))
      (set-reg 5 #t)
      (set-var F 0)
      (mes-load? 0)
      (set-var P 1))
     (/
      (cmd:204 0 11)
      (branch-var V
       (</>
        (/
         (define-proc 0 (<> (text "　　辺りの様子　　")))
         (set-reg 0 #t)
         (define-proc 1 (<> (text "　　") (proc 14) (text "　　")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　") (proc 14) (text "　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　") (proc 13) (text "の事　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　") (proc 13) (text "の事　")))
         (set-reg 0 #t)
         (define-proc 1 (<> (text "　") (proc 14) (text "の事　")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　他の場所へ　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　セーブ　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "ゲームを終了する") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 0)
         (if (</>
              (//
               (? (!= S 255))
               (nop@)
               (if (</>
                    (//
                     (? (!= A 255))
                     (nop@)
                     (set-var A 255)
                     (mes-load? "mes¥save.mec" 4096))))
               (mes-load? 4096)
               (if (</>
                    (// (? (= S 254)) (nop@) (set-var P 1))
                    (// (nop@) (set-var F 5) (mes-load? 0))))))))))
      (if (</> (// (? (= S 255)) (nop@) (set-var P 0)))))
     (/
      (if (</>
           (//
            (? (= V 4))
            (nop@)
            (nop@)
            (set-reg 24 #f)
            (set-reg 25 #f)
            (set-reg 26 #f))
           (//
            (nop@)
            (if (</> (// (? (= 26 #t)) (nop@) (set-var F 1) (mes-load? 4096))))
            (set-var F 6)
            (mes-load? 0))))
      (text-frame 14 328 69 383)
      (seg-call)
      (branch-reg 23 (</> (/ (proc 18)) (/ (set-reg 23 #f))))
      (set-var P 0))))))
 (seg (? (= V 0) (= N 0))
      (if (</>
           (//
            (? (= 100 #f))
            (text "髪の一本さえ落ちていない掃除の行き届いた部屋。かすかに漂うニオイは病院などで使われるフェノール消毒液のニオイか？")
            (proc 18)
            (text "しかし、ここは本当の意味での" '60522)
            (text "病院" '60523)
            (text "ではない、")
            (proc 14)
            (text "は度を越した潔癖症なのかもしれない。")
            (set-reg 100 #t))
           (//
            (? (= 101 #f))
            (text "医者の部屋に相応しい、簡素で衛生的な部屋")
            (proc 15)
            (text "いや、ギュンターの場合、精神衛生にいい部屋と言うべきか。")
            (set-reg 101 #t))
           (//
            (text "壁の本棚を占領する本は、大半が医学書のようだ。")
            (proc 14)
            (text "ななかなか勉強熱心だな。")
            (set-reg 100 #f)
            (set-reg 101 #f)))))
 (seg (? (= V 0))
      (if (</>
           (//
            (? (= 102 #f))
            (proc 14)
            (text "の笑顔など見た事ないが、今日は一段と表情を曇らせているように見える。")
            (set-reg 102 #t))
           (//
            (? (= 103 #f))
            (text "いつも冷静で、ミスなど犯さない男")
            (proc 15)
            (proc 14)
            (text "は知人の死ぐらいで心を乱したりはしないんだろう。")
            (set-reg 103 #t))
           (//
            (text "いつもどおりのスーツにタイ、かなり度が強いメガネ")
            (proc 15)
            (text "彼の姿を見ると、何故かほっとするような気がする。")
            (set-reg 102 #f)
            (set-reg 103 #f)))))
 (seg (? (= V 1) (= 231 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "どうしました、顔色がすぐれませんな？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "いろいろと心労が多いものですから")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "たとえば、どんな？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "知人に殺された人が")
      (proc 15)
      (text "短期間に何人も")
      (proc 15)
      (text "それで少し参っています。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "なるほど")
      (proc 15)
      (text "それでは、あの件は話さない方がいいかな。" '60392)
      (set-reg 231 #t))
 (seg (? (= V 1) (= 232 #f))
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "あの件？　それは一体なんなんですか？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "いや、その")
      (proc 15)
      (text "あなたが落ち着いてる時にお話しした方がよいでしょう。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "言いかけて内緒にされたらますます心労が募ります、どうか教えて下さい。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (proc 15)
      (text "確かに、それもそうですな。" '60392)
      (set-reg 232 #t))
 (seg (? (= V 1))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "あなたもあまり抱え込まない事です。所詮、どうあがいた所で個人で出来る事は些細なことですからね。" '60392))
 (seg (? (= V 2) (= 233 #f))
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "また")
      (proc 13)
      (text "のことなんですね？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "その通りですよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "やはり、私の予測通り、彼女はかなり危険です。もしかすると人をあやめている可能性があるかもしれない。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "そんな滅多なことを口にしないでください。彼女に限ってそんな事")
      (proc 15)
      (text "有り得ませんよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "今でなくても過去にさかのぼれば")
      (proc 15)
      (text "いや、あるいは今だって十分可能性はあるのです。" '60392)
      (set-reg 233 #t))
 (seg (? (= V 2) (= 707 #f))
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "そんなこと、そんなこと僕に言われても")
      (proc 15)
      (text "どうしろって言うんですか？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "あなたにどうしろとは言いません。ただ、彼女のことを気にかけて頂きたい。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "もっとも、今のあなたには酷なことでしょうな。他人より自分のことを気にかけなければ参ってしまいそうだ。" '60392)
      (set-reg 707 #t))
 (seg (? (= V 2))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "あなたに頭痛のタネを増やしてしまって申し訳ないが")
      (proc 15)
      (text "とにかくミス・ダーンの事を忘れないで、彼女は危険だ。" '60392))
 (seg (? (= V 3) (= N 0))
      (branch-reg 233
       (</>
        (/
         (proc 13)
         (text "にまた何かあったのか")
         (proc 15)
         (text "というより、治っていないというだけのことか。"))
        (/
         (proc 13)
         (text "が人を殺めるだって")
         (proc 15)
         (text "そんなはずがないじゃないか。")))))
 (seg (? (= V 3))
      (branch-reg 233
       (</>
        (/
         (text "今のように疲れてるときは、")
         (proc 14)
         (text "のカウンセリングを受けてラクになりたい気分だ。"))
        (/
         (proc 14)
         (text "はまだ")
         (proc 13)
         (text "が殺人を犯すなんて考えをぬぐいされずにいるのか")
         (proc 15)))))
 (seg (? (= V 4)) (mes-jump "b:¥mes¥4_map.mes"))
 (seg*
  (nop@)
  (text "※※※　バグです　※※※" 'br)
  (text "Ｖ＝")
  (exec-mem 35072 "DISP V")
  (text "　Ｎ＝")
  (exec-mem 35072 "DISP N")))