(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 35072 "@0='クラブＦＬＩＸ'")
  (define-proc 12 (<> (text "ジェイク")))
  (define-proc 13 (<> (text "シンディ")))
  (define-proc 14 (<> (text "ティム")))
  (define-proc 15 (<> (text-raw 60393 60393 60393)))
  (branch-reg 22
   (</>
    (/
     (cmd:204 100 199)
     (if (</> (// (? (!= M 3)) (nop@) (sound ' 2))))
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b20.gpc")
     (image-mem 0)
     (if (</>
          (//
           (? (!= M 3))
           (nop@)
           (sound ' 0)
           (sound ' "uso¥ap_03.uso")
           (sound ' 1)
           (set-var M 3))))
     (cmd:209 1 2)
     (delay 50)
     (image-file "gpc¥b21.gpc")
     (exec-mem 8192 "A 1")
     (text-frame 12 16 67 287)
     (text-reset 0)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (exec-mem 8192 "A 1")
     (image-mem 0)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (if (</>
          (//
           (? (= 520 #f))
           (text-frame 8 308 71 323)
           (text "カウンターの男")
           (proc 19)
           (text "あんたか")
           (proc 15)
           (proc 14)
           (text "は休んでるぜ。" '60392)
           (set-reg 520 #t))
          (//
           (? (= 521 #f))
           (text-frame 8 308 71 323)
           (text "カウンターの男")
           (proc 19)
           (text "いらっしゃい")
           (proc 15)
           (text-raw 60392)
           (set-reg 521 #t))
          (//
           (text-frame 8 308 71 323)
           (text "カウンターの男")
           (proc 19)
           (text "あんたもよく来るね、最近さ。" '60392))))
     (proc 18))
    (/
     (nop@)
     (sound ' 2)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b21.gpc")
     (image-mem 0)
     (sound ' 0)
     (sound ' "uso¥ap_03.uso")
     (sound ' 1)
     (set-var M 3)
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (cmd:204 24 26)
     (set-reg 22 #f)
     (set-var A 0))))
  (if (</> (// (? (!= A 255)) (nop@) (set-var A 0))))
  (set-var V 0)
  (set-var P 0)
  (set-var C 0)
  (repeat 9 (<> (exec-mem 35072 "A'[C]=0") (inc-var C 1)))
  (loop
   (branch-var P
    (</>
     (/
      (cmd:204 0 11)
      (define-proc 0 (<> (str " ") (text "　　見る　　") (str " ")))
      (set-reg 0 #t)
      (define-proc 1 (<> (str " ") (text "　　話す　　") (str " ")))
      (set-reg 1 #t)
      (define-proc 2 (<> (str " ") (text "　　聞く　　") (str " ")))
      (exec-mem 35072 "#2=#522")
      (define-proc 3 (<> (text "　　考える　　")))
      (exec-mem 35072 "#3=#522")
      (define-proc 4 (<> (str " ") (text "　移動する　") (str " ")))
      (exec-mem 35072 "#4=#522")
      (define-proc 5 (<> (str " ") (text "　システム　") (str " ")))
      (set-reg 5 #t)
      (set-var F 0)
      (mes-load? 0)
      (set-var P 1))
     (/
      (cmd:204 0 11)
      (branch-var V
       (</>
        (/
         (define-proc 0 (<> (text "　　辺りの様子　　")))
         (set-reg 0 #t)
         (define-proc 1 (<> (text "　カウンターの男　")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　カウンターの男　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　") (proc 14) (text "の事　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　アリアナの事　") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　") (proc 14) (text "の事　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　") (proc 13) (text "の事　") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　他の場所へ　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　セーブ　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "ゲームを終了する") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 0)
         (if (</>
              (//
               (? (!= S 255))
               (nop@)
               (if (</>
                    (//
                     (? (!= A 255))
                     (nop@)
                     (set-var A 255)
                     (mes-load? "mes¥save.mec" 4096))))
               (mes-load? 4096)
               (if (</>
                    (// (? (= S 254)) (nop@) (set-var P 1))
                    (// (nop@) (set-var F 5) (mes-load? 0))))))))))
      (if (</> (// (? (= S 255)) (nop@) (set-var P 0)))))
     (/
      (if (</> (// (? (= 26 #t)) (nop@) (set-var F 1) (mes-load? 4096))))
      (set-var F 6)
      (mes-load? 0)
      (text-frame 14 328 69 383)
      (seg-call)
      (branch-reg 23 (</> (/ (proc 18)) (/ (set-reg 23 #f))))
      (set-var P 0))))))
 (seg (? (= V 0) (= N 0))
      (if (</>
           (//
            (? (= 100 #f))
            (text "店内には")
            (proc 14)
            (text "の姿も、客の姿も無い。僕とバーテンの男の二人だけだ。")
            (set-reg 100 #t))
           (//
            (? (= 101 #f))
            (text "明かりは落ちたまま、音楽も流れていない。黙々とグラスを磨くバーテンの姿があるだけの、ひどく淋しい光景")
            (proc 15)
            (set-reg 101 #t))
           (//
            (text "お世辞にもキレイとは言えない店だ。")
            (set-reg 100 #f)
            (set-reg 101 #f)))))
 (seg (? (= V 0))
      (if (</>
           (//
            (? (= 102 #f))
            (text "３０代の前半ってとこだろうか、")
            (proc 14)
            (text "や大方の客のような派手な格好はしていない。")
            (set-reg 102 #t))
           (//
            (? (= 103 #f))
            (text "この時間から閉店までずっと働きづめなんだろうか？　そんな事が出来るタフガイには見えないが")
            (proc 15)
            (set-reg 103 #t))
           (//
            (text "特に僕に興味があるようでもなく、ただ義務的にこちらを向いて適当に話をあわせているって雰囲気だ。")
            (set-reg 102 #f)
            (set-reg 103 #f)))))
 (seg (? (= V 1) (= 522 #f))
      (text-frame 8 308 71 323)
      (text "カウンターの男")
      (proc 19)
      (proc 14)
      (text "は休んでるぜ。会いたいなら家に行けばいいさ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (proc 14)
      (text "、最近どんな調子？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (text "カウンターの男")
      (proc 19)
      (text "もう全然だめ。使い物にならなくなっちまったよ。" '60392)
      (set-reg 522 #t))
 (seg (? (= V 1))
      (text-frame 8 308 71 323)
      (text "カウンターの男")
      (proc 19)
      (text "商売やってる方としては、困り者だよな、あいつ。" '60392))
 (seg (? (= V 2) (= N 0) (= 523 #f))
      (text-frame 8 308 71 323)
      (text "カウンターの男")
      (proc 19)
      (proc 14)
      (text "さぁ、最近ひどく落ち込んでるんだ。あれじゃ辛気臭くていけないね。なんとか言ってやってよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "いま彼も大変だから")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (text "カウンターの男")
      (proc 19)
      (text "わかってるけどさ、女に逃げられたくらいで")
      (proc 15)
      (text "オレからすれば甘ちゃんだよ。" '60392)
      (set-reg 523 #t))
 (seg (? (= V 2) (= N 0) (= 524 #f))
      (text-frame 8 308 71 323)
      (text "カウンターの男")
      (proc 19)
      (proc 14)
      (text "はいい奴だけど、あまり胸のうちを開いてくれないんだよな。だから助けてもやれない。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "そういうところはあるけど、僕には比較的話してくれてる気がするよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (text "カウンターの男")
      (proc 19)
      (text "そりゃあそうさ、あんた達はダチだから")
      (proc 15)
      (text-raw 60392)
      (set-reg 524 #t))
 (seg (? (= V 2) (= N 0))
      (text-frame 8 308 71 323)
      (text "カウンターの男")
      (proc 19)
      (proc 14)
      (text "、仕事に復帰できるのかな？" '60392))
 (seg (? (= V 2) (= 525 #f))
      (text-frame 8 308 71 323)
      (text "カウンターの男")
      (proc 19)
      (text "アリアナの姿は見てないよ。前は")
      (proc 14)
      (text "をからかいに来たりしてたのにな。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "そうか、そうだよね")
      (proc 15)
      (text "来てるわけないか。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (text "カウンターの男")
      (proc 19)
      (text "なんだよ、ただのケンカじゃないのか？" '60392)
      (set-reg 525 #t))
 (seg (? (= V 2) (= 526 #f))
      (text-frame 8 308 71 323)
      (text "カウンターの男")
      (proc 19)
      (text "よくわかんないけど、")
      (proc 14)
      (text "が甘やかしすぎでつけあがった結果なんじゃないかな。他人が口出す事じゃないよ。" '60392)
      (set-reg 526 #t))
 (seg (? (= V 2))
      (text-frame 8 308 71 323)
      (text "カウンターの男")
      (proc 19)
      (text "アリアナが来なくなったら客足も遠退いちゃって、ちょっと" 'br)
      (text "ショックなんだよね。" '60392))
 (seg (? (= V 3) (= N 0))
      (branch-reg 527
       (</>
        (/
         (proc 13)
         (text "が死んでしまった事が余程ショックだったんだな")
         (text-raw 60393 60393)
         (text "ついに参ってしまったのか。")
         (set-reg 527 #t))
        (/
         (proc 14)
         (text "に会いに彼の部屋に行ってみようか？")))))
 (seg (? (= V 3))
      (branch-reg 528
       (</>
        (/
         (text "この男はアリアナ＝")
         (proc 13)
         (text "だと言う事を知らない。そして、彼女がすでに死んでしまったことも")
         (proc 15)
         (set-reg 528 #t))
        (/
         (text "今思えば、ここに来ている時の")
         (proc 13)
         (text "が一番生き生きしていたのかもしれないな")
         (proc 15)))))
 (seg (? (= V 4))
      (text-frame 8 308 71 323)
      (text "カウンターの男")
      (proc 19)
      (text "またな。" '60392)
      (cmd:203 1 0)
      (exec-mem 12288 0 20 (bytes 235 186) 72 368 0 1021 2)
      (text-frame 8 308 69 383)
      (cmd:203 1 1)
      (mes-jump "b:¥mes¥4_map.mes"))
 (seg*
  (nop@)
  (text "※※※　バグです　※※※" 'br)
  (text "Ｖ＝")
  (exec-mem 35072 "DISP V")
  (text "　Ｎ＝")
  (exec-mem 35072 "DISP N")))