(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 35072 "@0='ＮＥＴＳ球団事務所'")
  (define-proc 12 (<> (text "ジェイク")))
  (define-proc 13 (<> (text "ガリソン")))
  (define-proc 15 (<> (text-raw 60393 60393 60393)))
  (branch-reg 22
   (</>
    (/
     (cmd:204 100 199)
     (if (</> (// (? (!= M 3)) (nop@) (sound ' 2))))
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b28.gpc")
     (image-mem 0)
     (if (</>
          (//
           (? (!= M 3))
           (nop@)
           (sound ' 0)
           (sound ' "uso¥ap_03.uso")
           (sound ' 1)
           (set-var M 3))))
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (delay 50)
     (image-file "gpc¥b29.gpc")
     (exec-mem 8192 "A 1")
     (text-frame 12 16 67 287)
     (text-reset 0)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (exec-mem 8192 "A 1")
     (image-mem 0)
     (image-file "gpc¥b29a.gpc")
     (image-mem 1)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (text-frame 14 328 69 383)
     (text-frame 8 308 71 323)
     (proc 13)
     (proc 19)
     (text "もうガイは解放したんだよ。彼の自宅に行けばあえるんじゃないのかね？" '60392)
     (proc 18))
    (/
     (nop@)
     (sound ' 2)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b29.gpc")
     (image-mem 0)
     (image-file "gpc¥b29a.gpc")
     (image-mem 1)
     (sound ' 0)
     (sound ' "uso¥ap_03.uso")
     (sound ' 1)
     (set-var M 3)
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (cmd:204 24 26)
     (set-reg 22 #f)
     (set-var A 0))))
  (if (</> (// (? (!= A 255)) (nop@) (set-var A 0))))
  (set-var V 0)
  (set-var P 0)
  (set-var C 0)
  (repeat 9 (<> (exec-mem 35072 "A'[C]=0") (inc-var C 1)))
  (loop
   (branch-var P
    (</>
     (/
      (cmd:204 0 11)
      (define-proc 0 (<> (str " ") (text "　　見る　　") (str " ")))
      (set-reg 0 #t)
      (define-proc 1 (<> (str " ") (text "　　話す　　") (str " ")))
      (set-reg 1 #t)
      (define-proc 2 (<> (str " ") (text "　　聞く　　") (str " ")))
      (exec-mem 35072 "#2=#151")
      (define-proc 3 (<> (text "　　考える　　")))
      (exec-mem 35072 "#3=#151")
      (define-proc 4 (<> (str " ") (text "　移動する　") (str " ")))
      (exec-mem 35072 "#4=#721")
      (define-proc 5 (<> (str " ") (text "　システム　") (str " ")))
      (set-reg 5 #t)
      (set-var F 0)
      (mes-load? 0)
      (set-var P 1))
     (/
      (cmd:204 0 11)
      (branch-var V
       (</>
        (/
         (define-proc 0 (<> (text "　　辺りの様子　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　　") (proc 13) (text "　　") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0
          (<> (str " ") (text "　　") (proc 13) (text "　　") (str " ")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0
          (<> (str " ") (text "　　ガイの事　　") (str " ")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0
          (<> (str " ") (text "　　ガイの事　　") (str " ")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　") (proc 13) (text "の事　") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　他の場所へ　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　セーブ　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "ゲームを終了する") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 0)
         (if (</>
              (//
               (? (!= S 255))
               (nop@)
               (if (</>
                    (//
                     (? (!= A 255))
                     (nop@)
                     (set-var A 255)
                     (mes-load? "mes¥save.mec" 4096))))
               (mes-load? 4096)
               (if (</>
                    (// (? (= S 254)) (nop@) (set-var P 1))
                    (// (nop@) (set-var F 5) (mes-load? 0))))))))))
      (if (</> (// (? (= S 255)) (nop@) (set-var P 0)))))
     (/
      (if (</> (// (? (= 26 #t)) (nop@) (set-var F 1) (mes-load? 4096))))
      (set-var F 6)
      (mes-load? 0)
      (text-frame 14 328 69 383)
      (seg-call)
      (branch-reg 23 (</> (/ (proc 18)) (/ (set-reg 23 #f))))
      (set-var P 0))))))
 (seg (? (= V 0) (= N 0))
      (if (</>
           (//
            (? (= 100 #f))
            (text "シーズンオフだからか、元々球団事務所に用がある人間などそれほどいないからか知らないが、僕以外に客はいない。")
            (set-reg 100 #t))
           (//
            (? (= 101 #f))
            (text "商談用の小さなブースがいくつかと、僕の正面にある受付の他には、特にこれといった物はない。")
            (set-reg 101 #t))
           (//
            (proc 13)
            (text "の陰に隠れた、ブロンドの子の方が僕の好みだ。")
            (set-reg 100 #f)
            (set-reg 101 #f)))))
 (seg (? (= V 0))
      (if (</>
           (//
            (? (= 102 #f))
            (text "僕の姿を見ると、露骨に嫌な顔をする。会いたくないのは僕だって一緒だ。")
            (proc 13)
            (text "には社交性が足りないな")
            (proc 15)
            (set-reg 102 #t))
           (//
            (? (= 103 #f))
            (text "愛敬のある顔、滑稽なほど丸い体つき。マスコミや大衆には受けるだろうが、僕はそんな外見には騙されないぞ。")
            (set-reg 103 #t))
           (//
            (text "何があってもとぼけた態度を崩すつもりはないようだ。僕ぐらいなら知らぬ存ぜぬで押し通せると思っているんだろうか。")
            (set-reg 102 #f)
            (set-reg 103 #f)))))
 (seg (? (= V 1) (= 151 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "ガイに会う場所を間違えているよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "今日はあなたに会いに来たんです。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "こちらとしては、二度と会いたくないのだが")
      (proc 15)
      (text-raw 60392)
      (set-reg 151 #t))
 (seg (? (= V 1) (= 721 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "これから、また色々と忙しくなりますなぁ")
      (proc 15)
      (text-raw 60392))
 (seg (? (= V 1))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "もう二度と来ないでくれ。" '60392))
 (seg (? (= V 2) (= 104 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "ガイなら自宅にいるでしょう。彼の事は彼にお聞きなさい。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "そんなことより、ゴシップ記事が球団の手によるものだという話を耳にしたんですが、それは事実なんですか？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "そんなことはありませんよ。" '60392)
      (set-reg 104 #t))
 (seg (? (= V 2) (= 721 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (proc 15)
      (text "変な誤解をうむのはごめんだよ。いいかね、あの記事はガイがエヴァに書かせた記事なんだ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "そんなバカな")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "うそだと思うなら本人に聞いてみたまえ。" '60392)
      (set-reg 721 #t))
 (seg (? (= V 2))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "もう二度と来ないでくれ。" '60392))
 (seg (? (= V 3) (= N 0))
      (branch-reg 721
       (</>
        (/ (text "ガイが戻ってきてよかった。"))
        (/
         (text "ガイが自分からゴシップを広めるような真似を？　わざわざ自分の評判を落とすような事をするとは信じられない。")))))
 (seg (? (= V 3))
      (proc 13)
      (text "もガイの監禁に一枚噛んでたんだな。球団のためなら犯罪者になる事も厭わないってわけか、大した根性だ。"))
 (seg (? (= V 4))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "もう二度と来ないで下さい。今度こそあなたにこのドアはくぐらせません。" '60392)
      (cmd:203 1 0)
      (exec-mem 12288 0 20 (bytes 235 186) 72 368 0 1021 2)
      (text-frame 8 308 69 383)
      (cmd:203 1 1)
      (mes-jump "b:¥mes¥4_map.mes"))
 (seg*
  (nop@)
  (text "※※※　バグです　※※※" 'br)
  (text "Ｖ＝")
  (exec-mem 35072 "DISP V")
  (text "　Ｎ＝")
  (exec-mem 35072 "DISP N")))