(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 35072 "@0='ギュンターのオフィス'")
  (define-proc 12 (<> (text "ジェイク")))
  (define-proc 13 (<> (text "クリスティ")))
  (define-proc 14 (<> (text "ギュンター")))
  (define-proc 15 (<> (text-raw 60393 60393 60393)))
  (branch-reg 22
   (</>
    (/
     (cmd:204 100 199)
     (if (</> (// (? (!= M 12)) (nop@) (sound ' 2))))
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b18.gpc")
     (image-mem 0)
     (if (</>
          (//
           (? (!= M 12))
           (nop@)
           (sound ' 0)
           (sound ' "uso¥ap_12.uso")
           (sound ' 1)
           (set-var M 12))))
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (if (</>
          (//
           (? (= 793 #t))
           (if (</>
                (//
                 (? (= 550 #f))
                 (proc 14)
                 (text "は留守のようだ。")
                 (set-reg 550 #t))
                (//
                 (? (= 551 #f))
                 (text "誰もいない")
                 (proc 15)
                 (text "食事にでも行ったんだろうか？")
                 (set-reg 551 #t))
                (// (text "まだ戻っていないようだ") (proc 15))))
           (cmd:203 1 0)
           (exec-mem 12288 0 20 (bytes 235 186) 72 368 0 1021 2)
           (text-frame 8 308 69 383)
           (cmd:203 1 1)
           (mes-jump "b:¥mes¥5_map.mes"))))
     (delay 50)
     (if (</>
          (//
           (? (= 720 #t) (= 721 #t) (= 722 #t) (= 723 #t) (= 724 #t) (= 732 #f))
           (exec-mem 4096 "INIT")
           (exec-mem 4096 "MODE M50")
           (exec-mem 4096 "LOAD gpc¥b19.gpc,KEEP")
           (exec-mem 4096 "LOAD gpc¥b19a.gpc,KEEP")
           (exec-mem 4096 "LOAD b:¥gpc¥b19b.gpc,KEEP")
           (exec-mem 8192 "A 1")
           (text-frame 12 16 67 287)
           (text-reset 0)
           (exec-mem 8192 "A 0")
           (exec-mem 16384 12 16 67 287 3 1)
           (exec-mem 8192 "A 1")
           (exec-mem 4096 "COPY gpc¥b19.gpc,GPC")
           (image-mem 0)
           (exec-mem 4096 "COPY b:¥gpc¥b19b.gpc,GPC")
           (image-mem 1)
           (image-file "b:¥gpc¥b19c.gpc")
           (image-mem 1)
           (exec-mem 8192 "A 0")
           (exec-mem 16384 12 16 67 287 3 1)
           (text-frame 14 328 69 383)
           (text "受付から通されたものの、")
           (proc 14)
           (text "は席を外していた。")
           (proc 18)
           (text "ふと、机に目をやると、そこには一冊のファイルが置かれていた。")
           (proc 18)
           (text "その背表紙には、ジェニファー・ランフォードの記録と書いてあった。")
           (proc 18)
           (text-frame 8 308 69 383)
           (text 'br)
           (text "　　" '60331)
           (text-frame 14 328 69 383)
           (text "ジェニファー・ランフォード？　もしかして、女優のジェニファーのカルテなのか？" '60332)
           (proc 18)
           (text "好奇心にかられファイルに手を伸ばしかけたところへギュンターが戻って来てしまった。")
           (proc 18)
           (exec-mem 8192 "A 1")
           (exec-mem 4096 "COPY gpc¥b19.gpc,GPC")
           (image-mem 0)
           (exec-mem 4096 "COPY b:¥gpc¥b19b.gpc,GPC")
           (image-mem 1)
           (exec-mem 4096 "COPY gpc¥b19a.gpc,GPC")
           (image-mem 1)
           (exec-mem 4096 "EXIT")
           (exec-mem 8192 "A 0")
           (exec-mem 17664 21 39 65 287 1 0)
           (text-frame 8 308 71 323)
           (proc 14)
           (proc 19)
           (text "お待たせしてすまんね。電話が入ってしまって")
           (proc 15)
           (text "おやこれは")
           (proc 15)
           (text "しまい忘れていたな。" '60392)
           (set-reg 732 #t))
          (//
           (image-file "gpc¥b19.gpc")
           (exec-mem 8192 "A 1")
           (text-frame 12 16 67 287)
           (text-reset 0)
           (exec-mem 8192 "A 0")
           (exec-mem 16384 12 16 67 287 3 1)
           (exec-mem 8192 "A 1")
           (image-mem 0)
           (if (</>
                (//
                 (? (= 732 #t))
                 (nop@)
                 (image-file "b:¥gpc¥b19b.gpc")
                 (image-mem 1))))
           (image-file "gpc¥b19a.gpc")
           (image-mem 1)
           (exec-mem 8192 "A 0")
           (exec-mem 16384 12 16 67 287 3 1)
           (branch-reg 200
            (</>
             (/
              (text-frame 8 308 71 323)
              (proc 14)
              (proc 19)
              (text "ミス・ダーンがお亡くなりになったようですな。" '60392)
              (proc 18)
              (text-frame 8 308 71 323)
              (proc 12)
              (proc 19)
              (text "ご存じでしたか。" '60392)
              (proc 18)
              (text-frame 8 308 71 323)
              (proc 14)
              (proc 19)
              (text "ニュースぐらいは見ますから。それで、何か？" '60392)
              (set-reg 200 #t))
             (/
              (text-frame 8 308 71 323)
              (proc 14)
              (proc 19)
              (text "またあなたですか。" '60392)))))))
     (proc 18))
    (/
     (nop@)
     (sound ' 2)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b19.gpc")
     (image-mem 0)
     (if (</>
          (//
           (? (= 732 #t))
           (nop@)
           (image-file "b:¥gpc¥b19b.gpc")
           (image-mem 1))))
     (image-file "gpc¥b19a.gpc")
     (image-mem 1)
     (sound ' 0)
     (sound ' "uso¥ap_12.uso")
     (sound ' 1)
     (set-var M 12)
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (cmd:204 24 26)
     (set-reg 22 #f)
     (set-var A 0))))
  (if (</> (// (? (!= A 255)) (nop@) (set-var A 0))))
  (set-var V 0)
  (set-var P 0)
  (set-var C 0)
  (repeat 9 (<> (exec-mem 35072 "A'[C]=0") (inc-var C 1)))
  (loop
   (branch-var P
    (</>
     (/
      (cmd:204 0 11)
      (define-proc 0 (<> (str " ") (text "　　見る　　") (str " ")))
      (set-reg 0 #t)
      (define-proc 1 (<> (str " ") (text "　　話す　　") (str " ")))
      (set-reg 1 #t)
      (define-proc 2 (<> (str " ") (text "　　聞く　　") (str " ")))
      (exec-mem 35072 "#2=#201")
      (define-proc 3 (<> (text "　　考える　　")))
      (exec-mem 35072 "#3=#201")
      (define-proc 4 (<> (str " ") (text "　移動する　") (str " ")))
      (exec-mem 35072 "#4=#201")
      (define-proc 5 (<> (str " ") (text "　システム　") (str " ")))
      (set-reg 5 #t)
      (set-var F 0)
      (mes-load? 0)
      (set-var P 1))
     (/
      (cmd:204 0 11)
      (branch-var V
       (</>
        (/
         (define-proc 0 (<> (text "　　辺りの様子　　")))
         (set-reg 0 #t)
         (define-proc 1 (<> (text "　　") (proc 14) (text "　　")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　") (proc 14) (text "　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0
          (<> (str " ") (text "ジェニファーの事") (str " ")))
         (exec-mem 35072 "#0=#732")
         (define-proc 1 (<> (text "　") (proc 13) (text "の事　")))
         (set-reg 1 #t)
         (define-proc 2
          (<> (str " ") (text "猟奇殺人事件の事") (str " ")))
         (set-reg 2 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　") (proc 14) (text "の事　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "ジェニファーの事") (str " ")))
         (exec-mem 35072 "#1=#203")
         (define-proc 2 (<> (text "　") (proc 13) (text "の事　")))
         (set-reg 2 #t)
         (define-proc 3
          (<> (str " ") (text "猟奇殺人事件の事") (str " ")))
         (set-reg 3 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　他の場所へ　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　セーブ　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "ゲームを終了する") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 0)
         (if (</>
              (//
               (? (!= S 255))
               (nop@)
               (if (</>
                    (//
                     (? (!= A 255))
                     (nop@)
                     (set-var A 255)
                     (mes-load? "mes¥save.mec" 4096))))
               (mes-load? 4096)
               (if (</>
                    (// (? (= S 254)) (nop@) (set-var P 1))
                    (// (nop@) (set-var F 5) (mes-load? 0))))))))))
      (if (</> (// (? (= S 255)) (nop@) (set-var P 0)))))
     (/
      (if (</>
           (//
            (? (= V 4))
            (nop@)
            (nop@)
            (set-reg 24 #f)
            (set-reg 25 #f)
            (set-reg 26 #f))
           (//
            (nop@)
            (if (</> (// (? (= 26 #t)) (nop@) (set-var F 1) (mes-load? 4096))))
            (set-var F 6)
            (mes-load? 0))))
      (text-frame 14 328 69 383)
      (seg-call)
      (if (</> (// (? (= 205 #t) (= 207 #t)) (nop@) (set-reg 723 #t))))
      (branch-reg 23 (</> (/ (proc 18)) (/ (set-reg 23 #f))))
      (set-var P 0))))))
 (seg (? (= V 0) (= N 0))
      (if (</>
           (//
            (? (= 100 #f))
            (text "僕と")
            (proc 14)
            (text "の他には誰もいない。精神科医には助手や看護婦は必要ないらしい。")
            (set-reg 100 #t))
           (//
            (? (= 101 #f))
            (text "何度見ても、殺風景としか形容し難い空間だ。フランス人なら３日、イタリア人なら５分で逃げ出すって感じかな")
            (proc 15)
            (set-reg 101 #t))
           (//
            (text "壁や床は暗色に統一され、本棚は医学書と思しき本で埋まっている。装飾と言えるのは窓際の緑の鉢だけだ。")
            (set-reg 100 #f)
            (set-reg 101 #f)))))
 (seg (? (= V 0) (= N 1))
      (if (</>
           (//
            (? (= 102 #f))
            (proc 13)
            (text "の死を知っていながら、動揺している様子もない。患者の死なんて何とも感じないんだろうか？")
            (set-reg 102 #t))
           (//
            (? (= 103 #f))
            (text "まるで、")
            (proc 13)
            (text "の死を予期していたかのような冷静さだ。患者が突然死亡する事など珍しくはないのだろうが")
            (proc 15)
            (set-reg 103 #t))
           (//
            (text "普段と変わらない無表情で感情の無い顔だ。")
            (set-reg 102 #f)
            (set-reg 103 #f)))))
 (seg (? (= V 1) (= 201 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "少しでも接触のあった人間が死んでしまうのは、あまりいい気持ちがしませんな。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "いい気持ちがしない、という表現は嫌な言い方ですね。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "いや、失礼。悪気があったわけではないのですが")
      (proc 15)
      (text "ところで今日は一体どんなご用件でしょう？" '60392)
      (set-reg 201 #t))
 (seg (? (= V 1) (= 732 #t) (= 202 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "私とあなたの間にもう語り合う話もなくなったと思いますが？それとも、何かまだ気になることでも？" '60392)
      (set-reg 202 #t))
 (seg (? (= V 1) (= 732 #t))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "私はこれから忙しくなるのです。もう少しで研究の成果が上がりそうなんですよ。くくくっ")
      (proc 15)
      (text-raw 60392))
 (seg (? (= V 1))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "今日の訪問は、ミス・ダーンの死と関係あるんでしょうか？" '60392))
 (seg (? (= V 2) (= N 0) (= 203 #f))
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "その、机上のファイルは女優のジェニファー・ランフォードのものですか？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (proc 15)
      (text "いや、これは")
      (proc 15)
      (text "仮に彼女のものだったら何だとおっしゃりたいのです？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "いえ、ただ、少し気になって")
      (proc 15)
      (text-raw 60392)
      (set-reg 203 #t))
 (seg (? (= V 2) (= N 0) (= 725 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "ミス・ダーンはあなたのご友人でもありましたから、彼女を心配するあなたに色々とお話してきました。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "それはとても感謝しています。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "が、ジェニファーの場合は有名な女優で、しかもあなたとは何のつながりもない女性だ。お話すべき事は何もありません。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "ええ、まあ、そうですね。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "好奇心旺盛なのは探偵の習性ですかな？" '60392)
      (set-reg 725 #t))
 (seg (? (= V 2) (= N 0))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "何もお話出来る事はありませんね。患者のプライバシーを侵す訳にはいきませんから。" '60392))
 (seg (? (= V 2) (= N 1) (= 204 #f))
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "一説によると、")
      (proc 13)
      (text "は自殺を計ったらしいのですが、それに関しての見解をお聞かせ願えればと思いまして。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "彼女の意志で自殺することは有り得なかったんではないかと思いますよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "それはどういう理由からですか？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "確かに彼女は人をも殺しかねないトラウマを心の中に抱えているようでした。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "が、あくまでもそれは自己防衛の為の手段でしたから、自らの命を断つような方向へは向かない性質のものだと思います。" '60392)
      (set-reg 204 #t))
 (seg (? (= V 2) (= N 1) (= 205 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "最悪の場合、車に同乗していた婚約者が心中を計ったと考えられなくもないですが、たぶん、事故なのではないですか？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "僕も事故だと思うんです。場所が場所でしたからね。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "あの辺りじゃ雨の降った後の路面状況は最悪でしょう。スピードの出し過ぎでハンドル操作を誤ったことが原因ですかな。" '60392)
      (set-reg 205 #t))
 (seg (? (= V 2) (= N 1))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "ガイのように際立った体躯をした人間は、自分の力を誇示するためにスピード狂になる事が多いんですよ。" '60392))
 (seg (? (= V 2) (= N 2) (= 206 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "彼女がお亡くなりになったので、もう申し上げてもかまわないだろうと思うのですが")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "なんでしょうか？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "実は、私は彼女が猟奇殺人事件にかかわっていたのではないかと疑っていた時期がありました。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "それは")
      (proc 15)
      (text "どういう理由でなのか教えて頂けますか。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "理由は単純です。彼女が著しく不安定になった後、２、３日後に必ず殺人が起きその後彼女の調子が良くなったからです。" '60392)
      (set-reg 206 #t))
 (seg (? (= V 2) (= N 2) (= 207 #f))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "ミス・ダーンの状態を観察して、この殺人事件と何等かの関りがあるかもしれないと危惧を抱いたのですが")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "このまま新たな切断させた死体が発見されなければ、あるいは")
      (proc 15)
      (text "ということですか？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "そうです。今後、同様の事件がおきなければ彼女が犯人だったかもしれないと、まだ疑っています。" '60392)
      (set-reg 207 #t))
 (seg (? (= V 2) (= N 2))
      (text-frame 8 308 71 323)
      (proc 14)
      (proc 19)
      (text "今となってはどうでもいい事ですね。彼女を罰する事は誰にも出来ないんですから。" '60392))
 (seg (? (= V 3) (= N 0))
      (if (</>
           (//
            (? (= 207 #f))
            (text "どこまでも冷静で、感情の起伏が乏しい人だなぁ。精神科医ってのはみんなこんな風なのか？"))
           (//
            (? (= 203 #f))
            (proc 14)
            (text "は")
            (proc 13)
            (text "を疑っていたのか")
            (proc 15)
            (text "確かに人を殺しかねないと言ってはいたが")
            (proc 15))
           (//
            (? (= 208 #f))
            (proc 14)
            (text "はジェニファーの事には固く口を閉ざしている。きっとこのまま何も話してはくれないだろうな。")
            (set-reg 208 #t))
           (//
            (proc 14)
            (text "の所へ")
            (proc 13)
            (text "とジェニファー")
            (proc 15)
            (text "ユリコまでもが通っていたなんて、なんて奇遇なんだろう。")))))
 (seg (? (= V 3) (= N 1))
      (if (</>
           (//
            (? (= 209 #f))
            (text "ジェニファーもここへ通っていると言う事は、カウンセリングを受けなければならない何かがあると言う事か？")
            (set-reg 209 #t))
           (//
            (? (= 210 #f))
            (proc 14)
            (text "はジェニファーの事を話してくれそうにないし")
            (text-raw 60393 60393)
            (text "彼女に直接聞いた方がいいのか。")
            (set-reg 210 #t))
           (//
            (text "もしかすると、パーティで元気がなかったのは悩みごとを抱えていたからなのか")
            (proc 15)))))
 (seg (? (= V 3) (= N 2))
      (if (</>
           (//
            (? (= 207 #f))
            (proc 13)
            (text "は謎を残したまま死んでしまった。ガイと一緒に死ねて本望だったのか、それとも")
            (proc 15))
           (//
            (? (= 211 #f))
            (text "彼女が犯人であったかどうかは今は結論は出ない。しかし、ギュンターまでもが")
            (proc 13)
            (text "を疑っていたのはショックだ。")
            (set-reg 211 #t))
           (// (proc 13) (proc 15) (text "キミは幸せだったかい？")))))
 (seg (? (= V 3) (= N 3))
      (if (</>
           (//
            (? (= 207 #f))
            (text "猟奇殺人事件はこのまま未解決で終わってしまうのだろうか？"))
           (//
            (? (= 212 #f))
            (proc 13)
            (text "が犯人")
            (proc 15)
            (text "もしそうだとしたら")
            (proc 15)
            (text "いや、他の誰かであって欲しい。")
            (set-reg 212 #t))
           (//
            (text "万が一、")
            (proc 13)
            (text "が犯人であるのなら、ここで事件は終わる筈だが、被害者のカラダのパーツはどこにあるんだろう。")))))
 (seg (? (= V 4)) (mes-jump "b:¥mes¥5_map.mes"))
 (seg*
  (nop@)
  (text "※※※　バグです　※※※" 'br)
  (text "Ｖ＝")
  (exec-mem 35072 "DISP V")
  (text "　Ｎ＝")
  (exec-mem 35072 "DISP N")))