(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 35072 "@0='レインツリー'")
  (define-proc 12 (<> (text "ジェイク")))
  (define-proc 13 (<> (text "アッシュ")))
  (define-proc 15 (<> (text-raw 60393 60393 60393)))
  (branch-reg 22
   (</>
    (/
     (cmd:204 100 199)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b24.gpc")
     (image-mem 0)
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (delay 50)
     (if (</> (// (? (!= M 9)) (nop@) (sound ' 2))))
     (image-file "gpc¥b25.gpc")
     (exec-mem 8192 "A 1")
     (text-frame 12 16 67 287)
     (text-reset 0)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (exec-mem 8192 "A 1")
     (image-mem 0)
     (image-file "gpc¥b25d.gpc")
     (image-mem 1)
     (image-file "gpc¥b25a.gpc")
     (image-mem 1)
     (exec-mem 8192 "A 0")
     (if (</>
          (//
           (? (!= M 9))
           (nop@)
           (sound ' 0)
           (sound ' "uso¥ap_09.uso")
           (sound ' 1)
           (set-var M 9))))
     (exec-mem 16384 12 16 67 287 3 1)
     (text-frame 14 328 69 383)
     (branch-reg 220
      (</>
       (/
        (text-frame 8 308 71 323)
        (proc 13)
        (proc 19)
        (proc 15)
        (text "ガイとクリスティはお亡くなりになったんですね。" '60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 12)
        (proc 19)
        (text "うん")
        (proc 15)
        (text-raw 60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 13)
        (proc 19)
        (text "大丈夫ですか？" '60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 12)
        (proc 19)
        (text "うん")
        (proc 15)
        (text "今はね。" '60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 13)
        (proc 19)
        (proc 15)
        (text "だったらいいんですけど。" '60392)
        (set-reg 220 #t))
       (/
        (text-frame 8 308 71 323)
        (proc 13)
        (proc 19)
        (text "いらっしゃい。" '60392))))
     (proc 18))
    (/
     (nop@)
     (sound ' 2)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "gpc¥b25.gpc")
     (image-mem 0)
     (image-file "gpc¥b25d.gpc")
     (image-mem 1)
     (image-file "gpc¥b25a.gpc")
     (image-mem 1)
     (sound ' 0)
     (sound ' "uso¥ap_09.uso")
     (sound ' 1)
     (set-var M 9)
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (cmd:204 24 26)
     (set-reg 22 #f)
     (set-var A 0))))
  (if (</> (// (? (!= A 255)) (nop@) (set-var A 0))))
  (set-var V 0)
  (set-var P 0)
  (set-var C 0)
  (repeat 9 (<> (exec-mem 35072 "A'[C]=0") (inc-var C 1)))
  (loop
   (branch-var P
    (</>
     (/
      (cmd:204 0 11)
      (define-proc 0 (<> (str " ") (text "　　見る　　") (str " ")))
      (set-reg 0 #t)
      (define-proc 1 (<> (str " ") (text "　　話す　　") (str " ")))
      (set-reg 1 #t)
      (define-proc 2 (<> (str " ") (text "　　聞く　　") (str " ")))
      (exec-mem 35072 "#2=#221")
      (define-proc 3 (<> (text "　　考える　　")))
      (exec-mem 35072 "#3=#221")
      (define-proc 4 (<> (str " ") (text "　移動する　") (str " ")))
      (exec-mem 35072 "#4=#221")
      (define-proc 5 (<> (str " ") (text "　システム　") (str " ")))
      (set-reg 5 #t)
      (set-var F 0)
      (mes-load? 0)
      (set-var P 1))
     (/
      (cmd:204 0 11)
      (branch-var V
       (</>
        (/
         (define-proc 0 (<> (text "　　辺りの様子　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　　") (proc 13) (text "　　") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0
          (<> (str " ") (text "　　") (proc 13) (text "　　") (str " ")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0
          (<> (str " ") (text "　　ガイの事　　") (str " ")))
         (set-reg 0 #t)
         (define-proc 1 (<> (text "　クリスティの事　")))
         (set-reg 1 #t)
         (define-proc 2
          (<> (str " ") (text "猟奇殺人事件の事") (str " ")))
         (set-reg 2 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0
          (<> (str " ") (text "　") (proc 13) (text "の事　") (str " ")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "　　ガイの事　　") (str " ")))
         (set-reg 1 #t)
         (define-proc 2 (<> (text "　クリスティの事　")))
         (set-reg 2 #t)
         (define-proc 3
          (<> (str " ") (text "猟奇殺人事件の事") (str " ")))
         (set-reg 3 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　他の場所へ　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　セーブ　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "ゲームを終了する") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 0)
         (if (</>
              (//
               (? (!= S 255))
               (nop@)
               (if (</>
                    (//
                     (? (!= A 255))
                     (nop@)
                     (set-var A 255)
                     (mes-load? "mes¥save.mec" 4096))))
               (mes-load? 4096)
               (if (</>
                    (// (? (= S 254)) (nop@) (set-var P 1))
                    (// (nop@) (set-var F 5) (mes-load? 0))))))))))
      (if (</> (// (? (= S 255)) (nop@) (set-var P 0)))))
     (/
      (if (</>
           (//
            (? (= V 4) (= 724 #f))
            (nop@)
            (nop@)
            (set-reg 24 #f)
            (set-reg 25 #f)
            (set-reg 26 #f))
           (//
            (nop@)
            (if (</> (// (? (= 26 #t)) (nop@) (set-var F 1) (mes-load? 4096))))
            (set-var F 6)
            (mes-load? 0))))
      (text-frame 14 328 69 383)
      (seg-call)
      (if (</>
           (//
            (? (= 222 #t) (= 224 #t) (= 226 #t) (= 228 #t))
            (nop@)
            (set-reg 724 #t))))
      (branch-reg 23 (</> (/ (proc 18)) (/ (set-reg 23 #f))))
      (set-var P 0))))))
 (seg (? (= V 0) (= N 0))
      (if (</>
           (//
            (? (= 100 #f))
            (text "客もまばらな店内には、ちょっと耳障りな程の音量で、音楽が流れている。隣客の声を聞かずにすむようにって配慮か")
            (proc 15)
            (set-reg 100 #t))
           (//
            (? (= 101 #f))
            (text "バー全体がガイというメジャーの人気プレイヤーの死を悼んでいるように見えるのは、僕の妄想だろうか")
            (proc 15)
            (set-reg 101 #t))
           (//
            (text "店内には、あまり装飾めいた物が無い。これだけ暗いと目を凝らしてそれらの物を見たがる人間もいないのだろう。")
            (set-reg 100 #f)
            (set-reg 101 #f)))))
 (seg (? (= V 0))
      (if (</>
           (//
            (? (= 102 #f))
            (text "特に落ち込んでいる様子ではない。当然だ、彼は熱心な野球ファンじゃないし、クリスティと親しかった訳でもないんだ。")
            (set-reg 102 #t))
           (//
            (? (= 103 #f))
            (text "僕が何かしでかすんじゃないかと思っているのか、じっとこちらを凝視している。")
            (set-reg 103 #t))
           (//
            (text "じっと僕を見ている。何故だろう、詮索されている訳ではないのに、彼の目で見られていると、全部話してしまいたくなる。")
            (set-reg 102 #f)
            (set-reg 103 #f)))))
 (seg (? (= V 1) (= 221 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "なんだか嫌な事ばかりが起きますね。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "なんだか僕が諸悪の根源のような気がしてきたよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "何を言ってるんですか。そんなことありませんよ。" '60392)
      (set-reg 221 #t))
 (seg (? (= V 1) (= 222 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "こんな時ですから、何を言っても耳に入らないかもしれませんが、いいですか、ご自分を責めたりしちゃ駄目ですよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "自分を責める？　そんなつもりはないよ")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "それなら何もいいませんけど")
      (proc 15)
      (text "本当に大丈夫ですか？" '60392)
      (set-reg 222 #t))
 (seg (? (= V 1))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (proc 12)
      (text "は見た目より繊細で脆い人間なんですから。くれぐれも悲観的な考えはしない事です。" '60392))
 (seg (? (= V 2) (= N 0) (= 223 #f))
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "自殺説まで出てるんだけどさ、ガイは自殺をしたと思う？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "路面の状態が悪くてハンドルを切り損ねたのが事実じゃないんですか？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (proc 15)
      (text "自殺だったら、僕のせいかもしれないよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "また")
      (proc 15)
      (text "悪い方に考えてどうなるものでもないでしょう。" '60392)
      (set-reg 223 #t))
 (seg (? (= V 2) (= N 0) (= 224 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "いいですか、ガイは事故だったんですよ。あなたに何か言われたのを苦にして自殺したなんてことはないんです。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "そんなの")
      (proc 15)
      (proc 13)
      (text "にわかるの？　ガイとクリスティは僕を恨んで死んで行ったのかもしれないんだよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "それはきっと違いますよ。勝手な思い込みはよくないです。" '60392)
      (set-reg 224 #t))
 (seg (? (= V 2) (= N 0))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "全ての事が自分の責任でなんて考えは、私に言わせれば思い上りですよ。一人の人間に出来る事なんて微々たるものです。" '60392))
 (seg (? (= V 2) (= N 1) (= 225 #f))
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "僕はクリスティを疑ってたんだ。どう考えても彼女が犯人なんじゃないかと")
      (proc 15)
      (text "そんな酷い事を考えていたんだよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "もしかすると、それは正しかったのかもしれないし、そうでないかもしれない。現時点では何も言えませんよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "それでも僕は彼女が猟奇殺人事件の、少なくともニューヨークで起きた事件の犯人だと決めつけてたんだ、心の中で。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (proc 12)
      (proc 15)
      (proc 15)
      (text-raw 60392)
      (set-reg 225 #t))
 (seg (? (= V 2) (= N 1) (= 226 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "そうやって自分を責めても彼女は戻って来ませんよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "そんなの")
      (proc 15)
      (text "言われなくてもわかってるさ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "だったら、もっと前向きになって下さい。真犯人を捕まえようと決心するとか")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "そんなの")
      (proc 15)
      (text "僕には探偵をやれる器なんてないんだ。無理なんだよ、ただの素人なんだから")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "困った人ですね。落ち込むのは構いませんが、もっとしっかり自分を持って下さいね。" '60392)
      (set-reg 226 #t))
 (seg (? (= V 2) (= N 1))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "考えても仕方ない事ですよ。")
      (proc 12)
      (text "には他に考えるべき事があると思うんです。" '60392))
 (seg (? (= V 2) (= N 2) (= 227 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "ニュースでは、ガイ達が犯人であると匂わせるような報道をしていましたけど、彼等がやった証拠はないんですよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "そうだよ。なのに僕は彼等を")
      (proc 15)
      (text "友人でありながら疑ってしまったんだよ。最低さ")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "そんな風に自分を責めても何も生れませんよ。" '60392)
      (set-reg 227 #t))
 (seg (? (= V 2) (= N 2) (= 228 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "現時点では誰が犯人かなんてまだわからないじゃないですか。自分を責める前に今までの事を整理してみればいいのに。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (proc 15)
      (text "僕は、ガイかクリスティが犯人だと決めつけていたんだよ。なのに、二人があんな事になってしまって")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "謎が多い事件ですけど、きっとどこかにヒントはある筈です。ただ、それに気付かないだけで")
      (proc 15)
      (text-raw 60392)
      (set-reg 228 #t))
 (seg (? (= V 2) (= N 2))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "冷静になって、事件を最初から考え直してみることです。" '60392))
 (seg (? (= V 3) (= N 0))
      (if (</>
           (//
            (? (= 229 #f))
            (text "僕のような悲観論者でもなく、常に冷静な目で周囲を見回している。")
            (proc 13)
            (text "の方が僕より探偵向きなのは間違いない")
            (proc 15)
            (set-reg 229 #t))
           (//
            (? (= 230 #f))
            (proc 13)
            (text "は、以前からガイやクリスティを犯人候補に上げてはいなかったな。僕も二人を信じてやれていれば")
            (proc 15)
            (set-reg 230 #t))
           (//
            (text "いい加減")
            (proc 13)
            (text "を頼るのは止めなきゃ。彼の好意に甘えてばかりはいられないんだ。")))))
 (seg (? (= V 3) (= N 1))
      (if (</>
           (//
            (? (= 231 #f))
            (text "運転を誤って")
            (proc 15)
            (text "ってのはありそうな話だが、ガイが自殺するとは思えない。全てが順調だったはずだ。")
            (set-reg 231 #t))
           (//
            (? (= 232 #f))
            (text "殺人を隠すには事故に見せかけるのが一番だ。ガイ達が誰かに殺されたって事もあり得る。タイミングが良すぎるし")
            (proc 15)
            (set-reg 232 #t))
           (//
            (text "これっきり猟奇殺人が起こらなくなったら、やっぱりガイが死んだからって事になる。ガイを犯人に仕立てるために")
            (proc 15)))))
 (seg (? (= V 3) (= N 2))
      (if (</>
           (//
            (? (= 233 #f))
            (text "好きな男と結ばれて、やっとこれからって時だったのに。これじゃクリスティは浮かばれない。")
            (set-reg 233 #t))
           (//
            (? (= 234 #f))
            (text "クリスティは本当は猟奇殺人犯で、それを知ったガイが心中しようと")
            (proc 15)
            (text "そういう事も考えられるかな？")
            (set-reg 234 #t))
           (//
            (text "死んでしまった人を悪く言うのは気が進まないが、クリスティが潔白だと言い切る事は出来ない。")))))
 (seg (? (= V 3) (= N 3))
      (if (</>
           (//
            (? (= 235 #f))
            (text "容疑者と目されていたガイとクリスティが死んだ今、次の殺人が起こる可能性は低いだろうな")
            (proc 15)
            (set-reg 235 #t))
           (//
            (? (= 236 #f))
            (text "これで殺人が跡絶えたら、死んだガイとクリスティが犯人だって事になるだろうなぁ。反論する事が出来ないのが悲しい。")
            (set-reg 236 #t))
           (//
            (text "これ以上被害者が出ないで済むんなら、僕はその方がいいんじゃないかと思うけどな")
            (proc 15)))))
 (seg (? (= V 4))
      (if (</>
           (//
            (? (= 724 #t))
            (text-frame 8 308 71 323)
            (proc 13)
            (proc 19)
            (text "いいですか、前向きですよ。前向きに考えて下さいね。" '60392)
            (cmd:203 1 0)
            (exec-mem 12288 0 20 (bytes 235 186) 72 368 0 1021 2)
            (text-frame 8 308 69 383)
            (cmd:203 1 1))))
      (mes-jump "b:¥mes¥5_map.mes"))
 (seg*
  (nop@)
  (text "※※※　バグです　※※※" 'br)
  (text "Ｖ＝")
  (exec-mem 35072 "DISP V")
  (text "　Ｎ＝")
  (exec-mem 35072 "DISP N")))