(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 35072 "@0='ファーバー監督のＮＹ邸'")
  (define-proc 12 (<> (text "ジェイク")))
  (define-proc 13 (<> (text "ファーバー")))
  (define-proc 15 (<> (text-raw 60393 60393 60393)))
  (branch-reg 22
   (</>
    (/
     (cmd:204 100 199)
     (if (</> (// (? (!= M 12)) (nop@) (sound ' 2))))
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "b:¥gpc¥b41.gpc")
     (image-mem 0)
     (if (</>
          (//
           (? (!= M 12))
           (nop@)
           (sound ' 0)
           (sound ' "uso¥ap_12.uso")
           (sound ' 1)
           (set-var M 12))))
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (delay 50)
     (image-file "b:¥gpc¥b42.gpc")
     (exec-mem 8192 "A 1")
     (text-frame 12 16 67 287)
     (text-reset 0)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (exec-mem 8192 "A 1")
     (image-mem 0)
     (image-file "b:¥gpc¥b42a.gpc")
     (image-mem 1)
     (exec-mem 8192 "A 0")
     (exec-mem 16384 12 16 67 287 3 1)
     (text-frame 14 328 69 383)
     (branch-reg 210
      (</>
       (/
        (text-frame 8 308 71 323)
        (proc 13)
        (proc 19)
        (text "ああ、キミか")
        (proc 15)
        (text "よく来たね。" '60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 12)
        (proc 19)
        (text "近くに来たので寄らせていただきました。" '60392)
        (proc 18)
        (text-frame 8 308 71 323)
        (proc 13)
        (proc 19)
        (text "そうか")
        (proc 15)
        (text-raw 60392)
        (set-reg 210 #t))
       (/
        (text-frame 8 308 71 323)
        (proc 13)
        (proc 19)
        (text "やあ、")
        (proc 12)
        (proc 15)
        (text "何の用だい。" '60392))))
     (proc 18))
    (/
     (nop@)
     (sound ' 2)
     (cmd:209 0 2)
     (image-file "gpc¥wall1.gpc")
     (image-mem 0)
     (image-file "gpc¥wall2.gpc")
     (image-mem 0)
     (image-file "gpc¥win_m.gpc")
     (image-mem 1 0)
     (exec-mem 256 11 1 58 36 1 2 0 2560 2560 1 1)
     (image-file "b:¥gpc¥b42.gpc")
     (image-mem 0)
     (image-file "b:¥gpc¥b42a.gpc")
     (image-mem 1)
     (sound ' 0)
     (sound ' "uso¥ap_12.uso")
     (sound ' 1)
     (set-var M 12)
     (cmd:209 1 2)
     (text-color 0 2 2)
     (text-frame 14 328 69 383)
     (cmd:203 1 1)
     (cmd:204 24 26)
     (set-reg 22 #f)
     (set-var A 0))))
  (if (</> (// (? (!= A 255)) (nop@) (set-var A 0))))
  (set-var V 0)
  (set-var P 0)
  (set-var C 0)
  (repeat 9 (<> (exec-mem 35072 "A'[C]=0") (inc-var C 1)))
  (loop
   (branch-var P
    (</>
     (/
      (cmd:204 0 11)
      (define-proc 0 (<> (str " ") (text "　　見る　　") (str " ")))
      (set-reg 0 #t)
      (define-proc 1 (<> (str " ") (text "　　話す　　") (str " ")))
      (set-reg 1 #t)
      (define-proc 2 (<> (str " ") (text "　　聞く　　") (str " ")))
      (exec-mem 35072 "#2=#211")
      (define-proc 3 (<> (text "　　考える　　")))
      (exec-mem 35072 "#3=#211")
      (define-proc 4 (<> (str " ") (text "　移動する　") (str " ")))
      (exec-mem 35072 "#4=#211")
      (define-proc 5 (<> (str " ") (text "　システム　") (str " ")))
      (set-reg 5 #t)
      (set-var F 0)
      (mes-load? 0)
      (set-var P 1))
     (/
      (cmd:204 0 11)
      (branch-var V
       (</>
        (/
         (define-proc 0 (<> (text "　　辺りの様子　　")))
         (set-reg 0 #t)
         (define-proc 1 (<> (text "　") (proc 13) (text "監督　")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　") (proc 13) (text "監督　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　パトリシアの事　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "ジェニファーの事") (str " ")))
         (set-reg 1 #t)
         (define-proc 2 (<> (text "　　メリルの事　　")))
         (set-reg 2 #t)
         (define-proc 3
          (<> (str " ") (text "猟奇殺人事件の事") (str " ")))
         (set-reg 3 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (proc 13) (text "監督の事")))
         (set-reg 0 #t)
         (define-proc 1 (<> (text "　パトリシアの事　")))
         (set-reg 1 #t)
         (define-proc 2
          (<> (str " ") (text "ジェニファーの事") (str " ")))
         (set-reg 2 #t)
         (define-proc 3 (<> (text "　　メリルの事　　")))
         (set-reg 3 #t)
         (define-proc 4
          (<> (str " ") (text "猟奇殺人事件の事") (str " ")))
         (set-reg 4 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　他の場所へ　　")))
         (set-reg 0 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 2))
        (/
         (define-proc 0 (<> (text "　　　セーブ　　　")))
         (set-reg 0 #t)
         (define-proc 1
          (<> (str " ") (text "ゲームを終了する") (str " ")))
         (set-reg 1 #t)
         (set-var F 3)
         (mes-load? 0)
         (set-var P 0)
         (if (</>
              (//
               (? (!= S 255))
               (nop@)
               (if (</>
                    (//
                     (? (!= A 255))
                     (nop@)
                     (set-var A 255)
                     (mes-load? "mes¥save.mec" 4096))))
               (mes-load? 4096)
               (if (</>
                    (// (? (= S 254)) (nop@) (set-var P 1))
                    (// (nop@) (set-var F 5) (mes-load? 0))))))))))
      (if (</> (// (? (= S 255)) (nop@) (set-var P 0)))))
     (/
      (if (</>
           (//
            (? (= V 4))
            (nop@)
            (nop@)
            (set-reg 24 #f)
            (set-reg 25 #f)
            (set-reg 26 #f))
           (//
            (nop@)
            (if (</> (// (? (= 26 #t)) (nop@) (set-var F 1) (mes-load? 4096))))
            (set-var F 6)
            (mes-load? 0))))
      (text-frame 14 328 69 383)
      (seg-call)
      (if (</>
           (//
            (? (= 246 #t) (= 250 #t) (= 252 #t) (= 244 #t))
            (nop@)
            (set-reg 721 #t))))
      (branch-reg 23 (</> (/ (proc 18)) (/ (set-reg 23 #f))))
      (set-var P 0))))))
 (seg (? (= V 0) (= N 0))
      (if (</>
           (//
            (? (= 100 #f))
            (text "以前に来た時と何の変わりもないはずなのに、ひどく淋しくて陰気な感じがする。")
            (set-reg 100 #t))
           (//
            (? (= 101 #f))
            (text "窓の外に見える晴天の空も、室内の暗さのために空虚な雰囲気を増すだけの効果しかない。")
            (set-reg 101 #t))
           (//
            (proc 13)
            (text "監督以外誰もいない。今の監督を慰められる人間など、誰もいないというわけか")
            (proc 15)
            (set-reg 100 #f)
            (set-reg 101 #f)))))
 (seg (? (= V 0) (= N 1))
      (if (</>
           (//
            (? (= 102 #f))
            (text "パトリシアを失ったショックのために、年齢よりもかなり老けて見えるようになってしまった。")
            (set-reg 102 #t))
           (//
            (? (= 103 #f))
            (text "撮影の最中に見た強い個性や、体から溢れ出てくるような力強さが失われてしまっている。まるで老人のようだ")
            (proc 15)
            (set-reg 103 #t))
           (//
            (text "何と言葉をかけていいのかためらわれるほど消沈して、見ていると痛々しくて仕方ない。")
            (set-reg 102 #f)
            (set-reg 103 #f)))))
 (seg (? (= V 1) (= 211 #f))
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "お体の具合はどうです？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "ん、ああ")
      (proc 15)
      (text "僕は元気だよ。そうさ、大丈夫なんだよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (proc 13)
      (text "監督")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "なんだか、疲れてしまって")
      (proc 15)
      (text "年かなぁ。" '60392)
      (set-reg 211 #t))
 (seg (? (= V 1) (= 212 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "これから")
      (proc 15)
      (text "どうしたらいいのかと")
      (proc 15)
      (text "途方にくれてしまうよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "監督")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "僕はもう、死人も同様なんだ")
      (proc 15)
      (text-raw 60392)
      (set-reg 212 #t))
 (seg (? (= V 1))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "放っておいてくれないか、今は何をする気力も無いんだ。" '60392))
 (seg (? (= V 2) (= N 0) (= 213 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (proc 15)
      (text "キミもひどいな。僕に娘の事を聞くなんて。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "すみません。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "いや、いいんだが")
      (proc 15)
      (text "まだ")
      (proc 15)
      (text "まだ首も見つからないままなんだ")
      (proc 15)
      (proc 15)
      (text "可哀想に")
      (proc 15)
      (text-raw 60392)
      (set-reg 213 #t))
 (seg (? (= V 2) (= N 0) (= 214 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "犯人は何の目的で")
      (proc 15)
      (text "どんな理由で娘の首を")
      (proc 15)
      (text "酷い話だ惨すぎる")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "監督")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "僕は、もう")
      (proc 15)
      (text "もう嫌だよ。" '60392)
      (set-reg 214 #t))
 (seg (? (= V 2) (= N 0))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "やはり何をおいても探しに行くべきだった")
      (proc 15)
      (text-raw 60392))
 (seg (? (= V 2) (= N 1) (= 215 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "彼女のことなんて")
      (proc 15)
      (text "もうどうだっていいよ。" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "監督？" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "パトリシア")
      (proc 15)
      (text "最後に話したのは")
      (proc 15)
      (text "喧嘩をしてて")
      (proc 15)
      (text "ああっ、悔やんでも悔やみ切れない")
      (proc 15)
      (text-raw 60392)
      (set-reg 215 #t))
 (seg (? (= V 2) (= N 1))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "考えても仕方ない事だが、僕がもっといい父親だったらと思うと")
      (proc 15)
      (text "身を切られる思いだよ。" '60392))
 (seg (? (= V 2) (= N 2) (= 216 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "今の僕にはもう俗世間の事は何も")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "監督")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "もう僕にはかまわないでくれ")
      (proc 15)
      (text-raw 60392)
      (set-reg 216 #t))
 (seg (? (= V 2) (= N 2))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "もういいんだ")
      (proc 15)
      (text "そんな事はどうでもいい")
      (proc 15)
      (text-raw 60392))
 (seg (? (= V 2) (= N 3) (= 217 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "犯人が憎い")
      (proc 15)
      (text "犯人を")
      (proc 15)
      (text "この手で殺してやりたい！" '60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 12)
      (proc 19)
      (text "監督、その気持ちはよくわかり")
      (proc 15)
      (text-raw 60392)
      (proc 18)
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "キミに一体何がわかると言うんだね？　キミが娘を失ったわけじゃないだろう？" '60392)
      (set-reg 217 #t))
 (seg (? (= V 2) (= N 3) (= 218 #f))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "この痛みは、僕以外の誰にもわからないさ。僕は")
      (proc 15)
      (text "僕は娘を")
      (proc 15)
      (text "大事な、最後の家族を失ったんだよ")
      (proc 15)
      (text-raw 60392)
      (set-reg 218 #t))
 (seg (? (= V 2) (= N 3))
      (text-frame 8 308 71 323)
      (proc 13)
      (proc 19)
      (text "何も考えたくない")
      (proc 15)
      (text "頼むよ、そっとしておいてくれ。" '60392))
 (seg (? (= V 3) (= N 0))
      (if (</>
           (//
            (? (= 219 #f))
            (text "被害者がジニーやシンディなら、まだ他人事で済んだのだが最愛の娘が無残な姿で見つかったんだ、冷静でいれる訳もない。")
            (set-reg 219 #t))
           (//
            (? (= 220 #f))
            (text "今は何を話しても無駄だ、もう少し時間が経たなければまともに物を考える事は不可能だろう。")
            (set-reg 220 #t))
           (//
            (text "またこんな光景を見る羽目になるとは")
            (proc 15)
            (text "悲しみに打ちひしがれた人間を見るのは、辛い事だ。")))))
 (seg (? (= V 3) (= N 1))
      (if (</>
           (//
            (? (= 221 #f))
            (text "何故パトリシアが殺されなければならなかったのか、まるで犯人の意図がわからない。")
            (set-reg 221 #t))
           (//
            (? (= 222 #f))
            (proc 13)
            (text "監督に恨みを持つ誰かの犯行なのだろうか？　何にしてもパトリシアが死ななければならない理由にはならない。")
            (set-reg 222 #t))
           (//
            (text "パトリシアをそれほどよく知っていたわけではないが、誰かに殺される程恨まれていたとは思えない。")))))
 (seg (? (= V 3) (= N 2))
      (if (</>
           (//
            (? (= 223 #f))
            (text "撮影が中止になった時には、あれほど親身に監督の心配をしていたのに、今日はどうしてここにいないんだろう。")
            (set-reg 223 #t))
           (//
            (? (= 224 #f))
            (text "パトリシアの不幸で打ちひしがれた監督を、ジェニファーはどうして慰めてあげないんだろうか？")
            (set-reg 224 #t))
           (// (text "今は他に考える事があると思うが") (proc 15)))))
 (seg (? (= V 3) (= N 3))
      (if (</>
           (//
            (? (= 225 #f))
            (text "監督がメリルと結婚しようとした時、パトリシアは頑なにそれを認めようとはしなかったと聞いたな")
            (proc 15)
            (proc 15)
            (set-reg 225 #t))
           (//
            (? (= 226 #f))
            (text "メリルは今、何もかも無くして自暴自棄になっている。何をしでかしてもおかしくはない。")
            (set-reg 226 #t))
           (//
            (text "監督との関係が終わってしまったとはいえ、かつての愛人を慰めに来ようなんて気は無いみたいだな。")))))
 (seg (? (= V 3) (= N 4))
      (if (</>
           (//
            (? (= 227 #f))
            (text "何故パトリシアを")
            (proc 15)
            (text "いや、同じ犯人の犯行と決まった訳ではない。しかし、死体を切り刻む手口は同一のものだ。")
            (set-reg 227 #t))
           (//
            (? (= 228 #f))
            (text "パトリシアの事件が一連の猟奇殺人と同一犯人の犯行だとすると、")
            (proc 13)
            (text "監督への怨恨という動機が見えて来るな")
            (proc 15)
            (set-reg 228 #t))
           (//
            (text "ガイが死んでも犯行は終わらなかった。やはり真犯人がいるって事だな。")))))
 (seg (? (= V 4)) (mes-jump "b:¥mes¥5_map.mes"))
 (seg*
  (nop@)
  (text "※※※　バグです　※※※" 'br)
  (text "Ｖ＝")
  (exec-mem 35072 "DISP V")
  (text "　Ｎ＝")
  (exec-mem 35072 "DISP N")))